// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: npx ts-node scripts/analyze-categories.ts
// Generated at: 2026-02-07T16:27:20.108Z
// Total venues: 274

export interface CategoryItem {
  slug: string;
  label: string;
  count: number;
}

export const GENERATED_AT = "2026-02-07T16:27:20.108Z";
export const TOTAL_VENUES = 274;

// Tags with venues (124 categories)
export const AVAILABLE_TAGS: CategoryItem[] = [
  {
    "slug": "beginner_friendly",
    "label": "Beginner Friendly",
    "count": 229
  },
  {
    "slug": "corporate_events",
    "label": "Corporate Events",
    "count": 213
  },
  {
    "slug": "premium_tech",
    "label": "Premium Tech",
    "count": 212
  },
  {
    "slug": "coaching_available",
    "label": "Coaching Available",
    "count": 204
  },
  {
    "slug": "leagues",
    "label": "Leagues",
    "count": 182
  },
  {
    "slug": "food_and_drinks",
    "label": "Food And Drinks",
    "count": 178
  },
  {
    "slug": "private_rooms",
    "label": "Private Rooms",
    "count": 147
  },
  {
    "slug": "club_rentals",
    "label": "Club Rentals",
    "count": 147
  },
  {
    "slug": "date_night",
    "label": "Date Night",
    "count": 105
  },
  {
    "slug": "budget_friendly",
    "label": "Budget Friendly",
    "count": 56
  },
  {
    "slug": "community_club",
    "label": "Community Club",
    "count": 54
  },
  {
    "slug": "serious_golfers",
    "label": "Serious Golfers",
    "count": 45
  },
  {
    "slug": "late_night",
    "label": "Late Night",
    "count": 43
  },
  {
    "slug": "family_friendly",
    "label": "Family Friendly",
    "count": 34
  },
  {
    "slug": "kids_friendly",
    "label": "Kids Friendly",
    "count": 32
  },
  {
    "slug": "serious_practice",
    "label": "Serious Practice",
    "count": 29
  },
  {
    "slug": "juniors_youth",
    "label": "Juniors Youth",
    "count": 25
  },
  {
    "slug": "families",
    "label": "Families",
    "count": 15
  },
  {
    "slug": "solo_practice",
    "label": "Solo Practice",
    "count": 14
  },
  {
    "slug": "upscale_lounge",
    "label": "Upscale Lounge",
    "count": 12
  },
  {
    "slug": "club_fitting",
    "label": "Club Fitting",
    "count": 12
  },
  {
    "slug": "indoor_golf",
    "label": "Indoor Golf",
    "count": 7
  },
  {
    "slug": "large_groups",
    "label": "Large Groups",
    "count": 7
  },
  {
    "slug": "family_fun_center",
    "label": "Family Fun Center",
    "count": 6
  },
  {
    "slug": "party_atmosphere",
    "label": "Party Atmosphere",
    "count": 5
  },
  {
    "slug": "events",
    "label": "Events",
    "count": 5
  },
  {
    "slug": "simulator",
    "label": "Simulator",
    "count": 5
  },
  {
    "slug": "lessons",
    "label": "Lessons",
    "count": 5
  },
  {
    "slug": "low_handicap",
    "label": "Low Handicap",
    "count": 5
  },
  {
    "slug": "sim_bar",
    "label": "Sim Bar",
    "count": 4
  },
  {
    "slug": "membership_only",
    "label": "Membership Only",
    "count": 4
  },
  {
    "slug": "tech_lab",
    "label": "Tech Lab",
    "count": 4
  },
  {
    "slug": "private_luxury",
    "label": "Private Luxury",
    "count": 4
  },
  {
    "slug": "indoor golf",
    "label": "Indoor Golf",
    "count": 3
  },
  {
    "slug": "modern",
    "label": "Modern",
    "count": 3
  },
  {
    "slug": "members_only",
    "label": "Members Only",
    "count": 3
  },
  {
    "slug": "social",
    "label": "Social",
    "count": 3
  },
  {
    "slug": "instruction",
    "label": "Instruction",
    "count": 3
  },
  {
    "slug": "group_friendly",
    "label": "Group Friendly",
    "count": 3
  },
  {
    "slug": "parties",
    "label": "Parties",
    "count": 3
  },
  {
    "slug": "casual_golf",
    "label": "Casual Golf",
    "count": 3
  },
  {
    "slug": "improvement",
    "label": "Improvement",
    "count": 2
  },
  {
    "slug": "golf_simulator",
    "label": "Golf Simulator",
    "count": 2
  },
  {
    "slug": "multi_sport",
    "label": "Multi Sport",
    "count": 2
  },
  {
    "slug": "casual",
    "label": "Casual",
    "count": 2
  },
  {
    "slug": "bachelor_parties",
    "label": "Bachelor Parties",
    "count": 2
  },
  {
    "slug": "membership",
    "label": "Membership",
    "count": 2
  },
  {
    "slug": "pro_shop",
    "label": "Pro Shop",
    "count": 2
  },
  {
    "slug": "corporate events",
    "label": "Corporate Events",
    "count": 2
  },
  {
    "slug": "group_events",
    "label": "Group Events",
    "count": 2
  },
  {
    "slug": "corporate_teams",
    "label": "Corporate Teams",
    "count": 2
  },
  {
    "slug": "entertainment",
    "label": "Entertainment",
    "count": 2
  },
  {
    "slug": "practice",
    "label": "Practice",
    "count": 2
  },
  {
    "slug": "bar",
    "label": "Bar",
    "count": 1
  },
  {
    "slug": "simulator golf",
    "label": "Simulator Golf",
    "count": 1
  },
  {
    "slug": "practice range",
    "label": "Practice Range",
    "count": 1
  },
  {
    "slug": "Trackman",
    "label": "Trackman",
    "count": 1
  },
  {
    "slug": "Indoor Golf",
    "label": "Indoor Golf",
    "count": 1
  },
  {
    "slug": "Simulators",
    "label": "Simulators",
    "count": 1
  },
  {
    "slug": "Lessons",
    "label": "Lessons",
    "count": 1
  },
  {
    "slug": "Events",
    "label": "Events",
    "count": 1
  },
  {
    "slug": "Family Owned",
    "label": "Family Owned",
    "count": 1
  },
  {
    "slug": "wifi",
    "label": "Wifi",
    "count": 1
  },
  {
    "slug": "training",
    "label": "Training",
    "count": 1
  },
  {
    "slug": "pga_professional",
    "label": "Pga Professional",
    "count": 1
  },
  {
    "slug": "private_suites",
    "label": "Private Suites",
    "count": 1
  },
  {
    "slug": "24/7_access",
    "label": "24/7 Access",
    "count": 1
  },
  {
    "slug": " memberships",
    "label": " Memberships",
    "count": 1
  },
  {
    "slug": "memberships",
    "label": "Memberships",
    "count": 1
  },
  {
    "slug": "tournaments",
    "label": "Tournaments",
    "count": 1
  },
  {
    "slug": "24/7 access",
    "label": "24/7 Access",
    "count": 1
  },
  {
    "slug": "booking required",
    "label": "Booking Required",
    "count": 1
  },
  {
    "slug": "indoor_facility",
    "label": "Indoor Facility",
    "count": 1
  },
  {
    "slug": "events_rentals",
    "label": "Events Rentals",
    "count": 1
  },
  {
    "slug": "multisport_sim",
    "label": "Multisport Sim",
    "count": 1
  },
  {
    "slug": "24_7_access",
    "label": "24 7 Access",
    "count": 1
  },
  {
    "slug": "self_service",
    "label": "Self Service",
    "count": 1
  },
  {
    "slug": "tech_focused",
    "label": "Tech Focused",
    "count": 1
  },
  {
    "slug": "golf_lessons",
    "label": "Golf Lessons",
    "count": 1
  },
  {
    "slug": "putting_lab",
    "label": "Putting Lab",
    "count": 1
  },
  {
    "slug": "golf_repair",
    "label": "Golf Repair",
    "count": 1
  },
  {
    "slug": "practice_memberships",
    "label": "Practice Memberships",
    "count": 1
  },
  {
    "slug": "data_driven",
    "label": "Data Driven",
    "count": 1
  },
  {
    "slug": "data_analytics",
    "label": "Data Analytics",
    "count": 1
  },
  {
    "slug": "golf simulator",
    "label": "Golf Simulator",
    "count": 1
  },
  {
    "slug": "lounge",
    "label": "Lounge",
    "count": 1
  },
  {
    "slug": "family-friendly",
    "label": "Family Friendly",
    "count": 1
  },
  {
    "slug": "date night",
    "label": "Date Night",
    "count": 1
  },
  {
    "slug": "bachelor party",
    "label": "Bachelor Party",
    "count": 1
  },
  {
    "slug": "birthday parties",
    "label": "Birthday Parties",
    "count": 1
  },
  {
    "slug": "practice facility",
    "label": "Practice Facility",
    "count": 1
  },
  {
    "slug": "whiskey_bar",
    "label": "Whiskey Bar",
    "count": 1
  },
  {
    "slug": "retail_fitting_center",
    "label": "Retail Fitting Center",
    "count": 1
  },
  {
    "slug": "beginners",
    "label": "Beginners",
    "count": 1
  },
  {
    "slug": "multi_sport_sim",
    "label": "Multi Sport Sim",
    "count": 1
  },
  {
    "slug": "portable_rentals",
    "label": "Portable Rentals",
    "count": 1
  },
  {
    "slug": "24_hour_access",
    "label": "24 Hour Access",
    "count": 1
  },
  {
    "slug": "training_studio",
    "label": "Training Studio",
    "count": 1
  },
  {
    "slug": "year_round_golf",
    "label": "Year Round Golf",
    "count": 1
  },
  {
    "slug": "lefty_friendly",
    "label": "Lefty Friendly",
    "count": 1
  },
  {
    "slug": "casual_play",
    "label": "Casual Play",
    "count": 1
  },
  {
    "slug": "modern_facility",
    "label": "Modern Facility",
    "count": 1
  },
  {
    "slug": "trackman",
    "label": "Trackman",
    "count": 1
  },
  {
    "slug": "simulator_golf",
    "label": "Simulator Golf",
    "count": 1
  },
  {
    "slug": "bar_lounge",
    "label": "Bar Lounge",
    "count": 1
  },
  {
    "slug": "private_events",
    "label": "Private Events",
    "count": 1
  },
  {
    "slug": "fitness_training",
    "label": "Fitness Training",
    "count": 1
  },
  {
    "slug": "simulator_rental",
    "label": "Simulator Rental",
    "count": 1
  },
  {
    "slug": "training_center",
    "label": "Training Center",
    "count": 1
  },
  {
    "slug": "after_hours_access",
    "label": "After Hours Access",
    "count": 1
  },
  {
    "slug": "Golf Simulators",
    "label": "Golf Simulators",
    "count": 1
  },
  {
    "slug": "Bar",
    "label": "Bar",
    "count": 1
  },
  {
    "slug": "Game Room",
    "label": "Game Room",
    "count": 1
  },
  {
    "slug": "Sports Bar",
    "label": "Sports Bar",
    "count": 1
  },
  {
    "slug": "Entertainment",
    "label": "Entertainment",
    "count": 1
  },
  {
    "slug": "golf",
    "label": "Golf",
    "count": 1
  },
  {
    "slug": "ada_accessible",
    "label": "Ada Accessible",
    "count": 1
  },
  {
    "slug": "golf simulators",
    "label": "Golf Simulators",
    "count": 1
  },
  {
    "slug": "full bar",
    "label": "Full Bar",
    "count": 1
  },
  {
    "slug": "adults_only",
    "label": "Adults Only",
    "count": 1
  },
  {
    "slug": "membership_club",
    "label": "Membership Club",
    "count": 1
  },
  {
    "slug": "social_leagues",
    "label": "Social Leagues",
    "count": 1
  },
  {
    "slug": "parties_and_events",
    "label": "Parties And Events",
    "count": 1
  },
  {
    "slug": "retro_gaming",
    "label": "Retro Gaming",
    "count": 1
  }
];

// Vibes with venues (44 categories)
export const AVAILABLE_VIBES: CategoryItem[] = [
  {
    "slug": "community_club",
    "label": "Community Club",
    "count": 152
  },
  {
    "slug": "tech_lab",
    "label": "Tech Lab",
    "count": 144
  },
  {
    "slug": "modern",
    "label": "Modern",
    "count": 135
  },
  {
    "slug": "sports_bar",
    "label": "Sports Bar",
    "count": 114
  },
  {
    "slug": "welcoming",
    "label": "Welcoming",
    "count": 102
  },
  {
    "slug": "casual",
    "label": "Casual",
    "count": 85
  },
  {
    "slug": "family_fun_center",
    "label": "Family Fun Center",
    "count": 66
  },
  {
    "slug": "private_luxury",
    "label": "Private Luxury",
    "count": 41
  },
  {
    "slug": "upscale_lounge",
    "label": "Upscale Lounge",
    "count": 40
  },
  {
    "slug": "industrial_training",
    "label": "Industrial Training",
    "count": 30
  },
  {
    "slug": "party_atmosphere",
    "label": "Party Atmosphere",
    "count": 16
  },
  {
    "slug": "social",
    "label": "Social",
    "count": 6
  },
  {
    "slug": "instructional",
    "label": "Instructional",
    "count": 3
  },
  {
    "slug": "private",
    "label": "Private",
    "count": 3
  },
  {
    "slug": "high-tech",
    "label": "High Tech",
    "count": 3
  },
  {
    "slug": "professional",
    "label": "Professional",
    "count": 3
  },
  {
    "slug": "Casual",
    "label": "Casual",
    "count": 2
  },
  {
    "slug": "Social",
    "label": "Social",
    "count": 2
  },
  {
    "slug": "exclusive",
    "label": "Exclusive",
    "count": 2
  },
  {
    "slug": "focused",
    "label": "Focused",
    "count": 2
  },
  {
    "slug": "flexible",
    "label": "Flexible",
    "count": 2
  },
  {
    "slug": "sports bar",
    "label": "Sports Bar",
    "count": 1
  },
  {
    "slug": "winter activity",
    "label": "Winter Activity",
    "count": 1
  },
  {
    "slug": "Modern",
    "label": "Modern",
    "count": 1
  },
  {
    "slug": "competitive",
    "label": "Competitive",
    "count": 1
  },
  {
    "slug": "professional_training",
    "label": "Professional Training",
    "count": 1
  },
  {
    "slug": "comfortable",
    "label": "Comfortable",
    "count": 1
  },
  {
    "slug": "technology focused",
    "label": "Technology Focused",
    "count": 1
  },
  {
    "slug": "autonomous",
    "label": "Autonomous",
    "count": 1
  },
  {
    "slug": "speakeasy",
    "label": "Speakeasy",
    "count": 1
  },
  {
    "slug": "spacious",
    "label": "Spacious",
    "count": 1
  },
  {
    "slug": "entertainment-focused",
    "label": "Entertainment Focused",
    "count": 1
  },
  {
    "slug": "relaxed",
    "label": "Relaxed",
    "count": 1
  },
  {
    "slug": "family_friendly",
    "label": "Family Friendly",
    "count": 1
  },
  {
    "slug": "social_lively",
    "label": "Social Lively",
    "count": 1
  },
  {
    "slug": "entertainment_complex",
    "label": "Entertainment Complex",
    "count": 1
  },
  {
    "slug": "high-energy",
    "label": "High Energy",
    "count": 1
  },
  {
    "slug": "tech-forward",
    "label": "Tech Forward",
    "count": 1
  },
  {
    "slug": "focused_training",
    "label": "Focused Training",
    "count": 1
  },
  {
    "slug": "Lively",
    "label": "Lively",
    "count": 1
  },
  {
    "slug": "Family-Friendly",
    "label": "Family Friendly",
    "count": 1
  },
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 1
  },
  {
    "slug": "fun",
    "label": "Fun",
    "count": 1
  },
  {
    "slug": "entertainment",
    "label": "Entertainment",
    "count": 1
  }
];

// Segments with venues (42 categories)
export const AVAILABLE_SEGMENTS: CategoryItem[] = [
  {
    "slug": "beginners",
    "label": "Beginners",
    "count": 237
  },
  {
    "slug": "families",
    "label": "Families",
    "count": 226
  },
  {
    "slug": "corporate_teams",
    "label": "Corporate Teams",
    "count": 223
  },
  {
    "slug": "serious_golfers",
    "label": "Serious Golfers",
    "count": 222
  },
  {
    "slug": "solo_practice",
    "label": "Solo Practice",
    "count": 211
  },
  {
    "slug": "large_groups",
    "label": "Large Groups",
    "count": 100
  },
  {
    "slug": "juniors_youth",
    "label": "Juniors Youth",
    "count": 82
  },
  {
    "slug": "coaches_instructors",
    "label": "Coaches Instructors",
    "count": 73
  },
  {
    "slug": "tourists_travelers",
    "label": "Tourists Travelers",
    "count": 29
  },
  {
    "slug": "low_handicap",
    "label": "Low Handicap",
    "count": 23
  },
  {
    "slug": "bachelor_parties",
    "label": "Bachelor Parties",
    "count": 15
  },
  {
    "slug": "groups",
    "label": "Groups",
    "count": 4
  },
  {
    "slug": "golfers",
    "label": "Golfers",
    "count": 2
  },
  {
    "slug": "league players",
    "label": "League Players",
    "count": 2
  },
  {
    "slug": "Families",
    "label": "Families",
    "count": 2
  },
  {
    "slug": "golf enthusiasts",
    "label": "Golf Enthusiasts",
    "count": 2
  },
  {
    "slug": "casual golfers",
    "label": "Casual Golfers",
    "count": 2
  },
  {
    "slug": "casual_golfers",
    "label": "Casual Golfers",
    "count": 2
  },
  {
    "slug": "casual players",
    "label": "Casual Players",
    "count": 1
  },
  {
    "slug": "Golfers of all skill levels",
    "label": "Golfers Of All Skill Levels",
    "count": 1
  },
  {
    "slug": "Casual golfers",
    "label": "Casual Golfers",
    "count": 1
  },
  {
    "slug": "golf_enthusiasts",
    "label": "Golf Enthusiasts",
    "count": 1
  },
  {
    "slug": "corporate_groups",
    "label": "Corporate Groups",
    "count": 1
  },
  {
    "slug": "friends",
    "label": "Friends",
    "count": 1
  },
  {
    "slug": "golf_teams",
    "label": "Golf Teams",
    "count": 1
  },
  {
    "slug": "competitors",
    "label": "Competitors",
    "count": 1
  },
  {
    "slug": "small_groups",
    "label": "Small Groups",
    "count": 1
  },
  {
    "slug": "golfers_looking_to_improve",
    "label": "Golfers Looking To Improve",
    "count": 1
  },
  {
    "slug": "competitive_golfers",
    "label": "Competitive Golfers",
    "count": 1
  },
  {
    "slug": "juniors",
    "label": "Juniors",
    "count": 1
  },
  {
    "slug": "club_fitting_clients",
    "label": "Club Fitting Clients",
    "count": 1
  },
  {
    "slug": "All skill levels; families; groups; corporate meetings; casual golfers.",
    "label": "All Skill Levels; Families; Groups; Corporate Meetings; Casual Golfers.",
    "count": 1
  },
  {
    "slug": "date_night",
    "label": "Date Night",
    "count": 1
  },
  {
    "slug": "adults",
    "label": "Adults",
    "count": 1
  },
  {
    "slug": "sports_fans",
    "label": "Sports Fans",
    "count": 1
  },
  {
    "slug": "leagues",
    "label": "Leagues",
    "count": 1
  },
  {
    "slug": "Golfers",
    "label": "Golfers",
    "count": 1
  },
  {
    "slug": "Casual Players",
    "label": "Casual Players",
    "count": 1
  },
  {
    "slug": "Groups",
    "label": "Groups",
    "count": 1
  },
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 1
  },
  {
    "slug": "adults_only",
    "label": "Adults Only",
    "count": 1
  },
  {
    "slug": "social_seekers",
    "label": "Social Seekers",
    "count": 1
  }
];

// Hardware with venues (33 categories)
export const AVAILABLE_HARDWARE: CategoryItem[] = [
  {
    "slug": "trackman",
    "label": "TrackMan",
    "count": 97
  },
  {
    "slug": "uneekor",
    "label": "Uneekor",
    "count": 16
  },
  {
    "slug": "golfzon",
    "label": "Golfzon",
    "count": 16
  },
  {
    "slug": "aboutgolf",
    "label": "AboutGolf",
    "count": 15
  },
  {
    "slug": "foresight",
    "label": "Foresight",
    "count": 12
  },
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 8
  },
  {
    "slug": "x-golf",
    "label": "X Golf",
    "count": 8
  },
  {
    "slug": "full-swing",
    "label": "Full Swing",
    "count": 6
  },
  {
    "slug": "foresight-sports",
    "label": "Foresight Sports",
    "count": 5
  },
  {
    "slug": "hd-golf",
    "label": "Hd Golf",
    "count": 4
  },
  {
    "slug": "protee",
    "label": "Protee",
    "count": 3
  },
  {
    "slug": "trugolf",
    "label": "Trugolf",
    "count": 3
  },
  {
    "slug": "toptracer",
    "label": "Toptracer",
    "count": 2
  },
  {
    "slug": "about-golf",
    "label": "About Golf",
    "count": 2
  },
  {
    "slug": "t2",
    "label": "T2",
    "count": 2
  },
  {
    "slug": "skytrak",
    "label": "SkyTrak",
    "count": 2
  },
  {
    "slug": "fullswing",
    "label": "Fullswing",
    "count": 2
  },
  {
    "slug": "bogolf",
    "label": "Bogolf",
    "count": 1
  },
  {
    "slug": "premium-golf-simulator",
    "label": "Premium Golf Simulator",
    "count": 1
  },
  {
    "slug": "proveex",
    "label": "Proveex",
    "count": 1
  },
  {
    "slug": "apogee",
    "label": "Apogee",
    "count": 1
  },
  {
    "slug": "golftec",
    "label": "Golftec",
    "count": 1
  },
  {
    "slug": "zen",
    "label": "Zen",
    "count": 1
  },
  {
    "slug": "sg-golf",
    "label": "Sg Golf",
    "count": 1
  },
  {
    "slug": "xgolf",
    "label": "Xgolf",
    "count": 1
  },
  {
    "slug": "optishot",
    "label": "Optishot",
    "count": 1
  },
  {
    "slug": "other",
    "label": "Other",
    "count": 1
  },
  {
    "slug": "pga-tour",
    "label": "Pga Tour",
    "count": 1
  },
  {
    "slug": "kgolf",
    "label": "Kgolf",
    "count": 1
  },
  {
    "slug": "bravo",
    "label": "Bravo",
    "count": 1
  },
  {
    "slug": "garmin",
    "label": "Garmin",
    "count": 1
  },
  {
    "slug": "square",
    "label": "Square",
    "count": 1
  },
  {
    "slug": "flightscope",
    "label": "Flightscope",
    "count": 1
  }
];

// Amenities with venues (3 categories)
export const AVAILABLE_AMENITIES: CategoryItem[] = [
  {
    "slug": "parking",
    "label": "Parking",
    "count": 274
  },
  {
    "slug": "coaching_available",
    "label": "Coaching",
    "count": 208
  },
  {
    "slug": "private_rooms",
    "label": "Private Rooms",
    "count": 117
  }
];

// Software with venues (0 categories)
export const AVAILABLE_SOFTWARE: CategoryItem[] = [];

// Launch monitors with venues (4 categories)
export const AVAILABLE_LAUNCH_MONITORS: CategoryItem[] = [
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 116
  },
  {
    "slug": "radar",
    "label": "Radar",
    "count": 96
  },
  {
    "slug": "hybrid",
    "label": "Hybrid",
    "count": 43
  },
  {
    "slug": "photometric_camera",
    "label": "Camera",
    "count": 19
  }
];

// Helper to get related links for a category (static, no DB query)
export function getStaticRelatedLinks(
  currentCategory: string,
  currentSlug: string,
  limit = 6
): Array<{ href: string; label: string; count: number }> {
  const links: Array<{ href: string; label: string; count: number }> = [];

  // Add vibes (if not current category)
  if (currentCategory !== "vibe") {
    for (const vibe of AVAILABLE_VIBES.slice(0, 2)) {
      links.push({ href: `/best/vibe/${vibe.slug}`, label: `Best ${vibe.label}`, count: vibe.count });
    }
  } else {
    // Add other vibes excluding current
    for (const vibe of AVAILABLE_VIBES.filter(v => v.slug !== currentSlug).slice(0, 2)) {
      links.push({ href: `/best/vibe/${vibe.slug}`, label: `Best ${vibe.label}`, count: vibe.count });
    }
  }

  // Add segments
  if (currentCategory !== "who-its-for") {
    for (const seg of AVAILABLE_SEGMENTS.slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/who-its-for/${seg.slug}`, label: `Best for ${seg.label}`, count: seg.count });
      }
    }
  } else {
    for (const seg of AVAILABLE_SEGMENTS.filter(s => s.slug !== currentSlug).slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/who-its-for/${seg.slug}`, label: `Best for ${seg.label}`, count: seg.count });
      }
    }
  }

  // Add hardware
  if (currentCategory !== "hardware") {
    for (const hw of AVAILABLE_HARDWARE.slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/hardware/${hw.slug}`, label: `Best ${hw.label}`, count: hw.count });
      }
    }
  } else {
    for (const hw of AVAILABLE_HARDWARE.filter(h => h.slug !== currentSlug).slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/hardware/${hw.slug}`, label: `Best ${hw.label}`, count: hw.count });
      }
    }
  }

  return links.slice(0, limit);
}

// Check if a category slug has venues
export function hasVenues(category: string, slug: string): boolean {
  switch (category) {
    case "tags": return AVAILABLE_TAGS.some(t => t.slug === slug);
    case "vibe": return AVAILABLE_VIBES.some(v => v.slug === slug);
    case "who-its-for": return AVAILABLE_SEGMENTS.some(s => s.slug === slug);
    case "hardware": return AVAILABLE_HARDWARE.some(h => h.slug === slug);
    case "amenities": return AVAILABLE_AMENITIES.some(a => a.slug === slug);
    case "software": return AVAILABLE_SOFTWARE.some(s => s.slug === slug);
    case "launch-monitor": return AVAILABLE_LAUNCH_MONITORS.some(l => l.slug === slug);
    default: return false;
  }
}
