// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: npx tsx scripts/analyze-categories.ts
// Generated at: 2026-02-11T12:07:03.440Z
// Total venues: 3870

export interface CategoryItem {
  slug: string;
  label: string;
  count: number;
}

export const GENERATED_AT = "2026-02-11T12:07:03.440Z";
export const TOTAL_VENUES = 3870;

// Tags with venues (680 categories)
export const AVAILABLE_TAGS: CategoryItem[] = [
  {
    "slug": "beginner_friendly",
    "label": "Beginner Friendly",
    "count": 3292
  },
  {
    "slug": "premium_tech",
    "label": "Premium Tech",
    "count": 2904
  },
  {
    "slug": "corporate_events",
    "label": "Corporate Events",
    "count": 2837
  },
  {
    "slug": "coaching_available",
    "label": "Coaching",
    "count": 2740
  },
  {
    "slug": "food_and_drinks",
    "label": "Food And Drinks",
    "count": 2346
  },
  {
    "slug": "leagues",
    "label": "Leagues",
    "count": 2201
  },
  {
    "slug": "club_rentals",
    "label": "Club Rentals",
    "count": 2129
  },
  {
    "slug": "private_rooms",
    "label": "Private Rooms",
    "count": 2071
  },
  {
    "slug": "date_night",
    "label": "Date Night",
    "count": 1210
  },
  {
    "slug": "budget_friendly",
    "label": "Budget Friendly",
    "count": 966
  },
  {
    "slug": "serious_practice",
    "label": "Serious Practice",
    "count": 718
  },
  {
    "slug": "community_club",
    "label": "Community Club",
    "count": 680
  },
  {
    "slug": "family_friendly",
    "label": "Family Friendly",
    "count": 674
  },
  {
    "slug": "serious_golfers",
    "label": "Serious Golfers",
    "count": 663
  },
  {
    "slug": "juniors_youth",
    "label": "Juniors Youth",
    "count": 662
  },
  {
    "slug": "kids_friendly",
    "label": "Kids Friendly",
    "count": 586
  },
  {
    "slug": "late_night",
    "label": "Late Night",
    "count": 493
  },
  {
    "slug": "club_fitting",
    "label": "Club Fitting",
    "count": 317
  },
  {
    "slug": "solo_practice",
    "label": "Solo Practice",
    "count": 300
  },
  {
    "slug": "families",
    "label": "Families",
    "count": 259
  },
  {
    "slug": "family_fun_center",
    "label": "Family Fun Center",
    "count": 173
  },
  {
    "slug": "pro_shop",
    "label": "Pro Shop",
    "count": 163
  },
  {
    "slug": "party_atmosphere",
    "label": "Party Atmosphere",
    "count": 155
  },
  {
    "slug": "casual",
    "label": "Casual",
    "count": 110
  },
  {
    "slug": "indoor_golf",
    "label": "Indoor Golf",
    "count": 104
  },
  {
    "slug": "corporate_teams",
    "label": "Corporate Teams",
    "count": 91
  },
  {
    "slug": "upscale_lounge",
    "label": "Upscale Lounge",
    "count": 84
  },
  {
    "slug": "large_groups",
    "label": "Large Groups",
    "count": 79
  },
  {
    "slug": "low_handicap",
    "label": "Low Handicap",
    "count": 65
  },
  {
    "slug": "modern",
    "label": "Modern",
    "count": 59
  },
  {
    "slug": "tech_lab",
    "label": "Tech Lab",
    "count": 58
  },
  {
    "slug": "group_friendly",
    "label": "Group Friendly",
    "count": 53
  },
  {
    "slug": "welcoming",
    "label": "Welcoming",
    "count": 52
  },
  {
    "slug": "retail_fitting_center",
    "label": "Retail Fitting Center",
    "count": 50
  },
  {
    "slug": "membership_only",
    "label": "Membership Only",
    "count": 45
  },
  {
    "slug": "sports_bar",
    "label": "Sports Bar",
    "count": 42
  },
  {
    "slug": "simulator",
    "label": "Simulator",
    "count": 41
  },
  {
    "slug": "events",
    "label": "Events",
    "count": 40
  },
  {
    "slug": "lessons",
    "label": "Lessons",
    "count": 39
  },
  {
    "slug": "group_events",
    "label": "Group Events",
    "count": 37
  },
  {
    "slug": "private_events",
    "label": "Private Events",
    "count": 34
  },
  {
    "slug": "tourists_travelers",
    "label": "Tourists Travelers",
    "count": 34
  },
  {
    "slug": "social",
    "label": "Social",
    "count": 34
  },
  {
    "slug": "training_studio",
    "label": "Training Studio",
    "count": 30
  },
  {
    "slug": "kid_friendly",
    "label": "Kid Friendly",
    "count": 27
  },
  {
    "slug": "private_luxury",
    "label": "Private Luxury",
    "count": 27
  },
  {
    "slug": "membership",
    "label": "Membership",
    "count": 25
  },
  {
    "slug": "adults_only",
    "label": "Adults Only",
    "count": 25
  },
  {
    "slug": "multi_sport",
    "label": "Multi Sport",
    "count": 24
  },
  {
    "slug": "beginners",
    "label": "Beginners",
    "count": 24
  },
  {
    "slug": "entertainment",
    "label": "Entertainment",
    "count": 23
  },
  {
    "slug": "practice",
    "label": "Practice",
    "count": 23
  },
  {
    "slug": "data_driven",
    "label": "Data Driven",
    "count": 22
  },
  {
    "slug": "golf_simulator",
    "label": "Golf Simulator",
    "count": 22
  },
  {
    "slug": "retro_gaming",
    "label": "Retro Gaming",
    "count": 21
  },
  {
    "slug": "ada_accessible",
    "label": "Ada Accessible",
    "count": 18
  },
  {
    "slug": "trackman",
    "label": "TrackMan",
    "count": 18
  },
  {
    "slug": "gift_cards",
    "label": "Gift Cards",
    "count": 17
  },
  {
    "slug": "instruction",
    "label": "Instruction",
    "count": 17
  },
  {
    "slug": "practice_memberships",
    "label": "Practice Memberships",
    "count": 17
  },
  {
    "slug": "sim_bar",
    "label": "Sim Bar",
    "count": 16
  },
  {
    "slug": "memberships",
    "label": "Memberships",
    "count": 16
  },
  {
    "slug": "practice_facility",
    "label": "Practice Facility",
    "count": 15
  },
  {
    "slug": "multi_sport_sim",
    "label": "Multi Sport Sim",
    "count": 15
  },
  {
    "slug": "upscale",
    "label": "Upscale",
    "count": 14
  },
  {
    "slug": "24_7_access",
    "label": "24 7 Access",
    "count": 14
  },
  {
    "slug": "group_lessons",
    "label": "Group Lessons",
    "count": 13
  },
  {
    "slug": "improvement",
    "label": "Improvement",
    "count": 13
  },
  {
    "slug": "byob",
    "label": "Byob",
    "count": 12
  },
  {
    "slug": "casual_atmosphere",
    "label": "Casual Atmosphere",
    "count": 12
  },
  {
    "slug": "members_only",
    "label": "Members Only",
    "count": 12
  },
  {
    "slug": "bachelor_parties",
    "label": "Bachelor Parties",
    "count": 11
  },
  {
    "slug": "private_rental",
    "label": "Private Rental",
    "count": 11
  },
  {
    "slug": "family_fun",
    "label": "Family Fun",
    "count": 11
  },
  {
    "slug": "lefty_friendly",
    "label": "Lefty Friendly",
    "count": 11
  },
  {
    "slug": "country_club",
    "label": "Country Club",
    "count": 11
  },
  {
    "slug": "simulators",
    "label": "Simulators",
    "count": 10
  },
  {
    "slug": "mobile_service",
    "label": "Mobile Service",
    "count": 10
  },
  {
    "slug": "casual_golf",
    "label": "Casual Golf",
    "count": 10
  },
  {
    "slug": "casual_play",
    "label": "Casual Play",
    "count": 9
  },
  {
    "slug": "social_golf",
    "label": "Social Golf",
    "count": 9
  },
  {
    "slug": "group_activities",
    "label": "Group Activities",
    "count": 9
  },
  {
    "slug": "wifi",
    "label": "Wifi",
    "count": 9
  },
  {
    "slug": "groups",
    "label": "Groups",
    "count": 9
  },
  {
    "slug": "retail",
    "label": "Retail",
    "count": 9
  },
  {
    "slug": "membership_club",
    "label": "Membership Club",
    "count": 9
  },
  {
    "slug": "custom_fitting",
    "label": "Custom Fitting",
    "count": 8
  },
  {
    "slug": "group_outings",
    "label": "Group Outings",
    "count": 8
  },
  {
    "slug": "bar",
    "label": "Bar",
    "count": 8
  },
  {
    "slug": "golf_lessons",
    "label": "Golf Lessons",
    "count": 8
  },
  {
    "slug": "practice_focused",
    "label": "Practice Focused",
    "count": 7
  },
  {
    "slug": "food_and_drink",
    "label": "Food And Drink",
    "count": 7
  },
  {
    "slug": "group_bookings",
    "label": "Group Bookings",
    "count": 6
  },
  {
    "slug": "private_bays",
    "label": "Private Bays",
    "count": 6
  },
  {
    "slug": "virtual_golf",
    "label": "Virtual Golf",
    "count": 6
  },
  {
    "slug": "driving_range",
    "label": "Driving Range",
    "count": 6
  },
  {
    "slug": "24_hour_access",
    "label": "24 Hour Access",
    "count": 6
  },
  {
    "slug": "indoor golf",
    "label": "Indoor Golf",
    "count": 6
  },
  {
    "slug": "family_entertainment",
    "label": "Family Entertainment",
    "count": 6
  },
  {
    "slug": "online_booking",
    "label": "Online Booking",
    "count": 5
  },
  {
    "slug": "fitness",
    "label": "Fitness",
    "count": 5
  },
  {
    "slug": "indoor_facility",
    "label": "Indoor Facility",
    "count": 5
  },
  {
    "slug": "private_rentals",
    "label": "Private Rentals",
    "count": 5
  },
  {
    "slug": "tech_focused",
    "label": "Tech Focused",
    "count": 5
  },
  {
    "slug": "fitness_training",
    "label": "Fitness Training",
    "count": 5
  },
  {
    "slug": "trackman_simulator",
    "label": "Trackman Simulator",
    "count": 5
  },
  {
    "slug": "climate_controlled",
    "label": "Climate Controlled",
    "count": 5
  },
  {
    "slug": "modern_facility",
    "label": "Modern Facility",
    "count": 5
  },
  {
    "slug": "parties",
    "label": "Parties",
    "count": 5
  },
  {
    "slug": "technology_driven",
    "label": "Technology Driven",
    "count": 5
  },
  {
    "slug": "year_round_golf",
    "label": "Year Round Golf",
    "count": 5
  },
  {
    "slug": "simulator_bays",
    "label": "Simulator Bays",
    "count": 5
  },
  {
    "slug": "uneekor",
    "label": "Uneekor",
    "count": 5
  },
  {
    "slug": "simulator_rental",
    "label": "Simulator Rental",
    "count": 4
  },
  {
    "slug": "training",
    "label": "Training",
    "count": 4
  },
  {
    "slug": "technology",
    "label": "Technology",
    "count": 4
  },
  {
    "slug": "membership_options",
    "label": "Membership Options",
    "count": 4
  },
  {
    "slug": "junior_friendly",
    "label": "Junior Friendly",
    "count": 4
  },
  {
    "slug": "speakeasy",
    "label": "Speakeasy",
    "count": 4
  },
  {
    "slug": "convenient",
    "label": "Convenient",
    "count": 4
  },
  {
    "slug": "social_atmosphere",
    "label": "Social Atmosphere",
    "count": 4
  },
  {
    "slug": "24/7_access",
    "label": "24/7 Access",
    "count": 4
  },
  {
    "slug": "membership_required",
    "label": "Membership Required",
    "count": 4
  },
  {
    "slug": "flexible_hours",
    "label": "Flexible Hours",
    "count": 4
  },
  {
    "slug": "social_club",
    "label": "Social Club",
    "count": 4
  },
  {
    "slug": "golf_simulation",
    "label": "Golf Simulation",
    "count": 4
  },
  {
    "slug": "tournaments",
    "label": "Tournaments",
    "count": 4
  },
  {
    "slug": "golf_simulators",
    "label": "Golf Simulators",
    "count": 4
  },
  {
    "slug": "private_club",
    "label": "Private Club",
    "count": 4
  },
  {
    "slug": "public_course",
    "label": "Public Course",
    "count": 4
  },
  {
    "slug": "food_drink",
    "label": "Food Drink",
    "count": 4
  },
  {
    "slug": "self_service",
    "label": "Self Service",
    "count": 4
  },
  {
    "slug": "outdoor_course",
    "label": "Outdoor Course",
    "count": 3
  },
  {
    "slug": "adult_friendly",
    "label": "Adult Friendly",
    "count": 3
  },
  {
    "slug": "tech_driven",
    "label": "Tech Driven",
    "count": 3
  },
  {
    "slug": "fitness_focused",
    "label": "Fitness Focused",
    "count": 3
  },
  {
    "slug": "year_round_access",
    "label": "Year Round Access",
    "count": 3
  },
  {
    "slug": "club_repair",
    "label": "Club Repair",
    "count": 3
  },
  {
    "slug": "golf_practice",
    "label": "Golf Practice",
    "count": 3
  },
  {
    "slug": "event_venue",
    "label": "Event Venue",
    "count": 3
  },
  {
    "slug": "outdoor_events",
    "label": "Outdoor Events",
    "count": 3
  },
  {
    "slug": "outdoor_golf",
    "label": "Outdoor Golf",
    "count": 3
  },
  {
    "slug": "indoor",
    "label": "Indoor",
    "count": 3
  },
  {
    "slug": "golf_fitness",
    "label": "Golf Fitness",
    "count": 3
  },
  {
    "slug": "membership_based",
    "label": "Membership Based",
    "count": 3
  },
  {
    "slug": "indoor_training",
    "label": "Indoor Training",
    "count": 3
  },
  {
    "slug": "residential",
    "label": "Residential",
    "count": 3
  },
  {
    "slug": "junior_youth",
    "label": "Junior Youth",
    "count": 3
  },
  {
    "slug": "performance_tracking",
    "label": "Performance Tracking",
    "count": 3
  },
  {
    "slug": "coaching",
    "label": "Coaching",
    "count": 3
  },
  {
    "slug": "birthday_parties",
    "label": "Birthday Parties",
    "count": 3
  },
  {
    "slug": "community_focused",
    "label": "Community Focused",
    "count": 3
  },
  {
    "slug": "golf_entertainment",
    "label": "Golf Entertainment",
    "count": 3
  },
  {
    "slug": "coaches_instructors",
    "label": "Coaches Instructors",
    "count": 3
  },
  {
    "slug": "league_play",
    "label": "League Play",
    "count": 3
  },
  {
    "slug": "training_center",
    "label": "Training Center",
    "count": 3
  },
  {
    "slug": "data_analytics",
    "label": "Data Analytics",
    "count": 3
  },
  {
    "slug": "golf",
    "label": "Golf",
    "count": 3
  },
  {
    "slug": "simulator_golf",
    "label": "Simulator Golf",
    "count": 3
  },
  {
    "slug": "seasonal",
    "label": "Seasonal",
    "count": 3
  },
  {
    "slug": "putting_green",
    "label": "Putting Green",
    "count": 3
  },
  {
    "slug": "family_golf",
    "label": "Family Golf",
    "count": 3
  },
  {
    "slug": "data_analysis",
    "label": "Data Analysis",
    "count": 3
  },
  {
    "slug": "accessible",
    "label": "Accessible",
    "count": 3
  },
  {
    "slug": "tech_friendly",
    "label": "Tech Friendly",
    "count": 3
  },
  {
    "slug": "golf_outings",
    "label": "Golf Outings",
    "count": 3
  },
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 3
  },
  {
    "slug": "toptracer",
    "label": "Toptracer",
    "count": 3
  },
  {
    "slug": "loyalty_program",
    "label": "Loyalty Program",
    "count": 3
  },
  {
    "slug": "practice_range",
    "label": "Practice Range",
    "count": 3
  },
  {
    "slug": "fitting",
    "label": "Fitting",
    "count": 3
  },
  {
    "slug": "lounge",
    "label": "Lounge",
    "count": 3
  },
  {
    "slug": "hotel_resort",
    "label": "Hotel Resort",
    "count": 3
  },
  {
    "slug": "virtual_courses",
    "label": "Virtual Courses",
    "count": 2
  },
  {
    "slug": "veteran_owned",
    "label": "Veteran Owned",
    "count": 2
  },
  {
    "slug": "modern_facilities",
    "label": "Modern Facilities",
    "count": 2
  },
  {
    "slug": "equipment_fitting",
    "label": "Equipment Fitting",
    "count": 2
  },
  {
    "slug": "club_fittings",
    "label": "Club Fittings",
    "count": 2
  },
  {
    "slug": "private_lessons",
    "label": "Private Lessons",
    "count": 2
  },
  {
    "slug": "year_round_training",
    "label": "Year Round Training",
    "count": 2
  },
  {
    "slug": "retail_store",
    "label": "Retail Store",
    "count": 2
  },
  {
    "slug": "Trackman",
    "label": "Trackman",
    "count": 2
  },
  {
    "slug": "improvement_focused",
    "label": "Improvement Focused",
    "count": 2
  },
  {
    "slug": "unlimited_access",
    "label": "Unlimited Access",
    "count": 2
  },
  {
    "slug": "game_improvement",
    "label": "Game Improvement",
    "count": 2
  },
  {
    "slug": "weddings",
    "label": "Weddings",
    "count": 2
  },
  {
    "slug": "fundraisers",
    "label": "Fundraisers",
    "count": 2
  },
  {
    "slug": "beginners_friendly",
    "label": "Beginners Friendly",
    "count": 2
  },
  {
    "slug": "private_suites",
    "label": "Private Suites",
    "count": 2
  },
  {
    "slug": "custom_design",
    "label": "Custom Design",
    "count": 2
  },
  {
    "slug": "commercial",
    "label": "Commercial",
    "count": 2
  },
  {
    "slug": "customizable",
    "label": "Customizable",
    "count": 2
  },
  {
    "slug": "night_golf",
    "label": "Night Golf",
    "count": 2
  },
  {
    "slug": "group_sessions",
    "label": "Group Sessions",
    "count": 2
  },
  {
    "slug": "no_walk_ins",
    "label": "No Walk Ins",
    "count": 2
  },
  {
    "slug": "performance_training",
    "label": "Performance Training",
    "count": 2
  },
  {
    "slug": "bar_food",
    "label": "Bar Food",
    "count": 2
  },
  {
    "slug": "casual_gaming",
    "label": "Casual Gaming",
    "count": 2
  },
  {
    "slug": "bays",
    "label": "Bays",
    "count": 2
  },
  {
    "slug": "arizona",
    "label": "Arizona",
    "count": 2
  },
  {
    "slug": "weekend_activity",
    "label": "Weekend Activity",
    "count": 2
  },
  {
    "slug": "social_memberships",
    "label": "Social Memberships",
    "count": 2
  },
  {
    "slug": "speed_training",
    "label": "Speed Training",
    "count": 2
  },
  {
    "slug": "Sports Bar",
    "label": "Sports Bar",
    "count": 2
  },
  {
    "slug": "private_instruction",
    "label": "Private Instruction",
    "count": 2
  },
  {
    "slug": "customizable_packages",
    "label": "Customizable Packages",
    "count": 2
  },
  {
    "slug": "by_appointment",
    "label": "By Appointment",
    "count": 2
  },
  {
    "slug": "custom_clubs",
    "label": "Custom Clubs",
    "count": 2
  },
  {
    "slug": "batting_cages",
    "label": "Batting Cages",
    "count": 2
  },
  {
    "slug": "outdoor_range",
    "label": "Outdoor Range",
    "count": 2
  },
  {
    "slug": "golf_instruction",
    "label": "Golf Instruction",
    "count": 2
  },
  {
    "slug": "scenic_course",
    "label": "Scenic Course",
    "count": 2
  },
  {
    "slug": "winter_golf",
    "label": "Winter Golf",
    "count": 2
  },
  {
    "slug": "flexible_pricing",
    "label": "Flexible Pricing",
    "count": 2
  },
  {
    "slug": "indoor_outdoor",
    "label": "Indoor Outdoor",
    "count": 2
  },
  {
    "slug": "BYOB",
    "label": "BYOB",
    "count": 2
  },
  {
    "slug": "retail_fitting",
    "label": "Retail Fitting",
    "count": 2
  },
  {
    "slug": "nightlife",
    "label": "Nightlife",
    "count": 2
  },
  {
    "slug": "restaurant",
    "label": "Restaurant",
    "count": 2
  },
  {
    "slug": "golf_membership",
    "label": "Golf Membership",
    "count": 2
  },
  {
    "slug": "bookings",
    "label": "Bookings",
    "count": 2
  },
  {
    "slug": "recreation",
    "label": "Recreation",
    "count": 2
  },
  {
    "slug": "full bar",
    "label": "Full Bar",
    "count": 2
  },
  {
    "slug": "mini_golf",
    "label": "Mini Golf",
    "count": 2
  },
  {
    "slug": "adult_programs",
    "label": "Adult Programs",
    "count": 2
  },
  {
    "slug": "golf_tech",
    "label": "Golf Tech",
    "count": 2
  },
  {
    "slug": "golf entertainment",
    "label": "Golf Entertainment",
    "count": 2
  },
  {
    "slug": "group_rates",
    "label": "Group Rates",
    "count": 2
  },
  {
    "slug": "simulator_access",
    "label": "Simulator Access",
    "count": 2
  },
  {
    "slug": "golf_technology",
    "label": "Golf Technology",
    "count": 2
  },
  {
    "slug": "golf_leagues",
    "label": "Golf Leagues",
    "count": 2
  },
  {
    "slug": "junior_program",
    "label": "Junior Program",
    "count": 2
  },
  {
    "slug": "foresight_sports",
    "label": "Foresight Sports",
    "count": 2
  },
  {
    "slug": "gspro",
    "label": "GSPro",
    "count": 2
  },
  {
    "slug": "climate_control",
    "label": "Climate Control",
    "count": 2
  },
  {
    "slug": "practice facility",
    "label": "Practice Facility",
    "count": 2
  },
  {
    "slug": "topgolf",
    "label": "Topgolf",
    "count": 2
  },
  {
    "slug": "heated_bays",
    "label": "Heated Bays",
    "count": 2
  },
  {
    "slug": "membership_available",
    "label": "Membership Available",
    "count": 2
  },
  {
    "slug": "corporate events",
    "label": "Corporate Events",
    "count": 2
  },
  {
    "slug": "tv_sports",
    "label": "Tv Sports",
    "count": 2
  },
  {
    "slug": "pga_professional",
    "label": "Pga Professional",
    "count": 2
  },
  {
    "slug": "year_round",
    "label": "Year Round",
    "count": 1
  },
  {
    "slug": "walk_in_friendly",
    "label": "Walk In Friendly",
    "count": 1
  },
  {
    "slug": "short_game_practice",
    "label": "Short Game Practice",
    "count": 1
  },
  {
    "slug": "women_friendly",
    "label": "Women Friendly",
    "count": 1
  },
  {
    "slug": "remote_coaching",
    "label": "Remote Coaching",
    "count": 1
  },
  {
    "slug": "dallas_area",
    "label": "Dallas Area",
    "count": 1
  },
  {
    "slug": "location_based",
    "label": "Location Based",
    "count": 1
  },
  {
    "slug": "long_island",
    "label": "Long Island",
    "count": 1
  },
  {
    "slug": "team_practice",
    "label": "Team Practice",
    "count": 1
  },
  {
    "slug": "indoor_climate_control",
    "label": "Indoor Climate Control",
    "count": 1
  },
  {
    "slug": "membership_benefits",
    "label": "Membership Benefits",
    "count": 1
  },
  {
    "slug": "affordable_training",
    "label": "Affordable Training",
    "count": 1
  },
  {
    "slug": "secure_payment",
    "label": "Secure Payment",
    "count": 1
  },
  {
    "slug": "skill_improvement",
    "label": "Skill Improvement",
    "count": 1
  },
  {
    "slug": "professional_services",
    "label": "Professional Services",
    "count": 1
  },
  {
    "slug": "specialty_retail",
    "label": "Specialty Retail",
    "count": 1
  },
  {
    "slug": "social_fun",
    "label": "Social Fun",
    "count": 1
  },
  {
    "slug": "bistro_atmosphere",
    "label": "Bistro Atmosphere",
    "count": 1
  },
  {
    "slug": "charity_events",
    "label": "Charity Events",
    "count": 1
  },
  {
    "slug": "fitness_integration",
    "label": "Fitness Integration",
    "count": 1
  },
  {
    "slug": "events_weddings",
    "label": "Events Weddings",
    "count": 1
  },
  {
    "slug": "destination_golf",
    "label": "Destination Golf",
    "count": 1
  },
  {
    "slug": "group_coaching",
    "label": "Group Coaching",
    "count": 1
  },
  {
    "slug": "indoor_simulators",
    "label": "Indoor Simulators",
    "count": 1
  },
  {
    "slug": "trackman_technology",
    "label": "Trackman Technology",
    "count": 1
  },
  {
    "slug": "elite_coaching",
    "label": "Elite Coaching",
    "count": 1
  },
  {
    "slug": "north_grafton",
    "label": "North Grafton",
    "count": 1
  },
  {
    "slug": "group_booking",
    "label": "Group Booking",
    "count": 1
  },
  {
    "slug": "technology_focused",
    "label": "Technology Focused",
    "count": 1
  },
  {
    "slug": "improvement_tools",
    "label": "Improvement Tools",
    "count": 1
  },
  {
    "slug": "bookable_app",
    "label": "Bookable App",
    "count": 1
  },
  {
    "slug": "limited_membership",
    "label": "Limited Membership",
    "count": 1
  },
  {
    "slug": "unlimited_play",
    "label": "Unlimited Play",
    "count": 1
  },
  {
    "slug": "byob_allowed",
    "label": "Byob Allowed",
    "count": 1
  },
  {
    "slug": "indoor_year_round",
    "label": "Indoor Year Round",
    "count": 1
  },
  {
    "slug": "capped_memberships",
    "label": "Capped Memberships",
    "count": 1
  },
  {
    "slug": "access_controlled",
    "label": "Access Controlled",
    "count": 1
  },
  {
    "slug": "no_crowds",
    "label": "No Crowds",
    "count": 1
  },
  {
    "slug": "public_access",
    "label": "Public Access",
    "count": 1
  },
  {
    "slug": "online_academy",
    "label": "Online Academy",
    "count": 1
  },
  {
    "slug": "mobile_app",
    "label": "Mobile App",
    "count": 1
  },
  {
    "slug": "airport_convenient",
    "label": "Airport Convenient",
    "count": 1
  },
  {
    "slug": "financial_district",
    "label": "Financial District",
    "count": 1
  },
  {
    "slug": "one_on_one",
    "label": "One On One",
    "count": 1
  },
  {
    "slug": "unlimited_bay_reservations",
    "label": "Unlimited Bay Reservations",
    "count": 1
  },
  {
    "slug": "affordable_membership",
    "label": "Affordable Membership",
    "count": 1
  },
  {
    "slug": "state_of_the_art",
    "label": "State Of The Art",
    "count": 1
  },
  {
    "slug": "nebraska_iowa",
    "label": "Nebraska Iowa",
    "count": 1
  },
  {
    "slug": "bar_promotions",
    "label": "Bar Promotions",
    "count": 1
  },
  {
    "slug": "interactive_experience",
    "label": "Interactive Experience",
    "count": 1
  },
  {
    "slug": "all_inclusive",
    "label": "All Inclusive",
    "count": 1
  },
  {
    "slug": "new_england",
    "label": "New England",
    "count": 1
  },
  {
    "slug": "quality_service",
    "label": "Quality Service",
    "count": 1
  },
  {
    "slug": "local_expert",
    "label": "Local Expert",
    "count": 1
  },
  {
    "slug": "white_glove_service",
    "label": "White Glove Service",
    "count": 1
  },
  {
    "slug": "social_outing",
    "label": "Social Outing",
    "count": 1
  },
  {
    "slug": "privacy_focused",
    "label": "Privacy Focused",
    "count": 1
  },
  {
    "slug": "customizable_sessions",
    "label": "Customizable Sessions",
    "count": 1
  },
  {
    "slug": "tpc_courses",
    "label": "Tpc Courses",
    "count": 1
  },
  {
    "slug": "simulator_rentals",
    "label": "Simulator Rentals",
    "count": 1
  },
  {
    "slug": "mobile_simulators",
    "label": "Mobile Simulators",
    "count": 1
  },
  {
    "slug": "equipment_rental",
    "label": "Equipment Rental",
    "count": 1
  },
  {
    "slug": "24_hours",
    "label": "24 Hours",
    "count": 1
  },
  {
    "slug": "adult_leagues",
    "label": "Adult Leagues",
    "count": 1
  },
  {
    "slug": "gym_access",
    "label": "Gym Access",
    "count": 1
  },
  {
    "slug": "group_practice",
    "label": "Group Practice",
    "count": 1
  },
  {
    "slug": "convenient_booking",
    "label": "Convenient Booking",
    "count": 1
  },
  {
    "slug": "monthly_memberships",
    "label": "Monthly Memberships",
    "count": 1
  },
  {
    "slug": "no_long_term_contract",
    "label": "No Long Term Contract",
    "count": 1
  },
  {
    "slug": "indoor_practice",
    "label": "Indoor Practice",
    "count": 1
  },
  {
    "slug": "no_wait_time",
    "label": "No Wait Time",
    "count": 1
  },
  {
    "slug": "golden_tee",
    "label": "Golden Tee",
    "count": 1
  },
  {
    "slug": "no_staff",
    "label": "No Staff",
    "count": 1
  },
  {
    "slug": "convenient_access",
    "label": "Convenient Access",
    "count": 1
  },
  {
    "slug": "atmosphere_21+",
    "label": "Atmosphere 21+",
    "count": 1
  },
  {
    "slug": "custom_events",
    "label": "Custom Events",
    "count": 1
  },
  {
    "slug": "nashville",
    "label": "Nashville",
    "count": 1
  },
  {
    "slug": "bethpage",
    "label": "Bethpage",
    "count": 1
  },
  {
    "slug": "ny",
    "label": "Ny",
    "count": 1
  },
  {
    "slug": "birmingham_al",
    "label": "Birmingham Al",
    "count": 1
  },
  {
    "slug": "chardon_area",
    "label": "Chardon Area",
    "count": 1
  },
  {
    "slug": "recreational_golf",
    "label": "Recreational Golf",
    "count": 1
  },
  {
    "slug": "affordable_option",
    "label": "Affordable Option",
    "count": 1
  },
  {
    "slug": "community_events",
    "label": "Community Events",
    "count": 1
  },
  {
    "slug": "gilbert",
    "label": "Gilbert",
    "count": 1
  },
  {
    "slug": "outdoor_activity",
    "label": "Outdoor Activity",
    "count": 1
  },
  {
    "slug": "granbury",
    "label": "Granbury",
    "count": 1
  },
  {
    "slug": "central_texas",
    "label": "Central Texas",
    "count": 1
  },
  {
    "slug": "leander",
    "label": "Leander",
    "count": 1
  },
  {
    "slug": "lubbock",
    "label": "Lubbock",
    "count": 1
  },
  {
    "slug": "fun",
    "label": "Fun",
    "count": 1
  },
  {
    "slug": "mesa",
    "label": "Mesa",
    "count": 1
  },
  {
    "slug": "peoria_az",
    "label": "Peoria Az",
    "count": 1
  },
  {
    "slug": "local_golf",
    "label": "Local Golf",
    "count": 1
  },
  {
    "slug": "ponte_vedra",
    "label": "Ponte Vedra",
    "count": 1
  },
  {
    "slug": "florida",
    "label": "Florida",
    "count": 1
  },
  {
    "slug": "social_sport",
    "label": "Social Sport",
    "count": 1
  },
  {
    "slug": "training_available",
    "label": "Training Available",
    "count": 1
  },
  {
    "slug": "tyler_tx",
    "label": "Tyler Tx",
    "count": 1
  },
  {
    "slug": "sports_entertainment",
    "label": "Sports Entertainment",
    "count": 1
  },
  {
    "slug": "putting_lab",
    "label": "Putting Lab",
    "count": 1
  },
  {
    "slug": "golf_repair",
    "label": "Golf Repair",
    "count": 1
  },
  {
    "slug": "custom_installations",
    "label": "Custom Installations",
    "count": 1
  },
  {
    "slug": "luxury_experience",
    "label": "Luxury Experience",
    "count": 1
  },
  {
    "slug": "atlanta_based",
    "label": "Atlanta Based",
    "count": 1
  },
  {
    "slug": "comprehensive_services",
    "label": "Comprehensive Services",
    "count": 1
  },
  {
    "slug": "design_build",
    "label": "Design Build",
    "count": 1
  },
  {
    "slug": "after_hours_access",
    "label": "After Hours Access",
    "count": 1
  },
  {
    "slug": "bar_and_lounge",
    "label": "Bar And Lounge",
    "count": 1
  },
  {
    "slug": "putting_analysis",
    "label": "Putting Analysis",
    "count": 1
  },
  {
    "slug": "Golf Simulators",
    "label": "Golf Simulators",
    "count": 1
  },
  {
    "slug": "Bar",
    "label": "Bar",
    "count": 1
  },
  {
    "slug": "Game Room",
    "label": "Game Room",
    "count": 1
  },
  {
    "slug": "Entertainment",
    "label": "Entertainment",
    "count": 1
  },
  {
    "slug": "weekend_warriors",
    "label": "Weekend Warriors",
    "count": 1
  },
  {
    "slug": "structured_practice",
    "label": "Structured Practice",
    "count": 1
  },
  {
    "slug": "entertainment_center",
    "label": "Entertainment Center",
    "count": 1
  },
  {
    "slug": "upscale_environment",
    "label": "Upscale Environment",
    "count": 1
  },
  {
    "slug": "training_aid_available",
    "label": "Training Aid Available",
    "count": 1
  },
  {
    "slug": "exclusive_events",
    "label": "Exclusive Events",
    "count": 1
  },
  {
    "slug": "juniors_friendly",
    "label": "Juniors Friendly",
    "count": 1
  },
  {
    "slug": "adult_focused",
    "label": "Adult Focused",
    "count": 1
  },
  {
    "slug": "indoor_entertainment",
    "label": "Indoor Entertainment",
    "count": 1
  },
  {
    "slug": "weather_proof",
    "label": "Weather Proof",
    "count": 1
  },
  {
    "slug": "app_based_booking",
    "label": "App Based Booking",
    "count": 1
  },
  {
    "slug": "structured_lessons",
    "label": "Structured Lessons",
    "count": 1
  },
  {
    "slug": "couples_friendly",
    "label": "Couples Friendly",
    "count": 1
  },
  {
    "slug": "bar_lounge",
    "label": "Bar Lounge",
    "count": 1
  },
  {
    "slug": "family_owned",
    "label": "Family Owned",
    "count": 1
  },
  {
    "slug": "private_parties",
    "label": "Private Parties",
    "count": 1
  },
  {
    "slug": "festivals",
    "label": "Festivals",
    "count": 1
  },
  {
    "slug": "trade_shows",
    "label": "Trade Shows",
    "count": 1
  },
  {
    "slug": "fitness_center",
    "label": "Fitness Center",
    "count": 1
  },
  {
    "slug": "indoor_events",
    "label": "Indoor Events",
    "count": 1
  },
  {
    "slug": "pa_golf",
    "label": "Pa Golf",
    "count": 1
  },
  {
    "slug": "resort_amenities",
    "label": "Resort Amenities",
    "count": 1
  },
  {
    "slug": "all_skill_levels",
    "label": "All Skill Levels",
    "count": 1
  },
  {
    "slug": "downtown",
    "label": "Downtown",
    "count": 1
  },
  {
    "slug": "scenic_views",
    "label": "Scenic Views",
    "count": 1
  },
  {
    "slug": "private_appointment",
    "label": "Private Appointment",
    "count": 1
  },
  {
    "slug": "baseball_training",
    "label": "Baseball Training",
    "count": 1
  },
  {
    "slug": "lessons_training",
    "label": "Lessons Training",
    "count": 1
  },
  {
    "slug": "hittrax",
    "label": "Hittrax",
    "count": 1
  },
  {
    "slug": "arcade",
    "label": "Arcade",
    "count": 1
  },
  {
    "slug": "executive_course",
    "label": "Executive Course",
    "count": 1
  },
  {
    "slug": "historic_course",
    "label": "Historic Course",
    "count": 1
  },
  {
    "slug": "walking_friendly",
    "label": "Walking Friendly",
    "count": 1
  },
  {
    "slug": "mountain_valley",
    "label": "Mountain Valley",
    "count": 1
  },
  {
    "slug": "day_trip",
    "label": "Day Trip",
    "count": 1
  },
  {
    "slug": "famous_courses",
    "label": "Famous Courses",
    "count": 1
  },
  {
    "slug": "mini_games",
    "label": "Mini Games",
    "count": 1
  },
  {
    "slug": "mobile_simulator",
    "label": "Mobile Simulator",
    "count": 1
  },
  {
    "slug": "loyalty_club",
    "label": "Loyalty Club",
    "count": 1
  },
  {
    "slug": "junior_golf",
    "label": "Junior Golf",
    "count": 1
  },
  {
    "slug": "golfzon",
    "label": "Golfzon",
    "count": 1
  },
  {
    "slug": "indoor_leagues",
    "label": "Indoor Leagues",
    "count": 1
  },
  {
    "slug": "ohio_golf",
    "label": "Ohio Golf",
    "count": 1
  },
  {
    "slug": "competitive_play",
    "label": "Competitive Play",
    "count": 1
  },
  {
    "slug": "resort",
    "label": "Resort",
    "count": 1
  },
  {
    "slug": "fitness_facility",
    "label": "Fitness Facility",
    "count": 1
  },
  {
    "slug": "urban_arena",
    "label": "Urban Arena",
    "count": 1
  },
  {
    "slug": "practice_sessions",
    "label": "Practice Sessions",
    "count": 1
  },
  {
    "slug": "no_weather_issues",
    "label": "No Weather Issues",
    "count": 1
  },
  {
    "slug": "founding_members",
    "label": "Founding Members",
    "count": 1
  },
  {
    "slug": "no_public_play",
    "label": "No Public Play",
    "count": 1
  },
  {
    "slug": "racing_simulators",
    "label": "Racing Simulators",
    "count": 1
  },
  {
    "slug": "outings_tournaments",
    "label": "Outings Tournaments",
    "count": 1
  },
  {
    "slug": "duluth_ga",
    "label": "Duluth Ga",
    "count": 1
  },
  {
    "slug": "corporate_outings",
    "label": "Corporate Outings",
    "count": 1
  },
  {
    "slug": "next_golf_tour",
    "label": "Next Golf Tour",
    "count": 1
  },
  {
    "slug": "individual_training",
    "label": "Individual Training",
    "count": 1
  },
  {
    "slug": "group_training",
    "label": "Group Training",
    "count": 1
  },
  {
    "slug": "performance_classes",
    "label": "Performance Classes",
    "count": 1
  },
  {
    "slug": "injury_prevention",
    "label": "Injury Prevention",
    "count": 1
  },
  {
    "slug": "cocktail_bar",
    "label": "Cocktail Bar",
    "count": 1
  },
  {
    "slug": "live_music",
    "label": "Live Music",
    "count": 1
  },
  {
    "slug": "uptown_dallas",
    "label": "Uptown Dallas",
    "count": 1
  },
  {
    "slug": "caribbean_food",
    "label": "Caribbean Food",
    "count": 1
  },
  {
    "slug": "event_hosting",
    "label": "Event Hosting",
    "count": 1
  },
  {
    "slug": "birrdi",
    "label": "Birrdi",
    "count": 1
  },
  {
    "slug": "automated_bays",
    "label": "Automated Bays",
    "count": 1
  },
  {
    "slug": "punch_card",
    "label": "Punch Card",
    "count": 1
  },
  {
    "slug": "contactless",
    "label": "Contactless",
    "count": 1
  },
  {
    "slug": "walk_ins_welcome",
    "label": "Walk Ins Welcome",
    "count": 1
  },
  {
    "slug": "simulation_games",
    "label": "Simulation Games",
    "count": 1
  },
  {
    "slug": "home_builders",
    "label": "Home Builders",
    "count": 1
  },
  {
    "slug": "arkansas_golf",
    "label": "Arkansas Golf",
    "count": 1
  },
  {
    "slug": "indoor_activity",
    "label": "Indoor Activity",
    "count": 1
  },
  {
    "slug": "mobile_pop_up",
    "label": "Mobile Pop Up",
    "count": 1
  },
  {
    "slug": "bar_grill",
    "label": "Bar Grill",
    "count": 1
  },
  {
    "slug": "ellsworth",
    "label": "Ellsworth",
    "count": 1
  },
  {
    "slug": "simulator bays",
    "label": "Simulator Bays",
    "count": 1
  },
  {
    "slug": "sports bar",
    "label": "Sports Bar",
    "count": 1
  },
  {
    "slug": "food and drink",
    "label": "Food And Drink",
    "count": 1
  },
  {
    "slug": "group entertainment",
    "label": "Group Entertainment",
    "count": 1
  },
  {
    "slug": "family friendly",
    "label": "Family Friendly",
    "count": 1
  },
  {
    "slug": "networking_events",
    "label": "Networking Events",
    "count": 1
  },
  {
    "slug": "full_swing_simulator",
    "label": "Full Swing Simulator",
    "count": 1
  },
  {
    "slug": "venue_rental",
    "label": "Venue Rental",
    "count": 1
  },
  {
    "slug": "kids_and_juniors",
    "label": "Kids And Juniors",
    "count": 1
  },
  {
    "slug": "byo_friendly",
    "label": "Byo Friendly",
    "count": 1
  },
  {
    "slug": "outdoor_lessons",
    "label": "Outdoor Lessons",
    "count": 1
  },
  {
    "slug": "booking_required",
    "label": "Booking Required",
    "count": 1
  },
  {
    "slug": "party_venue",
    "label": "Party Venue",
    "count": 1
  },
  {
    "slug": "event_space",
    "label": "Event Space",
    "count": 1
  },
  {
    "slug": "iowa_golf",
    "label": "Iowa Golf",
    "count": 1
  },
  {
    "slug": "mixed",
    "label": "Mixed",
    "count": 1
  },
  {
    "slug": "hunting_simulator",
    "label": "Hunting Simulator",
    "count": 1
  },
  {
    "slug": "wild_west_shooting",
    "label": "Wild West Shooting",
    "count": 1
  },
  {
    "slug": "snacks",
    "label": "Snacks",
    "count": 1
  },
  {
    "slug": "beverages",
    "label": "Beverages",
    "count": 1
  },
  {
    "slug": "foresight",
    "label": "Foresight",
    "count": 1
  },
  {
    "slug": "data",
    "label": "Data",
    "count": 1
  },
  {
    "slug": "golf_rx",
    "label": "Golf Rx",
    "count": 1
  },
  {
    "slug": "massachusetts",
    "label": "Massachusetts",
    "count": 1
  },
  {
    "slug": "weekend_entertainment",
    "label": "Weekend Entertainment",
    "count": 1
  },
  {
    "slug": "wellness",
    "label": "Wellness",
    "count": 1
  },
  {
    "slug": "lifestyle_community",
    "label": "Lifestyle Community",
    "count": 1
  },
  {
    "slug": "education",
    "label": "Education",
    "count": 1
  },
  {
    "slug": "fashion",
    "label": "Fashion",
    "count": 1
  },
  {
    "slug": "upcoming_venue",
    "label": "Upcoming Venue",
    "count": 1
  },
  {
    "slug": "flower_mound",
    "label": "Flower Mound",
    "count": 1
  },
  {
    "slug": "lessons_packages",
    "label": "Lessons Packages",
    "count": 1
  },
  {
    "slug": "golf318",
    "label": "Golf318",
    "count": 1
  },
  {
    "slug": "swing",
    "label": "Swing",
    "count": 1
  },
  {
    "slug": "local_beer",
    "label": "Local Beer",
    "count": 1
  },
  {
    "slug": "billiards",
    "label": "Billiards",
    "count": 1
  },
  {
    "slug": "simulator_bar",
    "label": "Simulator Bar",
    "count": 1
  },
  {
    "slug": "nebraska_golf",
    "label": "Nebraska Golf",
    "count": 1
  },
  {
    "slug": "golf_camps",
    "label": "Golf Camps",
    "count": 1
  },
  {
    "slug": "golf_range",
    "label": "Golf Range",
    "count": 1
  },
  {
    "slug": "cafe",
    "label": "Cafe",
    "count": 1
  },
  {
    "slug": "golf_shop",
    "label": "Golf Shop",
    "count": 1
  },
  {
    "slug": "no_alcohol",
    "label": "No Alcohol",
    "count": 1
  },
  {
    "slug": "activity_focused",
    "label": "Activity Focused",
    "count": 1
  },
  {
    "slug": "semi_autonomous",
    "label": "Semi Autonomous",
    "count": 1
  },
  {
    "slug": "adult_lessons",
    "label": "Adult Lessons",
    "count": 1
  },
  {
    "slug": "outdoor_facility",
    "label": "Outdoor Facility",
    "count": 1
  },
  {
    "slug": "parking_available",
    "label": "Parking Available",
    "count": 1
  },
  {
    "slug": "partner_facility",
    "label": "Partner Facility",
    "count": 1
  },
  {
    "slug": "limited_memberships",
    "label": "Limited Memberships",
    "count": 1
  },
  {
    "slug": "golf_improvement",
    "label": "Golf Improvement",
    "count": 1
  },
  {
    "slug": "resort_amenity",
    "label": "Resort Amenity",
    "count": 1
  },
  {
    "slug": "scenic_location",
    "label": "Scenic Location",
    "count": 1
  },
  {
    "slug": "vermont",
    "label": "Vermont",
    "count": 1
  },
  {
    "slug": "virtual_tours",
    "label": "Virtual Tours",
    "count": 1
  },
  {
    "slug": "toptracer_technology",
    "label": "Toptracer Technology",
    "count": 1
  },
  {
    "slug": "south_carolina",
    "label": "South Carolina",
    "count": 1
  },
  {
    "slug": "community_center",
    "label": "Community Center",
    "count": 1
  },
  {
    "slug": "family_activities",
    "label": "Family Activities",
    "count": 1
  },
  {
    "slug": "radar_technology",
    "label": "Radar Technology",
    "count": 1
  },
  {
    "slug": "winter_league",
    "label": "Winter League",
    "count": 1
  },
  {
    "slug": "hotel_amenity",
    "label": "Hotel Amenity",
    "count": 1
  },
  {
    "slug": "e6_connect",
    "label": "E6 Connect",
    "count": 1
  },
  {
    "slug": "nfl_sunday_ticket",
    "label": "Nfl Sunday Ticket",
    "count": 1
  },
  {
    "slug": "custom_designs",
    "label": "Custom Designs",
    "count": 1
  },
  {
    "slug": "home_setup",
    "label": "Home Setup",
    "count": 1
  },
  {
    "slug": "accessories_expert",
    "label": "Accessories Expert",
    "count": 1
  },
  {
    "slug": "resort_stay",
    "label": "Resort Stay",
    "count": 1
  },
  {
    "slug": "fitness_included",
    "label": "Fitness Included",
    "count": 1
  },
  {
    "slug": "mental_coaching",
    "label": "Mental Coaching",
    "count": 1
  },
  {
    "slug": "retail_experiential",
    "label": "Retail Experiential",
    "count": 1
  },
  {
    "slug": "retail_experience",
    "label": "Retail Experience",
    "count": 1
  },
  {
    "slug": "hot_tub",
    "label": "Hot Tub",
    "count": 1
  },
  {
    "slug": "game_room",
    "label": "Game Room",
    "count": 1
  },
  {
    "slug": "vacation_rental",
    "label": "Vacation Rental",
    "count": 1
  },
  {
    "slug": "pets_allowed",
    "label": "Pets Allowed",
    "count": 1
  },
  {
    "slug": "flex_league",
    "label": "Flex League",
    "count": 1
  },
  {
    "slug": "swing_analysis",
    "label": "Swing Analysis",
    "count": 1
  },
  {
    "slug": "training_aid",
    "label": "Training Aid",
    "count": 1
  },
  {
    "slug": "uneven_lies",
    "label": "Uneven Lies",
    "count": 1
  },
  {
    "slug": "portable",
    "label": "Portable",
    "count": 1
  },
  {
    "slug": "home_practice",
    "label": "Home Practice",
    "count": 1
  },
  {
    "slug": "commercial_golf",
    "label": "Commercial Golf",
    "count": 1
  },
  {
    "slug": "outdoor_rated",
    "label": "Outdoor Rated",
    "count": 1
  },
  {
    "slug": "mechanized_platform",
    "label": "Mechanized Platform",
    "count": 1
  },
  {
    "slug": "group_rentals",
    "label": "Group Rentals",
    "count": 1
  },
  {
    "slug": "installation",
    "label": "Installation",
    "count": 1
  },
  {
    "slug": "control_boxes",
    "label": "Control Boxes",
    "count": 1
  },
  {
    "slug": "booking_software",
    "label": "Booking Software",
    "count": 1
  },
  {
    "slug": "mobile_rental",
    "label": "Mobile Rental",
    "count": 1
  },
  {
    "slug": "golf_network",
    "label": "Golf Network",
    "count": 1
  },
  {
    "slug": "cashless_payment",
    "label": "Cashless Payment",
    "count": 1
  },
  {
    "slug": "digital_golf",
    "label": "Digital Golf",
    "count": 1
  },
  {
    "slug": "private_lounge",
    "label": "Private Lounge",
    "count": 1
  },
  {
    "slug": "bushnell_launchpro",
    "label": "Bushnell Launchpro",
    "count": 1
  },
  {
    "slug": "lexington_ky",
    "label": "Lexington Ky",
    "count": 1
  },
  {
    "slug": "bar_and_grill",
    "label": "Bar And Grill",
    "count": 1
  },
  {
    "slug": "hd golf",
    "label": "Hd Golf",
    "count": 1
  },
  {
    "slug": "sports simulator",
    "label": "Sports Simulator",
    "count": 1
  },
  {
    "slug": "arcade games",
    "label": "Arcade Games",
    "count": 1
  },
  {
    "slug": "bowling simulator",
    "label": "Bowling Simulator",
    "count": 1
  },
  {
    "slug": "family entertainment",
    "label": "Family Entertainment",
    "count": 1
  },
  {
    "slug": "thomaston ga",
    "label": "Thomaston Ga",
    "count": 1
  },
  {
    "slug": "membership available",
    "label": "Membership Available",
    "count": 1
  },
  {
    "slug": "private events",
    "label": "Private Events",
    "count": 1
  },
  {
    "slug": "gift certificates",
    "label": "Gift Certificates",
    "count": 1
  },
  {
    "slug": "top_course_ranked",
    "label": "Top Course Ranked",
    "count": 1
  },
  {
    "slug": "scenic_water_hazards",
    "label": "Scenic Water Hazards",
    "count": 1
  },
  {
    "slug": "angola_indiana",
    "label": "Angola Indiana",
    "count": 1
  },
  {
    "slug": "tech_fitting",
    "label": "Tech Fitting",
    "count": 1
  },
  {
    "slug": "sports_programs",
    "label": "Sports Programs",
    "count": 1
  },
  {
    "slug": "fittings",
    "label": "Fittings",
    "count": 1
  },
  {
    "slug": "simulation",
    "label": "Simulation",
    "count": 1
  },
  {
    "slug": "manchester",
    "label": "Manchester",
    "count": 1
  },
  {
    "slug": "structured_learning",
    "label": "Structured Learning",
    "count": 1
  },
  {
    "slug": "appointment_only",
    "label": "Appointment Only",
    "count": 1
  },
  {
    "slug": "full_bar",
    "label": "Full Bar",
    "count": 1
  },
  {
    "slug": "hd_tv",
    "label": "Hd Tv",
    "count": 1
  },
  {
    "slug": "golf_tournaments",
    "label": "Golf Tournaments",
    "count": 1
  },
  {
    "slug": "trackman simulator",
    "label": "Trackman Simulator",
    "count": 1
  },
  {
    "slug": "golf leagues",
    "label": "Golf Leagues",
    "count": 1
  },
  {
    "slug": "virtual golf",
    "label": "Virtual Golf",
    "count": 1
  },
  {
    "slug": "heath ohio",
    "label": "Heath Ohio",
    "count": 1
  },
  {
    "slug": "pataskala ohio",
    "label": "Pataskala Ohio",
    "count": 1
  },
  {
    "slug": "golf tournaments",
    "label": "Golf Tournaments",
    "count": 1
  },
  {
    "slug": "bay rental",
    "label": "Bay Rental",
    "count": 1
  },
  {
    "slug": "flightscope",
    "label": "FlightScope",
    "count": 1
  },
  {
    "slug": "private_tutoring",
    "label": "Private Tutoring",
    "count": 1
  },
  {
    "slug": "online_retailer",
    "label": "Online Retailer",
    "count": 1
  },
  {
    "slug": "financing_available",
    "label": "Financing Available",
    "count": 1
  },
  {
    "slug": "simulator_bay",
    "label": "Simulator Bay",
    "count": 1
  },
  {
    "slug": "launch_monitor",
    "label": "Launch Monitor",
    "count": 1
  },
  {
    "slug": "metro_detroit",
    "label": "Metro Detroit",
    "count": 1
  },
  {
    "slug": "Topgolf",
    "label": "Topgolf",
    "count": 1
  },
  {
    "slug": "Entertainment Venue",
    "label": "Entertainment Venue",
    "count": 1
  },
  {
    "slug": "Topgolf Game",
    "label": "Topgolf Game",
    "count": 1
  },
  {
    "slug": "Microchipped Balls",
    "label": "Microchipped Balls",
    "count": 1
  },
  {
    "slug": "Group Events",
    "label": "Group Events",
    "count": 1
  },
  {
    "slug": "Family Entertainment",
    "label": "Family Entertainment",
    "count": 1
  },
  {
    "slug": "Climate Controlled Bays",
    "label": "Climate Controlled Bays",
    "count": 1
  },
  {
    "slug": "Rooftop Terrace",
    "label": "Rooftop Terrace",
    "count": 1
  },
  {
    "slug": "Gaming",
    "label": "Gaming",
    "count": 1
  },
  {
    "slug": "entertainment_complex",
    "label": "Entertainment Complex",
    "count": 1
  },
  {
    "slug": "microchipped_balls",
    "label": "Microchipped Balls",
    "count": 1
  },
  {
    "slug": "swing_suite",
    "label": "Swing Suite",
    "count": 1
  },
  {
    "slug": "hotel_entertainment",
    "label": "Hotel Entertainment",
    "count": 1
  },
  {
    "slug": "private_bay",
    "label": "Private Bay",
    "count": 1
  },
  {
    "slug": "dallas",
    "label": "Dallas",
    "count": 1
  },
  {
    "slug": "virtual_sports",
    "label": "Virtual Sports",
    "count": 1
  },
  {
    "slug": "luxury_amenity",
    "label": "Luxury Amenity",
    "count": 1
  },
  {
    "slug": "entertainment_venue",
    "label": "Entertainment Venue",
    "count": 1
  },
  {
    "slug": "rooftop_terrace",
    "label": "Rooftop Terrace",
    "count": 1
  },
  {
    "slug": "golf_games",
    "label": "Golf Games",
    "count": 1
  },
  {
    "slug": "virtual_tour",
    "label": "Virtual Tour",
    "count": 1
  },
  {
    "slug": "recovery",
    "label": "Recovery",
    "count": 1
  },
  {
    "slug": "custom_builds",
    "label": "Custom Builds",
    "count": 1
  },
  {
    "slug": "residential_installation",
    "label": "Residential Installation",
    "count": 1
  },
  {
    "slug": "commercial_installation",
    "label": "Commercial Installation",
    "count": 1
  },
  {
    "slug": "portable_rentals",
    "label": "Portable Rentals",
    "count": 1
  },
  {
    "slug": "team_building",
    "label": "Team Building",
    "count": 1
  },
  {
    "slug": "private_members_only",
    "label": "Private Members Only",
    "count": 1
  },
  {
    "slug": "poway",
    "label": "Poway",
    "count": 1
  },
  {
    "slug": "ADA_accessible",
    "label": "ADA Accessible",
    "count": 1
  },
  {
    "slug": "pga_professionals",
    "label": "Pga Professionals",
    "count": 1
  },
  {
    "slug": "custom_fit",
    "label": "Custom Fit",
    "count": 1
  },
  {
    "slug": "resort_style",
    "label": "Resort Style",
    "count": 1
  },
  {
    "slug": "private_studio",
    "label": "Private Studio",
    "count": 1
  },
  {
    "slug": "pro_shop_discount",
    "label": "Pro Shop Discount",
    "count": 1
  },
  {
    "slug": "social_friendly",
    "label": "Social Friendly",
    "count": 1
  },
  {
    "slug": "anytime_access",
    "label": "Anytime Access",
    "count": 1
  },
  {
    "slug": "pickleball",
    "label": "Pickleball",
    "count": 1
  },
  {
    "slug": "golf simulator",
    "label": "Golf Simulator",
    "count": 1
  },
  {
    "slug": "family-friendly",
    "label": "Family Friendly",
    "count": 1
  },
  {
    "slug": "date night",
    "label": "Date Night",
    "count": 1
  },
  {
    "slug": "bachelor party",
    "label": "Bachelor Party",
    "count": 1
  },
  {
    "slug": "birthday parties",
    "label": "Birthday Parties",
    "count": 1
  },
  {
    "slug": "membership_program",
    "label": "Membership Program",
    "count": 1
  },
  {
    "slug": "custom_club_repair",
    "label": "Custom Club Repair",
    "count": 1
  },
  {
    "slug": "arcade_games",
    "label": "Arcade Games",
    "count": 1
  },
  {
    "slug": "simulator golf",
    "label": "Simulator Golf",
    "count": 1
  },
  {
    "slug": "practice range",
    "label": "Practice Range",
    "count": 1
  },
  {
    "slug": "whiskey_bar",
    "label": "Whiskey Bar",
    "count": 1
  },
  {
    "slug": "family_business",
    "label": "Family Business",
    "count": 1
  },
  {
    "slug": "toledo",
    "label": "Toledo",
    "count": 1
  },
  {
    "slug": "Indoor Golf",
    "label": "Indoor Golf",
    "count": 1
  },
  {
    "slug": "Simulators",
    "label": "Simulators",
    "count": 1
  },
  {
    "slug": "Lessons",
    "label": "Lessons",
    "count": 1
  },
  {
    "slug": "Events",
    "label": "Events",
    "count": 1
  },
  {
    "slug": "Family Owned",
    "label": "Family Owned",
    "count": 1
  },
  {
    "slug": "retail_shop",
    "label": "Retail Shop",
    "count": 1
  },
  {
    "slug": "course_improvements",
    "label": "Course Improvements",
    "count": 1
  },
  {
    "slug": "alcohol",
    "label": "Alcohol",
    "count": 1
  },
  {
    "slug": "urban_location",
    "label": "Urban Location",
    "count": 1
  },
  {
    "slug": "sports_complex",
    "label": "Sports Complex",
    "count": 1
  },
  {
    "slug": "group_classes",
    "label": "Group Classes",
    "count": 1
  },
  {
    "slug": "beer_golf",
    "label": "Beer Golf",
    "count": 1
  },
  {
    "slug": "24/7 access",
    "label": "24/7 Access",
    "count": 1
  },
  {
    "slug": "booking required",
    "label": "Booking Required",
    "count": 1
  },
  {
    "slug": "online_gaming",
    "label": "Online Gaming",
    "count": 1
  },
  {
    "slug": "slot_games",
    "label": "Slot Games",
    "count": 1
  },
  {
    "slug": "betting",
    "label": "Betting",
    "count": 1
  },
  {
    "slug": "casino",
    "label": "Casino",
    "count": 1
  },
  {
    "slug": "gacor_slots",
    "label": "Gacor Slots",
    "count": 1
  },
  {
    "slug": "indonesian_market",
    "label": "Indonesian Market",
    "count": 1
  },
  {
    "slug": "vip_program",
    "label": "Vip Program",
    "count": 1
  },
  {
    "slug": "daily_bonuses",
    "label": "Daily Bonuses",
    "count": 1
  },
  {
    "slug": "secure_platform",
    "label": "Secure Platform",
    "count": 1
  },
  {
    "slug": "24_hour_support",
    "label": "24 Hour Support",
    "count": 1
  },
  {
    "slug": "mobile_events",
    "label": "Mobile Events",
    "count": 1
  },
  {
    "slug": "brand_activations",
    "label": "Brand Activations",
    "count": 1
  },
  {
    "slug": "academics",
    "label": "Academics",
    "count": 1
  },
  {
    "slug": "practice_areas",
    "label": "Practice Areas",
    "count": 1
  },
  {
    "slug": "full_service",
    "label": "Full Service",
    "count": 1
  },
  {
    "slug": "events_rentals",
    "label": "Events Rentals",
    "count": 1
  },
  {
    "slug": "virtual_lessons",
    "label": "Virtual Lessons",
    "count": 1
  },
  {
    "slug": "guaranteed_results",
    "label": "Guaranteed Results",
    "count": 1
  },
  {
    "slug": "focused_practice",
    "label": "Focused Practice",
    "count": 1
  },
  {
    "slug": "custom_solutions",
    "label": "Custom Solutions",
    "count": 1
  },
  {
    "slug": "high_tech",
    "label": "High Tech",
    "count": 1
  },
  {
    "slug": "premium_brands",
    "label": "Premium Brands",
    "count": 1
  },
  {
    "slug": "practice_tune-up",
    "label": "Practice Tune Up",
    "count": 1
  },
  {
    "slug": "home_installation",
    "label": "Home Installation",
    "count": 1
  },
  {
    "slug": "casual_dining",
    "label": "Casual Dining",
    "count": 1
  },
  {
    "slug": "social_spot",
    "label": "Social Spot",
    "count": 1
  },
  {
    "slug": "happy_hour",
    "label": "Happy Hour",
    "count": 1
  },
  {
    "slug": "golf simulators",
    "label": "Golf Simulators",
    "count": 1
  },
  {
    "slug": "junior_programs",
    "label": "Junior Programs",
    "count": 1
  },
  {
    "slug": "simulator_available",
    "label": "Simulator Available",
    "count": 1
  },
  {
    "slug": "on_course_training",
    "label": "On Course Training",
    "count": 1
  },
  {
    "slug": "golf_academy",
    "label": "Golf Academy",
    "count": 1
  },
  {
    "slug": "indoor_bays",
    "label": "Indoor Bays",
    "count": 1
  },
  {
    "slug": "lake_forest",
    "label": "Lake Forest",
    "count": 1
  },
  {
    "slug": "air_conditioned",
    "label": "Air Conditioned",
    "count": 1
  },
  {
    "slug": "quiet_studio",
    "label": "Quiet Studio",
    "count": 1
  },
  {
    "slug": "social_gathering",
    "label": "Social Gathering",
    "count": 1
  },
  {
    "slug": "social_events",
    "label": "Social Events",
    "count": 1
  },
  {
    "slug": "byob_friendly",
    "label": "Byob Friendly",
    "count": 1
  },
  {
    "slug": "skill_building",
    "label": "Skill Building",
    "count": 1
  },
  {
    "slug": "rain_or_shine",
    "label": "Rain Or Shine",
    "count": 1
  },
  {
    "slug": "social_leagues",
    "label": "Social Leagues",
    "count": 1
  },
  {
    "slug": "parties_and_events",
    "label": "Parties And Events",
    "count": 1
  },
  {
    "slug": "no_membership",
    "label": "No Membership",
    "count": 1
  },
  {
    "slug": "equipment_retail",
    "label": "Equipment Retail",
    "count": 1
  },
  {
    "slug": "online_shopping",
    "label": "Online Shopping",
    "count": 1
  },
  {
    "slug": "discounted_lessons",
    "label": "Discounted Lessons",
    "count": 1
  },
  {
    "slug": "group_learning",
    "label": "Group Learning",
    "count": 1
  },
  {
    "slug": "equipment_upgrades",
    "label": "Equipment Upgrades",
    "count": 1
  }
];

// Vibes with venues (132 categories)
export const AVAILABLE_VIBES: CategoryItem[] = [
  {
    "slug": "modern",
    "label": "Modern",
    "count": 2329
  },
  {
    "slug": "community_club",
    "label": "Community Club",
    "count": 2078
  },
  {
    "slug": "welcoming",
    "label": "Welcoming",
    "count": 2044
  },
  {
    "slug": "tech_lab",
    "label": "Tech Lab",
    "count": 1713
  },
  {
    "slug": "casual",
    "label": "Casual",
    "count": 1609
  },
  {
    "slug": "sports_bar",
    "label": "Sports Bar",
    "count": 1378
  },
  {
    "slug": "family_fun_center",
    "label": "Family Fun Center",
    "count": 1118
  },
  {
    "slug": "industrial_training",
    "label": "Industrial Training",
    "count": 636
  },
  {
    "slug": "private_luxury",
    "label": "Private Luxury",
    "count": 509
  },
  {
    "slug": "upscale_lounge",
    "label": "Upscale Lounge",
    "count": 425
  },
  {
    "slug": "party_atmosphere",
    "label": "Party Atmosphere",
    "count": 386
  },
  {
    "slug": "professional",
    "label": "Professional",
    "count": 95
  },
  {
    "slug": "social",
    "label": "Social",
    "count": 30
  },
  {
    "slug": "focused",
    "label": "Focused",
    "count": 24
  },
  {
    "slug": "professional_training",
    "label": "Professional Training",
    "count": 18
  },
  {
    "slug": "retro_gaming",
    "label": "Retro Gaming",
    "count": 16
  },
  {
    "slug": "family_friendly",
    "label": "Family Friendly",
    "count": 11
  },
  {
    "slug": "speakeasy",
    "label": "Speakeasy",
    "count": 9
  },
  {
    "slug": "entertainment",
    "label": "Entertainment",
    "count": 7
  },
  {
    "slug": "private",
    "label": "Private",
    "count": 6
  },
  {
    "slug": "instructional",
    "label": "Instructional",
    "count": 6
  },
  {
    "slug": "exclusive",
    "label": "Exclusive",
    "count": 5
  },
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 5
  },
  {
    "slug": "traditional",
    "label": "Traditional",
    "count": 4
  },
  {
    "slug": "community",
    "label": "Community",
    "count": 4
  },
  {
    "slug": "entertainment_complex",
    "label": "Entertainment Complex",
    "count": 4
  },
  {
    "slug": "tech_focused",
    "label": "Tech Focused",
    "count": 3
  },
  {
    "slug": "technical",
    "label": "Technical",
    "count": 3
  },
  {
    "slug": "premium_tech",
    "label": "Premium Tech",
    "count": 3
  },
  {
    "slug": "scenic",
    "label": "Scenic",
    "count": 3
  },
  {
    "slug": "upscale",
    "label": "Upscale",
    "count": 3
  },
  {
    "slug": "high-tech",
    "label": "High Tech",
    "count": 3
  },
  {
    "slug": "social_lounge",
    "label": "Social Lounge",
    "count": 3
  },
  {
    "slug": "community_focused",
    "label": "Community Focused",
    "count": 3
  },
  {
    "slug": "country_club",
    "label": "Country Club",
    "count": 3
  },
  {
    "slug": "relaxed",
    "label": "Relaxed",
    "count": 3
  },
  {
    "slug": "retail_space",
    "label": "Retail Space",
    "count": 3
  },
  {
    "slug": "practical",
    "label": "Practical",
    "count": 2
  },
  {
    "slug": "quiet",
    "label": "Quiet",
    "count": 2
  },
  {
    "slug": "professional_atmosphere",
    "label": "Professional Atmosphere",
    "count": 2
  },
  {
    "slug": "entertainment_focused",
    "label": "Entertainment Focused",
    "count": 2
  },
  {
    "slug": "training_oriented",
    "label": "Training Oriented",
    "count": 2
  },
  {
    "slug": "focused_training",
    "label": "Focused Training",
    "count": 2
  },
  {
    "slug": "Casual",
    "label": "Casual",
    "count": 2
  },
  {
    "slug": "Social",
    "label": "Social",
    "count": 2
  },
  {
    "slug": "energetic",
    "label": "Energetic",
    "count": 2
  },
  {
    "slug": "retail",
    "label": "Retail",
    "count": 2
  },
  {
    "slug": "training_studio",
    "label": "Training Studio",
    "count": 2
  },
  {
    "slug": "flexible",
    "label": "Flexible",
    "count": 2
  },
  {
    "slug": "fun",
    "label": "Fun",
    "count": 2
  },
  {
    "slug": "training_focused",
    "label": "Training Focused",
    "count": 1
  },
  {
    "slug": "industrial_modern",
    "label": "Industrial Modern",
    "count": 1
  },
  {
    "slug": "performance",
    "label": "Performance",
    "count": 1
  },
  {
    "slug": "athletic",
    "label": "Athletic",
    "count": 1
  },
  {
    "slug": "focused_learning",
    "label": "Focused Learning",
    "count": 1
  },
  {
    "slug": "professional_studio",
    "label": "Professional Studio",
    "count": 1
  },
  {
    "slug": "functional",
    "label": "Functional",
    "count": 1
  },
  {
    "slug": "serious_athletic",
    "label": "Serious Athletic",
    "count": 1
  },
  {
    "slug": "motivating_community",
    "label": "Motivating Community",
    "count": 1
  },
  {
    "slug": "comfortable",
    "label": "Comfortable",
    "count": 1
  },
  {
    "slug": "modern_facility",
    "label": "Modern Facility",
    "count": 1
  },
  {
    "slug": "focus_on_learning",
    "label": "Focus On Learning",
    "count": 1
  },
  {
    "slug": "club_house",
    "label": "Club House",
    "count": 1
  },
  {
    "slug": "focus",
    "label": "Focus",
    "count": 1
  },
  {
    "slug": "intensive",
    "label": "Intensive",
    "count": 1
  },
  {
    "slug": "social_sports_bar",
    "label": "Social Sports Bar",
    "count": 1
  },
  {
    "slug": "indoor_comfort",
    "label": "Indoor Comfort",
    "count": 1
  },
  {
    "slug": "competitive",
    "label": "Competitive",
    "count": 1
  },
  {
    "slug": "focused_practice",
    "label": "Focused Practice",
    "count": 1
  },
  {
    "slug": "community_oriented",
    "label": "Community Oriented",
    "count": 1
  },
  {
    "slug": "focused_fun",
    "label": "Focused Fun",
    "count": 1
  },
  {
    "slug": "urban_clubhouse",
    "label": "Urban Clubhouse",
    "count": 1
  },
  {
    "slug": "elevated",
    "label": "Elevated",
    "count": 1
  },
  {
    "slug": "inclusive",
    "label": "Inclusive",
    "count": 1
  },
  {
    "slug": "data_driven",
    "label": "Data Driven",
    "count": 1
  },
  {
    "slug": "Lively",
    "label": "Lively",
    "count": 1
  },
  {
    "slug": "Family-Friendly",
    "label": "Family Friendly",
    "count": 1
  },
  {
    "slug": "club_atmosphere",
    "label": "Club Atmosphere",
    "count": 1
  },
  {
    "slug": "high-energy",
    "label": "High Energy",
    "count": 1
  },
  {
    "slug": "tech-forward",
    "label": "Tech Forward",
    "count": 1
  },
  {
    "slug": "mobile_luxury",
    "label": "Mobile Luxury",
    "count": 1
  },
  {
    "slug": "customizable",
    "label": "Customizable",
    "count": 1
  },
  {
    "slug": "lounge",
    "label": "Lounge",
    "count": 1
  },
  {
    "slug": "upscale_resort",
    "label": "Upscale Resort",
    "count": 1
  },
  {
    "slug": "relaxed_luxury",
    "label": "Relaxed Luxury",
    "count": 1
  },
  {
    "slug": "destination_golf",
    "label": "Destination Golf",
    "count": 1
  },
  {
    "slug": "technical_modern",
    "label": "Technical Modern",
    "count": 1
  },
  {
    "slug": "community_hub",
    "label": "Community Hub",
    "count": 1
  },
  {
    "slug": "historic",
    "label": "Historic",
    "count": 1
  },
  {
    "slug": "outdoorsy",
    "label": "Outdoorsy",
    "count": 1
  },
  {
    "slug": "retail_atmosphere",
    "label": "Retail Atmosphere",
    "count": 1
  },
  {
    "slug": "sports_focused",
    "label": "Sports Focused",
    "count": 1
  },
  {
    "slug": "family-oriented",
    "label": "Family Oriented",
    "count": 1
  },
  {
    "slug": "indoor_outdoor_combo",
    "label": "Indoor Outdoor Combo",
    "count": 1
  },
  {
    "slug": "resort_lifestyle",
    "label": "Resort Lifestyle",
    "count": 1
  },
  {
    "slug": "serious",
    "label": "Serious",
    "count": 1
  },
  {
    "slug": "tech-focused",
    "label": "Tech Focused",
    "count": 1
  },
  {
    "slug": "resort_style",
    "label": "Resort Style",
    "count": 1
  },
  {
    "slug": "scenic_relaxed",
    "label": "Scenic Relaxed",
    "count": 1
  },
  {
    "slug": "family_oriented",
    "label": "Family Oriented",
    "count": 1
  },
  {
    "slug": "classic_vermont",
    "label": "Classic Vermont",
    "count": 1
  },
  {
    "slug": "entertainment_center",
    "label": "Entertainment Center",
    "count": 1
  },
  {
    "slug": "local_hangout",
    "label": "Local Hangout",
    "count": 1
  },
  {
    "slug": "individual_attention",
    "label": "Individual Attention",
    "count": 1
  },
  {
    "slug": "analytical",
    "label": "Analytical",
    "count": 1
  },
  {
    "slug": "structured",
    "label": "Structured",
    "count": 1
  },
  {
    "slug": "clean_modern",
    "label": "Clean Modern",
    "count": 1
  },
  {
    "slug": "family_friendly_center",
    "label": "Family Friendly Center",
    "count": 1
  },
  {
    "slug": "lounge_atmosphere",
    "label": "Lounge Atmosphere",
    "count": 1
  },
  {
    "slug": "spacious",
    "label": "Spacious",
    "count": 1
  },
  {
    "slug": "entertainment-focused",
    "label": "Entertainment Focused",
    "count": 1
  },
  {
    "slug": "dog_friendly",
    "label": "Dog Friendly",
    "count": 1
  },
  {
    "slug": "sports bar",
    "label": "Sports Bar",
    "count": 1
  },
  {
    "slug": "winter activity",
    "label": "Winter Activity",
    "count": 1
  },
  {
    "slug": "retro",
    "label": "Retro",
    "count": 1
  },
  {
    "slug": "modern_tech",
    "label": "Modern Tech",
    "count": 1
  },
  {
    "slug": "Modern",
    "label": "Modern",
    "count": 1
  },
  {
    "slug": "technology focused",
    "label": "Technology Focused",
    "count": 1
  },
  {
    "slug": "digital_entertainment",
    "label": "Digital Entertainment",
    "count": 1
  },
  {
    "slug": "gaming_platform",
    "label": "Gaming Platform",
    "count": 1
  },
  {
    "slug": "promotional",
    "label": "Promotional",
    "count": 1
  },
  {
    "slug": "online_service",
    "label": "Online Service",
    "count": 1
  },
  {
    "slug": "resort_atmosphere",
    "label": "Resort Atmosphere",
    "count": 1
  },
  {
    "slug": "social_lively",
    "label": "Social Lively",
    "count": 1
  },
  {
    "slug": "lively",
    "label": "Lively",
    "count": 1
  },
  {
    "slug": "autonomous",
    "label": "Autonomous",
    "count": 1
  },
  {
    "slug": "climate_controlled",
    "label": "Climate Controlled",
    "count": 1
  },
  {
    "slug": "intimate",
    "label": "Intimate",
    "count": 1
  },
  {
    "slug": "social_club",
    "label": "Social Club",
    "count": 1
  },
  {
    "slug": "retail_fitting_center",
    "label": "Retail Fitting Center",
    "count": 1
  },
  {
    "slug": "professional_service",
    "label": "Professional Service",
    "count": 1
  },
  {
    "slug": "retail_environment",
    "label": "Retail Environment",
    "count": 1
  }
];

// Segments with venues (111 categories)
export const AVAILABLE_SEGMENTS: CategoryItem[] = [
  {
    "slug": "beginners",
    "label": "Beginners",
    "count": 3331
  },
  {
    "slug": "families",
    "label": "Families",
    "count": 3177
  },
  {
    "slug": "corporate_teams",
    "label": "Corporate Teams",
    "count": 2941
  },
  {
    "slug": "serious_golfers",
    "label": "Serious Golfers",
    "count": 2939
  },
  {
    "slug": "solo_practice",
    "label": "Solo Practice",
    "count": 2472
  },
  {
    "slug": "juniors_youth",
    "label": "Juniors Youth",
    "count": 1236
  },
  {
    "slug": "large_groups",
    "label": "Large Groups",
    "count": 1163
  },
  {
    "slug": "coaches_instructors",
    "label": "Coaches Instructors",
    "count": 804
  },
  {
    "slug": "tourists_travelers",
    "label": "Tourists Travelers",
    "count": 463
  },
  {
    "slug": "low_handicap",
    "label": "Low Handicap",
    "count": 191
  },
  {
    "slug": "bachelor_parties",
    "label": "Bachelor Parties",
    "count": 85
  },
  {
    "slug": "casual_golfers",
    "label": "Casual Golfers",
    "count": 45
  },
  {
    "slug": "groups",
    "label": "Groups",
    "count": 34
  },
  {
    "slug": "beginner_friendly",
    "label": "Beginner Friendly",
    "count": 14
  },
  {
    "slug": "adults_only",
    "label": "Adults Only",
    "count": 9
  },
  {
    "slug": "date_night",
    "label": "Date Night",
    "count": 9
  },
  {
    "slug": "kids",
    "label": "Kids",
    "count": 8
  },
  {
    "slug": "golf_enthusiasts",
    "label": "Golf Enthusiasts",
    "count": 7
  },
  {
    "slug": "social_golfers",
    "label": "Social Golfers",
    "count": 7
  },
  {
    "slug": "leagues",
    "label": "Leagues",
    "count": 6
  },
  {
    "slug": "social_groups",
    "label": "Social Groups",
    "count": 5
  },
  {
    "slug": "league_players",
    "label": "League Players",
    "count": 5
  },
  {
    "slug": "homeowners",
    "label": "Homeowners",
    "count": 4
  },
  {
    "slug": "corporate_groups",
    "label": "Corporate Groups",
    "count": 4
  },
  {
    "slug": "sports_fans",
    "label": "Sports Fans",
    "count": 4
  },
  {
    "slug": "league_golfers",
    "label": "League Golfers",
    "count": 4
  },
  {
    "slug": "local_residents",
    "label": "Local Residents",
    "count": 3
  },
  {
    "slug": "kids_youth",
    "label": "Kids Youth",
    "count": 3
  },
  {
    "slug": "juniors",
    "label": "Juniors",
    "count": 3
  },
  {
    "slug": "beginner_golfers",
    "label": "Beginner Golfers",
    "count": 3
  },
  {
    "slug": "golfers",
    "label": "Golfers",
    "count": 3
  },
  {
    "slug": "casual_players",
    "label": "Casual Players",
    "count": 2
  },
  {
    "slug": "event_planners",
    "label": "Event Planners",
    "count": 2
  },
  {
    "slug": "group_friendly",
    "label": "Group Friendly",
    "count": 2
  },
  {
    "slug": "small_groups",
    "label": "Small Groups",
    "count": 2
  },
  {
    "slug": "adults",
    "label": "Adults",
    "count": 2
  },
  {
    "slug": "friends",
    "label": "Friends",
    "count": 2
  },
  {
    "slug": "business_professionals",
    "label": "Business Professionals",
    "count": 2
  },
  {
    "slug": "Families",
    "label": "Families",
    "count": 2
  },
  {
    "slug": "everyone",
    "label": "Everyone",
    "count": 2
  },
  {
    "slug": "students",
    "label": "Students",
    "count": 2
  },
  {
    "slug": "members",
    "label": "Members",
    "count": 2
  },
  {
    "slug": "casual_diners",
    "label": "Casual Diners",
    "count": 2
  },
  {
    "slug": "business_travelers",
    "label": "Business Travelers",
    "count": 2
  },
  {
    "slug": "league players",
    "label": "League Players",
    "count": 2
  },
  {
    "slug": "golf enthusiasts",
    "label": "Golf Enthusiasts",
    "count": 2
  },
  {
    "slug": "casual golfers",
    "label": "Casual Golfers",
    "count": 2
  },
  {
    "slug": "group_bookings",
    "label": "Group Bookings",
    "count": 1
  },
  {
    "slug": "practice_seekers",
    "label": "Practice Seekers",
    "count": 1
  },
  {
    "slug": "teams",
    "label": "Teams",
    "count": 1
  },
  {
    "slug": "groups_of_friends",
    "label": "Groups Of Friends",
    "count": 1
  },
  {
    "slug": "businesses",
    "label": "Businesses",
    "count": 1
  },
  {
    "slug": "golf_teams",
    "label": "Golf Teams",
    "count": 1
  },
  {
    "slug": "commercial_clients",
    "label": "Commercial Clients",
    "count": 1
  },
  {
    "slug": "recreational_golfers",
    "label": "Recreational Golfers",
    "count": 1
  },
  {
    "slug": "tech_savvy",
    "label": "Tech Savvy",
    "count": 1
  },
  {
    "slug": "technology_enthusiasts",
    "label": "Technology Enthusiasts",
    "count": 1
  },
  {
    "slug": "busy_professionals",
    "label": "Busy Professionals",
    "count": 1
  },
  {
    "slug": "tech_savvy_players",
    "label": "Tech Savvy Players",
    "count": 1
  },
  {
    "slug": "golfers_looking_to_improve",
    "label": "Golfers Looking To Improve",
    "count": 1
  },
  {
    "slug": "competitive_golfers",
    "label": "Competitive Golfers",
    "count": 1
  },
  {
    "slug": "club_fitting_clients",
    "label": "Club Fitting Clients",
    "count": 1
  },
  {
    "slug": "Golfers",
    "label": "Golfers",
    "count": 1
  },
  {
    "slug": "Casual Players",
    "label": "Casual Players",
    "count": 1
  },
  {
    "slug": "Groups",
    "label": "Groups",
    "count": 1
  },
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 1
  },
  {
    "slug": "casual_gamers",
    "label": "Casual Gamers",
    "count": 1
  },
  {
    "slug": "founding_members",
    "label": "Founding Members",
    "count": 1
  },
  {
    "slug": "racing_enthusiasts",
    "label": "Racing Enthusiasts",
    "count": 1
  },
  {
    "slug": "corporate_events",
    "label": "Corporate Events",
    "count": 1
  },
  {
    "slug": "nightlife_crowd",
    "label": "Nightlife Crowd",
    "count": 1
  },
  {
    "slug": "foodies",
    "label": "Foodies",
    "count": 1
  },
  {
    "slug": "home_builders",
    "label": "Home Builders",
    "count": 1
  },
  {
    "slug": "adult_programs",
    "label": "Adult Programs",
    "count": 1
  },
  {
    "slug": "solo_players",
    "label": "Solo Players",
    "count": 1
  },
  {
    "slug": "hunters",
    "label": "Hunters",
    "count": 1
  },
  {
    "slug": "weekend_warriors",
    "label": "Weekend Warriors",
    "count": 1
  },
  {
    "slug": "non_golfers",
    "label": "Non Golfers",
    "count": 1
  },
  {
    "slug": "resort_guests",
    "label": "Resort Guests",
    "count": 1
  },
  {
    "slug": "vacationers",
    "label": "Vacationers",
    "count": 1
  },
  {
    "slug": "hotel_guests",
    "label": "Hotel Guests",
    "count": 1
  },
  {
    "slug": "novice_golfers",
    "label": "Novice Golfers",
    "count": 1
  },
  {
    "slug": "amateur_golfers",
    "label": "Amateur Golfers",
    "count": 1
  },
  {
    "slug": "professional_golfers",
    "label": "Professional Golfers",
    "count": 1
  },
  {
    "slug": "country_clubs",
    "label": "Country Clubs",
    "count": 1
  },
  {
    "slug": "universities",
    "label": "Universities",
    "count": 1
  },
  {
    "slug": "tech_enthusiasts",
    "label": "Tech Enthusiasts",
    "count": 1
  },
  {
    "slug": "club_members",
    "label": "Club Members",
    "count": 1
  },
  {
    "slug": "nightlife",
    "label": "Nightlife",
    "count": 1
  },
  {
    "slug": "parties",
    "label": "Parties",
    "count": 1
  },
  {
    "slug": "luxury_seekers",
    "label": "Luxury Seekers",
    "count": 1
  },
  {
    "slug": "party_seekers",
    "label": "Party Seekers",
    "count": 1
  },
  {
    "slug": "commercial_businesses",
    "label": "Commercial Businesses",
    "count": 1
  },
  {
    "slug": "All skill levels; families; groups; corporate meetings; casual golfers.",
    "label": "All Skill Levels; Families; Groups; Corporate Meetings; Casual Golfers.",
    "count": 1
  },
  {
    "slug": "casual players",
    "label": "Casual Players",
    "count": 1
  },
  {
    "slug": "Golfers of all skill levels",
    "label": "Golfers Of All Skill Levels",
    "count": 1
  },
  {
    "slug": "Casual golfers",
    "label": "Casual Golfers",
    "count": 1
  },
  {
    "slug": "competitors",
    "label": "Competitors",
    "count": 1
  },
  {
    "slug": "online_gamers",
    "label": "Online Gamers",
    "count": 1
  },
  {
    "slug": "slot_enthusiasts",
    "label": "Slot Enthusiasts",
    "count": 1
  },
  {
    "slug": "indonesian_players",
    "label": "Indonesian Players",
    "count": 1
  },
  {
    "slug": "vip_members",
    "label": "Vip Members",
    "count": 1
  },
  {
    "slug": "casino_fans",
    "label": "Casino Fans",
    "count": 1
  },
  {
    "slug": "kids_friendly",
    "label": "Kids Friendly",
    "count": 1
  },
  {
    "slug": "budget_minded_golfers",
    "label": "Budget Minded Golfers",
    "count": 1
  },
  {
    "slug": "club_shoppers",
    "label": "Club Shoppers",
    "count": 1
  },
  {
    "slug": "home_owners",
    "label": "Home Owners",
    "count": 1
  },
  {
    "slug": "custom_builders",
    "label": "Custom Builders",
    "count": 1
  },
  {
    "slug": "performance_seekers",
    "label": "Performance Seekers",
    "count": 1
  },
  {
    "slug": "locals",
    "label": "Locals",
    "count": 1
  },
  {
    "slug": "social_seekers",
    "label": "Social Seekers",
    "count": 1
  }
];

// Hardware with venues (156 categories)
export const AVAILABLE_HARDWARE: CategoryItem[] = [
  {
    "slug": "trackman",
    "label": "TrackMan",
    "count": 1183
  },
  {
    "slug": "foresight",
    "label": "Foresight",
    "count": 271
  },
  {
    "slug": "uneekor",
    "label": "Uneekor",
    "count": 203
  },
  {
    "slug": "full-swing",
    "label": "Full Swing",
    "count": 177
  },
  {
    "slug": "skytrak",
    "label": "SkyTrak",
    "count": 113
  },
  {
    "slug": "golfzon",
    "label": "Golfzon",
    "count": 106
  },
  {
    "slug": "toptracer",
    "label": "Toptracer",
    "count": 92
  },
  {
    "slug": "x-golf",
    "label": "X-Golf",
    "count": 68
  },
  {
    "slug": "aboutgolf",
    "label": "AboutGolf",
    "count": 67
  },
  {
    "slug": "trugolf",
    "label": "TruGolf",
    "count": 60
  },
  {
    "slug": "flightscope",
    "label": "FlightScope",
    "count": 59
  },
  {
    "slug": "hd-golf",
    "label": "HD Golf",
    "count": 39
  },
  {
    "slug": "protee",
    "label": "ProTee",
    "count": 35
  },
  {
    "slug": "swing-catalyst",
    "label": "Swing Catalyst",
    "count": 15
  },
  {
    "slug": "topgolf",
    "label": "Topgolf",
    "count": 15
  },
  {
    "slug": "gc-quad",
    "label": "GC Quad",
    "count": 14
  },
  {
    "slug": "puttview",
    "label": "Puttview",
    "count": 14
  },
  {
    "slug": "garmin",
    "label": "Garmin",
    "count": 14
  },
  {
    "slug": "bushnell",
    "label": "Bushnell",
    "count": 13
  },
  {
    "slug": "gspro",
    "label": "GSPro",
    "count": 13
  },
  {
    "slug": "gc-hawk",
    "label": "Gc Hawk",
    "count": 8
  },
  {
    "slug": "sam",
    "label": "Sam",
    "count": 7
  },
  {
    "slug": "other",
    "label": "Other",
    "count": 7
  },
  {
    "slug": "apogee",
    "label": "Apogee",
    "count": 7
  },
  {
    "slug": "sam-puttlab",
    "label": "Sam Puttlab",
    "count": 5
  },
  {
    "slug": "rapsodo",
    "label": "Rapsodo",
    "count": 5
  },
  {
    "slug": "capto",
    "label": "Capto",
    "count": 4
  },
  {
    "slug": "optishot",
    "label": "OptiShot",
    "count": 4
  },
  {
    "slug": "gchawk",
    "label": "Gchawk",
    "count": 4
  },
  {
    "slug": "launch-monitor",
    "label": "Launch Monitor",
    "count": 4
  },
  {
    "slug": "pga-tour",
    "label": "Pga Tour",
    "count": 4
  },
  {
    "slug": "premium",
    "label": "Premium",
    "count": 4
  },
  {
    "slug": "smart2move",
    "label": "Smart2move",
    "count": 4
  },
  {
    "slug": "boditrak",
    "label": "Boditrak",
    "count": 3
  },
  {
    "slug": "sportsbox",
    "label": "Sportsbox",
    "count": 3
  },
  {
    "slug": "full-swing-golf",
    "label": "Full Swing Golf",
    "count": 3
  },
  {
    "slug": "golftec",
    "label": "Golftec",
    "count": 3
  },
  {
    "slug": "ag",
    "label": "Ag",
    "count": 3
  },
  {
    "slug": "unknown-premium",
    "label": "Unknown Premium",
    "count": 3
  },
  {
    "slug": "xgolf",
    "label": "Xgolf",
    "count": 3
  },
  {
    "slug": "golfvx",
    "label": "Golfvx",
    "count": 3
  },
  {
    "slug": "gears",
    "label": "Gears",
    "count": 3
  },
  {
    "slug": "kgolf",
    "label": "Kgolf",
    "count": 3
  },
  {
    "slug": "hackmotion",
    "label": "Hackmotion",
    "count": 3
  },
  {
    "slug": "gdr",
    "label": "Gdr",
    "count": 3
  },
  {
    "slug": "square",
    "label": "Square",
    "count": 3
  },
  {
    "slug": "inrange",
    "label": "Inrange",
    "count": 3
  },
  {
    "slug": "benq",
    "label": "Benq",
    "count": 3
  },
  {
    "slug": "k-vest",
    "label": "K Vest",
    "count": 3
  },
  {
    "slug": "quintic",
    "label": "Quintic",
    "count": 2
  },
  {
    "slug": "high-end",
    "label": "High End",
    "count": 2
  },
  {
    "slug": "t2",
    "label": "T2",
    "count": 2
  },
  {
    "slug": "eyexo",
    "label": "Eyexo",
    "count": 2
  },
  {
    "slug": "pga-tour-simulator",
    "label": "Pga Tour Simulator",
    "count": 2
  },
  {
    "slug": "carl-s-place",
    "label": "Carl S Place",
    "count": 2
  },
  {
    "slug": "idra",
    "label": "Idra",
    "count": 2
  },
  {
    "slug": "golf-vx",
    "label": "Golf Vx",
    "count": 2
  },
  {
    "slug": "motion2coach",
    "label": "Motion2coach",
    "count": 2
  },
  {
    "slug": "jc-video",
    "label": "Jc Video",
    "count": 2
  },
  {
    "slug": "square-golf",
    "label": "Square Golf",
    "count": 2
  },
  {
    "slug": "simulator",
    "label": "Simulator",
    "count": 2
  },
  {
    "slug": "high-definition-golf",
    "label": "High Definition Golf",
    "count": 2
  },
  {
    "slug": "indoor-links",
    "label": "Indoor Links",
    "count": 1
  },
  {
    "slug": "gimme",
    "label": "Gimme",
    "count": 1
  },
  {
    "slug": "visual-sports",
    "label": "Visual Sports",
    "count": 1
  },
  {
    "slug": "sams",
    "label": "Sams",
    "count": 1
  },
  {
    "slug": "h-kan-dahlby",
    "label": "H Kan Dahlby",
    "count": 1
  },
  {
    "slug": "flighscope",
    "label": "Flighscope",
    "count": 1
  },
  {
    "slug": "pro-tee",
    "label": "Pro Tee",
    "count": 1
  },
  {
    "slug": "full-swing-simulator",
    "label": "Full Swing Simulator",
    "count": 1
  },
  {
    "slug": "proteevx",
    "label": "Proteevx",
    "count": 1
  },
  {
    "slug": "swingcatalyst",
    "label": "Swingcatalyst",
    "count": 1
  },
  {
    "slug": "courses71",
    "label": "Courses71",
    "count": 1
  },
  {
    "slug": "udr",
    "label": "Udr",
    "count": 1
  },
  {
    "slug": "divot-action",
    "label": "Divot Action",
    "count": 1
  },
  {
    "slug": "red-stakes-golf",
    "label": "Red Stakes Golf",
    "count": 1
  },
  {
    "slug": "whing-golf",
    "label": "Whing Golf",
    "count": 1
  },
  {
    "slug": "gears-golf",
    "label": "Gears Golf",
    "count": 1
  },
  {
    "slug": "eye-xo2",
    "label": "Eye Xo2",
    "count": 1
  },
  {
    "slug": "bogolf",
    "label": "Bogolf",
    "count": 1
  },
  {
    "slug": "sms-screen-golf",
    "label": "Sms Screen Golf",
    "count": 1
  },
  {
    "slug": "gc",
    "label": "Gc",
    "count": 1
  },
  {
    "slug": "custom",
    "label": "Custom",
    "count": 1
  },
  {
    "slug": "full-swing-simulators",
    "label": "Full Swing Simulators",
    "count": 1
  },
  {
    "slug": "innovative-motion",
    "label": "Innovative Motion",
    "count": 1
  },
  {
    "slug": "golfjoy",
    "label": "Golfjoy",
    "count": 1
  },
  {
    "slug": "two-vision",
    "label": "Two Vision",
    "count": 1
  },
  {
    "slug": "hdgolf",
    "label": "Hdgolf",
    "count": 1
  },
  {
    "slug": "eyexyo",
    "label": "Eyexyo",
    "count": 1
  },
  {
    "slug": "eagle-club-systems",
    "label": "Eagle Club Systems",
    "count": 1
  },
  {
    "slug": "air-break",
    "label": "Air Break",
    "count": 1
  },
  {
    "slug": "putt-aim",
    "label": "Putt Aim",
    "count": 1
  },
  {
    "slug": "hybridz",
    "label": "Hybridz",
    "count": 1
  },
  {
    "slug": "x-golf-simulator",
    "label": "X Golf Simulator",
    "count": 1
  },
  {
    "slug": "e6-golf",
    "label": "E6 Golf",
    "count": 1
  },
  {
    "slug": "truegolf",
    "label": "Truegolf",
    "count": 1
  },
  {
    "slug": "e6",
    "label": "E6 Connect",
    "count": 1
  },
  {
    "slug": "chronic-golf",
    "label": "Chronic Golf",
    "count": 1
  },
  {
    "slug": "deadsolid",
    "label": "Deadsolid",
    "count": 1
  },
  {
    "slug": "gsppro",
    "label": "Gsppro",
    "count": 1
  },
  {
    "slug": "planeswing",
    "label": "Planeswing",
    "count": 1
  },
  {
    "slug": "eye-xo",
    "label": "Eye Xo",
    "count": 1
  },
  {
    "slug": "e6-connect",
    "label": "E6 Connect",
    "count": 1
  },
  {
    "slug": "ernest-sports",
    "label": "Ernest Sports",
    "count": 1
  },
  {
    "slug": "optoma",
    "label": "Optoma",
    "count": 1
  },
  {
    "slug": "bigshots",
    "label": "Bigshots",
    "count": 1
  },
  {
    "slug": "falcon",
    "label": "Falcon",
    "count": 1
  },
  {
    "slug": "ag-simulators",
    "label": "Ag Simulators",
    "count": 1
  },
  {
    "slug": "cedar-mountain-software",
    "label": "Cedar Mountain Software",
    "count": 1
  },
  {
    "slug": "gts",
    "label": "Gts",
    "count": 1
  },
  {
    "slug": "oak-and-grist",
    "label": "Oak And Grist",
    "count": 1
  },
  {
    "slug": "champions",
    "label": "Champions",
    "count": 1
  },
  {
    "slug": "top-golf",
    "label": "Top Golf",
    "count": 1
  },
  {
    "slug": "power-golf",
    "label": "Power Golf",
    "count": 1
  },
  {
    "slug": "puttshack",
    "label": "Puttshack",
    "count": 1
  },
  {
    "slug": "robogolfpro",
    "label": "Robogolfpro",
    "count": 1
  },
  {
    "slug": "roxor",
    "label": "Roxor",
    "count": 1
  },
  {
    "slug": "bravo-golf",
    "label": "Bravo Golf",
    "count": 1
  },
  {
    "slug": "swinglogic",
    "label": "Swinglogic",
    "count": 1
  },
  {
    "slug": "hd-sportsuite",
    "label": "Hd Sportsuite",
    "count": 1
  },
  {
    "slug": "sam-putt-lab",
    "label": "Sam Putt Lab",
    "count": 1
  },
  {
    "slug": "fiberbuilt",
    "label": "Fiberbuilt",
    "count": 1
  },
  {
    "slug": "swing-caddie",
    "label": "Swing Caddie",
    "count": 1
  },
  {
    "slug": "callaway",
    "label": "Callaway",
    "count": 1
  },
  {
    "slug": "3-trak",
    "label": "3 Trak",
    "count": 1
  },
  {
    "slug": "ag-golf-links",
    "label": "Ag Golf Links",
    "count": 1
  },
  {
    "slug": "ion3",
    "label": "Ion3",
    "count": 1
  },
  {
    "slug": "pga-tour-simulators",
    "label": "Pga Tour Simulators",
    "count": 1
  },
  {
    "slug": "optimotion",
    "label": "Optimotion",
    "count": 1
  },
  {
    "slug": "zen",
    "label": "Zen",
    "count": 1
  },
  {
    "slug": "sg-golf",
    "label": "Sg Golf",
    "count": 1
  },
  {
    "slug": "heradiya",
    "label": "Heradiya",
    "count": 1
  },
  {
    "slug": "k-golf",
    "label": "K Golf",
    "count": 1
  },
  {
    "slug": "rangex",
    "label": "Rangex",
    "count": 1
  },
  {
    "slug": "3trak",
    "label": "3trak",
    "count": 1
  },
  {
    "slug": "forsyth-sports",
    "label": "Forsyth Sports",
    "count": 1
  },
  {
    "slug": "premium-golf-simulator",
    "label": "Premium Golf Simulator",
    "count": 1
  },
  {
    "slug": "hack-motion",
    "label": "Hack Motion",
    "count": 1
  },
  {
    "slug": "brookfields",
    "label": "Brookfields",
    "count": 1
  },
  {
    "slug": "golfforever",
    "label": "Golfforever",
    "count": 1
  },
  {
    "slug": "kit",
    "label": "Kit",
    "count": 1
  },
  {
    "slug": "trueturnpro",
    "label": "Trueturnpro",
    "count": 1
  },
  {
    "slug": "v1",
    "label": "V1",
    "count": 1
  },
  {
    "slug": "visio-putting",
    "label": "Visio Putting",
    "count": 1
  },
  {
    "slug": "pxg",
    "label": "Pxg",
    "count": 1
  },
  {
    "slug": "laser-shot",
    "label": "Laser Shot",
    "count": 1
  },
  {
    "slug": "bravo",
    "label": "Bravo",
    "count": 1
  },
  {
    "slug": "proveex",
    "label": "Proveex",
    "count": 1
  },
  {
    "slug": "chad-johansen",
    "label": "Chad Johansen",
    "count": 1
  },
  {
    "slug": "premium-launch-monitor",
    "label": "Premium Launch Monitor",
    "count": 1
  },
  {
    "slug": "par-t-golf",
    "label": "Par T Golf",
    "count": 1
  },
  {
    "slug": "gtr",
    "label": "Gtr",
    "count": 1
  },
  {
    "slug": "voice-caddie",
    "label": "Voice Caddie",
    "count": 1
  },
  {
    "slug": "impactvision",
    "label": "Impactvision",
    "count": 1
  },
  {
    "slug": "robo-golf-pro",
    "label": "Robo Golf Pro",
    "count": 1
  },
  {
    "slug": "v1-sports",
    "label": "V1 Sports",
    "count": 1
  }
];

// Amenities with venues (3 categories)
export const AVAILABLE_AMENITIES: CategoryItem[] = [
  {
    "slug": "parking",
    "label": "Parking",
    "count": 3870
  },
  {
    "slug": "coaching_available",
    "label": "Coaching",
    "count": 2854
  },
  {
    "slug": "private_rooms",
    "label": "Private Rooms",
    "count": 1398
  }
];

// Software with venues (8 categories)
export const AVAILABLE_SOFTWARE: CategoryItem[] = [
  {
    "slug": "gspro",
    "label": "GSPro",
    "count": 477
  },
  {
    "slug": "e6",
    "label": "E6 Connect",
    "count": 227
  },
  {
    "slug": "fsx",
    "label": "FSX Play",
    "count": 34
  },
  {
    "slug": "tgc",
    "label": "TGC 2019",
    "count": 18
  },
  {
    "slug": "trackman-virtual",
    "label": "TrackMan Virtual",
    "count": 16
  },
  {
    "slug": "awesome-golf",
    "label": "Awesome Golf",
    "count": 1
  },
  {
    "slug": "creative-golf",
    "label": "Creative Golf 3D",
    "count": 1
  },
  {
    "slug": "wgt",
    "label": "WGT",
    "count": 1
  }
];

// Launch monitors with venues (4 categories)
export const AVAILABLE_LAUNCH_MONITORS: CategoryItem[] = [
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 1874
  },
  {
    "slug": "radar",
    "label": "Radar",
    "count": 1361
  },
  {
    "slug": "hybrid",
    "label": "Hybrid",
    "count": 365
  },
  {
    "slug": "photometric_camera",
    "label": "Camera",
    "count": 270
  }
];

/** Convert any slug to URL-friendly format (underscores → hyphens) */
function toUrlSlug(slug: string): string {
  return slug.replace(/_/g, "-");
}

// Helper to get related links for a category (static, no DB query)
export function getStaticRelatedLinks(
  currentCategory: string,
  currentSlug: string,
  limit = 6
): Array<{ href: string; label: string; count: number }> {
  const links: Array<{ href: string; label: string; count: number }> = [];

  // Add vibes (if not current category)
  if (currentCategory !== "vibe") {
    for (const vibe of AVAILABLE_VIBES.slice(0, 2)) {
      links.push({ href: `/best/vibe/${toUrlSlug(vibe.slug)}`, label: `Best ${vibe.label}`, count: vibe.count });
    }
  } else {
    // Add other vibes excluding current
    for (const vibe of AVAILABLE_VIBES.filter(v => v.slug !== currentSlug).slice(0, 2)) {
      links.push({ href: `/best/vibe/${toUrlSlug(vibe.slug)}`, label: `Best ${vibe.label}`, count: vibe.count });
    }
  }

  // Add segments
  if (currentCategory !== "who-its-for") {
    for (const seg of AVAILABLE_SEGMENTS.slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/who-its-for/${toUrlSlug(seg.slug)}`, label: `Best for ${seg.label}`, count: seg.count });
      }
    }
  } else {
    for (const seg of AVAILABLE_SEGMENTS.filter(s => s.slug !== currentSlug).slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/who-its-for/${toUrlSlug(seg.slug)}`, label: `Best for ${seg.label}`, count: seg.count });
      }
    }
  }

  // Add hardware
  if (currentCategory !== "hardware") {
    for (const hw of AVAILABLE_HARDWARE.slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/hardware/${toUrlSlug(hw.slug)}`, label: `Best ${hw.label}`, count: hw.count });
      }
    }
  } else {
    for (const hw of AVAILABLE_HARDWARE.filter(h => h.slug !== currentSlug).slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/hardware/${toUrlSlug(hw.slug)}`, label: `Best ${hw.label}`, count: hw.count });
      }
    }
  }

  return links.slice(0, limit);
}

// Check if a category slug has venues (matches both underscore and hyphen formats)
export function hasVenues(category: string, slug: string): boolean {
  const variants = [slug, slug.replace(/-/g, "_"), slug.replace(/_/g, "-")];
  switch (category) {
    case "tags": return AVAILABLE_TAGS.some(t => variants.includes(t.slug));
    case "vibe": return AVAILABLE_VIBES.some(v => variants.includes(v.slug));
    case "who-its-for": return AVAILABLE_SEGMENTS.some(s => variants.includes(s.slug));
    case "hardware": return AVAILABLE_HARDWARE.some(h => variants.includes(h.slug));
    case "amenities": return AVAILABLE_AMENITIES.some(a => variants.includes(a.slug));
    case "software": return AVAILABLE_SOFTWARE.some(s => variants.includes(s.slug));
    case "launch-monitor": return AVAILABLE_LAUNCH_MONITORS.some(l => variants.includes(l.slug));
    default: return false;
  }
}
