// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: npx ts-node scripts/analyze-categories.ts
// Generated at: 2026-02-10T02:22:35.418Z
// Total venues: 3153

export interface CategoryItem {
  slug: string;
  label: string;
  count: number;
}

export const GENERATED_AT = "2026-02-10T02:22:35.418Z";
export const TOTAL_VENUES = 3153;

// Tags with venues (465 categories)
export const AVAILABLE_TAGS: CategoryItem[] = [
  {
    "slug": "beginner_friendly",
    "label": "Beginner Friendly",
    "count": 2726
  },
  {
    "slug": "premium_tech",
    "label": "Premium Tech",
    "count": 2457
  },
  {
    "slug": "coaching_available",
    "label": "Coaching Available",
    "count": 2323
  },
  {
    "slug": "corporate_events",
    "label": "Corporate Events",
    "count": 2311
  },
  {
    "slug": "food_and_drinks",
    "label": "Food And Drinks",
    "count": 1888
  },
  {
    "slug": "leagues",
    "label": "Leagues",
    "count": 1809
  },
  {
    "slug": "club_rentals",
    "label": "Club Rentals",
    "count": 1777
  },
  {
    "slug": "private_rooms",
    "label": "Private Rooms",
    "count": 1698
  },
  {
    "slug": "date_night",
    "label": "Date Night",
    "count": 951
  },
  {
    "slug": "budget_friendly",
    "label": "Budget Friendly",
    "count": 720
  },
  {
    "slug": "serious_practice",
    "label": "Serious Practice",
    "count": 636
  },
  {
    "slug": "community_club",
    "label": "Community Club",
    "count": 568
  },
  {
    "slug": "serious_golfers",
    "label": "Serious Golfers",
    "count": 567
  },
  {
    "slug": "juniors_youth",
    "label": "Juniors Youth",
    "count": 563
  },
  {
    "slug": "family_friendly",
    "label": "Family Friendly",
    "count": 541
  },
  {
    "slug": "kids_friendly",
    "label": "Kids Friendly",
    "count": 420
  },
  {
    "slug": "late_night",
    "label": "Late Night",
    "count": 372
  },
  {
    "slug": "club_fitting",
    "label": "Club Fitting",
    "count": 285
  },
  {
    "slug": "solo_practice",
    "label": "Solo Practice",
    "count": 249
  },
  {
    "slug": "families",
    "label": "Families",
    "count": 207
  },
  {
    "slug": "pro_shop",
    "label": "Pro Shop",
    "count": 147
  },
  {
    "slug": "family_fun_center",
    "label": "Family Fun Center",
    "count": 128
  },
  {
    "slug": "party_atmosphere",
    "label": "Party Atmosphere",
    "count": 102
  },
  {
    "slug": "casual",
    "label": "Casual",
    "count": 90
  },
  {
    "slug": "corporate_teams",
    "label": "Corporate Teams",
    "count": 72
  },
  {
    "slug": "upscale_lounge",
    "label": "Upscale Lounge",
    "count": 71
  },
  {
    "slug": "large_groups",
    "label": "Large Groups",
    "count": 61
  },
  {
    "slug": "low_handicap",
    "label": "Low Handicap",
    "count": 56
  },
  {
    "slug": "indoor_golf",
    "label": "Indoor Golf",
    "count": 55
  },
  {
    "slug": "modern",
    "label": "Modern",
    "count": 51
  },
  {
    "slug": "tech_lab",
    "label": "Tech Lab",
    "count": 49
  },
  {
    "slug": "group_friendly",
    "label": "Group Friendly",
    "count": 44
  },
  {
    "slug": "membership_only",
    "label": "Membership Only",
    "count": 42
  },
  {
    "slug": "welcoming",
    "label": "Welcoming",
    "count": 40
  },
  {
    "slug": "sports_bar",
    "label": "Sports Bar",
    "count": 33
  },
  {
    "slug": "retail_fitting_center",
    "label": "Retail Fitting Center",
    "count": 32
  },
  {
    "slug": "simulator",
    "label": "Simulator",
    "count": 30
  },
  {
    "slug": "social",
    "label": "Social",
    "count": 29
  },
  {
    "slug": "group_events",
    "label": "Group Events",
    "count": 28
  },
  {
    "slug": "tourists_travelers",
    "label": "Tourists Travelers",
    "count": 25
  },
  {
    "slug": "training_studio",
    "label": "Training Studio",
    "count": 25
  },
  {
    "slug": "events",
    "label": "Events",
    "count": 24
  },
  {
    "slug": "adults_only",
    "label": "Adults Only",
    "count": 23
  },
  {
    "slug": "data_driven",
    "label": "Data Driven",
    "count": 22
  },
  {
    "slug": "private_luxury",
    "label": "Private Luxury",
    "count": 22
  },
  {
    "slug": "private_events",
    "label": "Private Events",
    "count": 20
  },
  {
    "slug": "multi_sport",
    "label": "Multi Sport",
    "count": 20
  },
  {
    "slug": "kid_friendly",
    "label": "Kid Friendly",
    "count": 20
  },
  {
    "slug": "lessons",
    "label": "Lessons",
    "count": 20
  },
  {
    "slug": "beginners",
    "label": "Beginners",
    "count": 18
  },
  {
    "slug": "retro_gaming",
    "label": "Retro Gaming",
    "count": 18
  },
  {
    "slug": "practice_memberships",
    "label": "Practice Memberships",
    "count": 17
  },
  {
    "slug": "ada_accessible",
    "label": "Ada Accessible",
    "count": 16
  },
  {
    "slug": "entertainment",
    "label": "Entertainment",
    "count": 15
  },
  {
    "slug": "practice",
    "label": "Practice",
    "count": 14
  },
  {
    "slug": "membership",
    "label": "Membership",
    "count": 13
  },
  {
    "slug": "upscale",
    "label": "Upscale",
    "count": 13
  },
  {
    "slug": "multi_sport_sim",
    "label": "Multi Sport Sim",
    "count": 13
  },
  {
    "slug": "instruction",
    "label": "Instruction",
    "count": 12
  },
  {
    "slug": "sim_bar",
    "label": "Sim Bar",
    "count": 12
  },
  {
    "slug": "24_7_access",
    "label": "24 7 Access",
    "count": 11
  },
  {
    "slug": "improvement",
    "label": "Improvement",
    "count": 11
  },
  {
    "slug": "bachelor_parties",
    "label": "Bachelor Parties",
    "count": 10
  },
  {
    "slug": "practice_facility",
    "label": "Practice Facility",
    "count": 10
  },
  {
    "slug": "mobile_service",
    "label": "Mobile Service",
    "count": 10
  },
  {
    "slug": "private_rental",
    "label": "Private Rental",
    "count": 10
  },
  {
    "slug": "members_only",
    "label": "Members Only",
    "count": 10
  },
  {
    "slug": "trackman",
    "label": "Trackman",
    "count": 10
  },
  {
    "slug": "lefty_friendly",
    "label": "Lefty Friendly",
    "count": 10
  },
  {
    "slug": "casual_play",
    "label": "Casual Play",
    "count": 9
  },
  {
    "slug": "casual_atmosphere",
    "label": "Casual Atmosphere",
    "count": 9
  },
  {
    "slug": "family_fun",
    "label": "Family Fun",
    "count": 8
  },
  {
    "slug": "group_activities",
    "label": "Group Activities",
    "count": 8
  },
  {
    "slug": "country_club",
    "label": "Country Club",
    "count": 8
  },
  {
    "slug": "golf_simulator",
    "label": "Golf Simulator",
    "count": 8
  },
  {
    "slug": "memberships",
    "label": "Memberships",
    "count": 8
  },
  {
    "slug": "byob",
    "label": "Byob",
    "count": 7
  },
  {
    "slug": "group_lessons",
    "label": "Group Lessons",
    "count": 7
  },
  {
    "slug": "groups",
    "label": "Groups",
    "count": 7
  },
  {
    "slug": "membership_club",
    "label": "Membership Club",
    "count": 7
  },
  {
    "slug": "casual_golf",
    "label": "Casual Golf",
    "count": 7
  },
  {
    "slug": "custom_fitting",
    "label": "Custom Fitting",
    "count": 6
  },
  {
    "slug": "wifi",
    "label": "Wifi",
    "count": 6
  },
  {
    "slug": "practice_focused",
    "label": "Practice Focused",
    "count": 6
  },
  {
    "slug": "group_bookings",
    "label": "Group Bookings",
    "count": 5
  },
  {
    "slug": "fitness_training",
    "label": "Fitness Training",
    "count": 5
  },
  {
    "slug": "virtual_golf",
    "label": "Virtual Golf",
    "count": 5
  },
  {
    "slug": "bar",
    "label": "Bar",
    "count": 5
  },
  {
    "slug": "retail",
    "label": "Retail",
    "count": 5
  },
  {
    "slug": "modern_facility",
    "label": "Modern Facility",
    "count": 5
  },
  {
    "slug": "parties",
    "label": "Parties",
    "count": 5
  },
  {
    "slug": "online_booking",
    "label": "Online Booking",
    "count": 4
  },
  {
    "slug": "fitness",
    "label": "Fitness",
    "count": 4
  },
  {
    "slug": "technology",
    "label": "Technology",
    "count": 4
  },
  {
    "slug": "indoor_facility",
    "label": "Indoor Facility",
    "count": 4
  },
  {
    "slug": "social_golf",
    "label": "Social Golf",
    "count": 4
  },
  {
    "slug": "group_outings",
    "label": "Group Outings",
    "count": 4
  },
  {
    "slug": "speakeasy",
    "label": "Speakeasy",
    "count": 4
  },
  {
    "slug": "climate_controlled",
    "label": "Climate Controlled",
    "count": 4
  },
  {
    "slug": "membership_required",
    "label": "Membership Required",
    "count": 4
  },
  {
    "slug": "flexible_hours",
    "label": "Flexible Hours",
    "count": 4
  },
  {
    "slug": "golf_simulation",
    "label": "Golf Simulation",
    "count": 4
  },
  {
    "slug": "technology_driven",
    "label": "Technology Driven",
    "count": 4
  },
  {
    "slug": "public_course",
    "label": "Public Course",
    "count": 4
  },
  {
    "slug": "private_rentals",
    "label": "Private Rentals",
    "count": 3
  },
  {
    "slug": "membership_options",
    "label": "Membership Options",
    "count": 3
  },
  {
    "slug": "year_round_access",
    "label": "Year Round Access",
    "count": 3
  },
  {
    "slug": "tech_focused",
    "label": "Tech Focused",
    "count": 3
  },
  {
    "slug": "outdoor_events",
    "label": "Outdoor Events",
    "count": 3
  },
  {
    "slug": "outdoor_golf",
    "label": "Outdoor Golf",
    "count": 3
  },
  {
    "slug": "private_bays",
    "label": "Private Bays",
    "count": 3
  },
  {
    "slug": "trackman_simulator",
    "label": "Trackman Simulator",
    "count": 3
  },
  {
    "slug": "junior_friendly",
    "label": "Junior Friendly",
    "count": 3
  },
  {
    "slug": "indoor",
    "label": "Indoor",
    "count": 3
  },
  {
    "slug": "convenient",
    "label": "Convenient",
    "count": 3
  },
  {
    "slug": "membership_based",
    "label": "Membership Based",
    "count": 3
  },
  {
    "slug": "social_atmosphere",
    "label": "Social Atmosphere",
    "count": 3
  },
  {
    "slug": "residential",
    "label": "Residential",
    "count": 3
  },
  {
    "slug": "junior_youth",
    "label": "Junior Youth",
    "count": 3
  },
  {
    "slug": "performance_tracking",
    "label": "Performance Tracking",
    "count": 3
  },
  {
    "slug": "coaching",
    "label": "Coaching",
    "count": 3
  },
  {
    "slug": "social_club",
    "label": "Social Club",
    "count": 3
  },
  {
    "slug": "community_focused",
    "label": "Community Focused",
    "count": 3
  },
  {
    "slug": "training_center",
    "label": "Training Center",
    "count": 3
  },
  {
    "slug": "tournaments",
    "label": "Tournaments",
    "count": 3
  },
  {
    "slug": "data_analysis",
    "label": "Data Analysis",
    "count": 3
  },
  {
    "slug": "tech_friendly",
    "label": "Tech Friendly",
    "count": 3
  },
  {
    "slug": "indoor golf",
    "label": "Indoor Golf",
    "count": 3
  },
  {
    "slug": "simulator_rental",
    "label": "Simulator Rental",
    "count": 2
  },
  {
    "slug": "outdoor_course",
    "label": "Outdoor Course",
    "count": 2
  },
  {
    "slug": "training",
    "label": "Training",
    "count": 2
  },
  {
    "slug": "gift_cards",
    "label": "Gift Cards",
    "count": 2
  },
  {
    "slug": "adult_friendly",
    "label": "Adult Friendly",
    "count": 2
  },
  {
    "slug": "simulators",
    "label": "Simulators",
    "count": 2
  },
  {
    "slug": "tech_driven",
    "label": "Tech Driven",
    "count": 2
  },
  {
    "slug": "veteran_owned",
    "label": "Veteran Owned",
    "count": 2
  },
  {
    "slug": "modern_facilities",
    "label": "Modern Facilities",
    "count": 2
  },
  {
    "slug": "fitness_focused",
    "label": "Fitness Focused",
    "count": 2
  },
  {
    "slug": "club_repair",
    "label": "Club Repair",
    "count": 2
  },
  {
    "slug": "equipment_fitting",
    "label": "Equipment Fitting",
    "count": 2
  },
  {
    "slug": "event_venue",
    "label": "Event Venue",
    "count": 2
  },
  {
    "slug": "club_fittings",
    "label": "Club Fittings",
    "count": 2
  },
  {
    "slug": "private_lessons",
    "label": "Private Lessons",
    "count": 2
  },
  {
    "slug": "golf_fitness",
    "label": "Golf Fitness",
    "count": 2
  },
  {
    "slug": "Trackman",
    "label": "Trackman",
    "count": 2
  },
  {
    "slug": "improvement_focused",
    "label": "Improvement Focused",
    "count": 2
  },
  {
    "slug": "indoor_training",
    "label": "Indoor Training",
    "count": 2
  },
  {
    "slug": "unlimited_access",
    "label": "Unlimited Access",
    "count": 2
  },
  {
    "slug": "game_improvement",
    "label": "Game Improvement",
    "count": 2
  },
  {
    "slug": "weddings",
    "label": "Weddings",
    "count": 2
  },
  {
    "slug": "fundraisers",
    "label": "Fundraisers",
    "count": 2
  },
  {
    "slug": "beginners_friendly",
    "label": "Beginners Friendly",
    "count": 2
  },
  {
    "slug": "private_suites",
    "label": "Private Suites",
    "count": 2
  },
  {
    "slug": "24/7_access",
    "label": "24/7 Access",
    "count": 2
  },
  {
    "slug": "custom_design",
    "label": "Custom Design",
    "count": 2
  },
  {
    "slug": "commercial",
    "label": "Commercial",
    "count": 2
  },
  {
    "slug": "customizable",
    "label": "Customizable",
    "count": 2
  },
  {
    "slug": "no_walk_ins",
    "label": "No Walk Ins",
    "count": 2
  },
  {
    "slug": "birthday_parties",
    "label": "Birthday Parties",
    "count": 2
  },
  {
    "slug": "casual_gaming",
    "label": "Casual Gaming",
    "count": 2
  },
  {
    "slug": "arizona",
    "label": "Arizona",
    "count": 2
  },
  {
    "slug": "coaches_instructors",
    "label": "Coaches Instructors",
    "count": 2
  },
  {
    "slug": "league_play",
    "label": "League Play",
    "count": 2
  },
  {
    "slug": "social_memberships",
    "label": "Social Memberships",
    "count": 2
  },
  {
    "slug": "speed_training",
    "label": "Speed Training",
    "count": 2
  },
  {
    "slug": "data_analytics",
    "label": "Data Analytics",
    "count": 2
  },
  {
    "slug": "private_instruction",
    "label": "Private Instruction",
    "count": 2
  },
  {
    "slug": "seasonal",
    "label": "Seasonal",
    "count": 2
  },
  {
    "slug": "customizable_packages",
    "label": "Customizable Packages",
    "count": 2
  },
  {
    "slug": "by_appointment",
    "label": "By Appointment",
    "count": 2
  },
  {
    "slug": "private_club",
    "label": "Private Club",
    "count": 2
  },
  {
    "slug": "scenic_course",
    "label": "Scenic Course",
    "count": 2
  },
  {
    "slug": "golf_outings",
    "label": "Golf Outings",
    "count": 2
  },
  {
    "slug": "year_round_golf",
    "label": "Year Round Golf",
    "count": 2
  },
  {
    "slug": "winter_golf",
    "label": "Winter Golf",
    "count": 2
  },
  {
    "slug": "flexible_pricing",
    "label": "Flexible Pricing",
    "count": 2
  },
  {
    "slug": "24_hour_access",
    "label": "24 Hour Access",
    "count": 2
  },
  {
    "slug": "membership_available",
    "label": "Membership Available",
    "count": 2
  },
  {
    "slug": "corporate events",
    "label": "Corporate Events",
    "count": 2
  },
  {
    "slug": "tv_sports",
    "label": "Tv Sports",
    "count": 2
  },
  {
    "slug": "pga_professional",
    "label": "Pga Professional",
    "count": 2
  },
  {
    "slug": "year_round",
    "label": "Year Round",
    "count": 1
  },
  {
    "slug": "walk_in_friendly",
    "label": "Walk In Friendly",
    "count": 1
  },
  {
    "slug": "short_game_practice",
    "label": "Short Game Practice",
    "count": 1
  },
  {
    "slug": "women_friendly",
    "label": "Women Friendly",
    "count": 1
  },
  {
    "slug": "virtual_courses",
    "label": "Virtual Courses",
    "count": 1
  },
  {
    "slug": "remote_coaching",
    "label": "Remote Coaching",
    "count": 1
  },
  {
    "slug": "dallas_area",
    "label": "Dallas Area",
    "count": 1
  },
  {
    "slug": "location_based",
    "label": "Location Based",
    "count": 1
  },
  {
    "slug": "long_island",
    "label": "Long Island",
    "count": 1
  },
  {
    "slug": "team_practice",
    "label": "Team Practice",
    "count": 1
  },
  {
    "slug": "indoor_climate_control",
    "label": "Indoor Climate Control",
    "count": 1
  },
  {
    "slug": "membership_benefits",
    "label": "Membership Benefits",
    "count": 1
  },
  {
    "slug": "affordable_training",
    "label": "Affordable Training",
    "count": 1
  },
  {
    "slug": "secure_payment",
    "label": "Secure Payment",
    "count": 1
  },
  {
    "slug": "skill_improvement",
    "label": "Skill Improvement",
    "count": 1
  },
  {
    "slug": "professional_services",
    "label": "Professional Services",
    "count": 1
  },
  {
    "slug": "specialty_retail",
    "label": "Specialty Retail",
    "count": 1
  },
  {
    "slug": "social_fun",
    "label": "Social Fun",
    "count": 1
  },
  {
    "slug": "bistro_atmosphere",
    "label": "Bistro Atmosphere",
    "count": 1
  },
  {
    "slug": "golf_practice",
    "label": "Golf Practice",
    "count": 1
  },
  {
    "slug": "year_round_training",
    "label": "Year Round Training",
    "count": 1
  },
  {
    "slug": "charity_events",
    "label": "Charity Events",
    "count": 1
  },
  {
    "slug": "retail_store",
    "label": "Retail Store",
    "count": 1
  },
  {
    "slug": "fitness_integration",
    "label": "Fitness Integration",
    "count": 1
  },
  {
    "slug": "events_weddings",
    "label": "Events Weddings",
    "count": 1
  },
  {
    "slug": "destination_golf",
    "label": "Destination Golf",
    "count": 1
  },
  {
    "slug": "group_coaching",
    "label": "Group Coaching",
    "count": 1
  },
  {
    "slug": "indoor_simulators",
    "label": "Indoor Simulators",
    "count": 1
  },
  {
    "slug": "trackman_technology",
    "label": "Trackman Technology",
    "count": 1
  },
  {
    "slug": "elite_coaching",
    "label": "Elite Coaching",
    "count": 1
  },
  {
    "slug": "north_grafton",
    "label": "North Grafton",
    "count": 1
  },
  {
    "slug": "group_booking",
    "label": "Group Booking",
    "count": 1
  },
  {
    "slug": "technology_focused",
    "label": "Technology Focused",
    "count": 1
  },
  {
    "slug": "improvement_tools",
    "label": "Improvement Tools",
    "count": 1
  },
  {
    "slug": "bookable_app",
    "label": "Bookable App",
    "count": 1
  },
  {
    "slug": "limited_membership",
    "label": "Limited Membership",
    "count": 1
  },
  {
    "slug": "unlimited_play",
    "label": "Unlimited Play",
    "count": 1
  },
  {
    "slug": "byob_allowed",
    "label": "Byob Allowed",
    "count": 1
  },
  {
    "slug": "indoor_year_round",
    "label": "Indoor Year Round",
    "count": 1
  },
  {
    "slug": "capped_memberships",
    "label": "Capped Memberships",
    "count": 1
  },
  {
    "slug": "access_controlled",
    "label": "Access Controlled",
    "count": 1
  },
  {
    "slug": "no_crowds",
    "label": "No Crowds",
    "count": 1
  },
  {
    "slug": "public_access",
    "label": "Public Access",
    "count": 1
  },
  {
    "slug": "online_academy",
    "label": "Online Academy",
    "count": 1
  },
  {
    "slug": "mobile_app",
    "label": "Mobile App",
    "count": 1
  },
  {
    "slug": "airport_convenient",
    "label": "Airport Convenient",
    "count": 1
  },
  {
    "slug": "financial_district",
    "label": "Financial District",
    "count": 1
  },
  {
    "slug": "one_on_one",
    "label": "One On One",
    "count": 1
  },
  {
    "slug": "unlimited_bay_reservations",
    "label": "Unlimited Bay Reservations",
    "count": 1
  },
  {
    "slug": "affordable_membership",
    "label": "Affordable Membership",
    "count": 1
  },
  {
    "slug": "state_of_the_art",
    "label": "State Of The Art",
    "count": 1
  },
  {
    "slug": "nebraska_iowa",
    "label": "Nebraska Iowa",
    "count": 1
  },
  {
    "slug": "bar_promotions",
    "label": "Bar Promotions",
    "count": 1
  },
  {
    "slug": "interactive_experience",
    "label": "Interactive Experience",
    "count": 1
  },
  {
    "slug": "all_inclusive",
    "label": "All Inclusive",
    "count": 1
  },
  {
    "slug": " memberships",
    "label": " Memberships",
    "count": 1
  },
  {
    "slug": "new_england",
    "label": "New England",
    "count": 1
  },
  {
    "slug": "quality_service",
    "label": "Quality Service",
    "count": 1
  },
  {
    "slug": "local_expert",
    "label": "Local Expert",
    "count": 1
  },
  {
    "slug": "white_glove_service",
    "label": "White Glove Service",
    "count": 1
  },
  {
    "slug": "night_golf",
    "label": "Night Golf",
    "count": 1
  },
  {
    "slug": "group_sessions",
    "label": "Group Sessions",
    "count": 1
  },
  {
    "slug": "social_outing",
    "label": "Social Outing",
    "count": 1
  },
  {
    "slug": "privacy_focused",
    "label": "Privacy Focused",
    "count": 1
  },
  {
    "slug": "customizable_sessions",
    "label": "Customizable Sessions",
    "count": 1
  },
  {
    "slug": "performance_training",
    "label": "Performance Training",
    "count": 1
  },
  {
    "slug": "tpc_courses",
    "label": "Tpc Courses",
    "count": 1
  },
  {
    "slug": "simulator_rentals",
    "label": "Simulator Rentals",
    "count": 1
  },
  {
    "slug": "bar_food",
    "label": "Bar Food",
    "count": 1
  },
  {
    "slug": "mobile_simulators",
    "label": "Mobile Simulators",
    "count": 1
  },
  {
    "slug": "equipment_rental",
    "label": "Equipment Rental",
    "count": 1
  },
  {
    "slug": "24_hours",
    "label": "24 Hours",
    "count": 1
  },
  {
    "slug": "adult_leagues",
    "label": "Adult Leagues",
    "count": 1
  },
  {
    "slug": "gym_access",
    "label": "Gym Access",
    "count": 1
  },
  {
    "slug": "group_practice",
    "label": "Group Practice",
    "count": 1
  },
  {
    "slug": "convenient_booking",
    "label": "Convenient Booking",
    "count": 1
  },
  {
    "slug": "monthly_memberships",
    "label": "Monthly Memberships",
    "count": 1
  },
  {
    "slug": "no_long_term_contract",
    "label": "No Long Term Contract",
    "count": 1
  },
  {
    "slug": "indoor_practice",
    "label": "Indoor Practice",
    "count": 1
  },
  {
    "slug": "no_wait_time",
    "label": "No Wait Time",
    "count": 1
  },
  {
    "slug": "golden_tee",
    "label": "Golden Tee",
    "count": 1
  },
  {
    "slug": "no_staff",
    "label": "No Staff",
    "count": 1
  },
  {
    "slug": "convenient_access",
    "label": "Convenient Access",
    "count": 1
  },
  {
    "slug": "atmosphere_21+",
    "label": "Atmosphere 21+",
    "count": 1
  },
  {
    "slug": "custom_events",
    "label": "Custom Events",
    "count": 1
  },
  {
    "slug": "bays",
    "label": "Bays",
    "count": 1
  },
  {
    "slug": "nashville",
    "label": "Nashville",
    "count": 1
  },
  {
    "slug": "bethpage",
    "label": "Bethpage",
    "count": 1
  },
  {
    "slug": "ny",
    "label": "Ny",
    "count": 1
  },
  {
    "slug": "birmingham_al",
    "label": "Birmingham Al",
    "count": 1
  },
  {
    "slug": "chardon_area",
    "label": "Chardon Area",
    "count": 1
  },
  {
    "slug": "recreational_golf",
    "label": "Recreational Golf",
    "count": 1
  },
  {
    "slug": "affordable_option",
    "label": "Affordable Option",
    "count": 1
  },
  {
    "slug": "community_events",
    "label": "Community Events",
    "count": 1
  },
  {
    "slug": "gilbert",
    "label": "Gilbert",
    "count": 1
  },
  {
    "slug": "outdoor_activity",
    "label": "Outdoor Activity",
    "count": 1
  },
  {
    "slug": "granbury",
    "label": "Granbury",
    "count": 1
  },
  {
    "slug": "central_texas",
    "label": "Central Texas",
    "count": 1
  },
  {
    "slug": "leander",
    "label": "Leander",
    "count": 1
  },
  {
    "slug": "lubbock",
    "label": "Lubbock",
    "count": 1
  },
  {
    "slug": "fun",
    "label": "Fun",
    "count": 1
  },
  {
    "slug": "mesa",
    "label": "Mesa",
    "count": 1
  },
  {
    "slug": "peoria_az",
    "label": "Peoria Az",
    "count": 1
  },
  {
    "slug": "weekend_activity",
    "label": "Weekend Activity",
    "count": 1
  },
  {
    "slug": "local_golf",
    "label": "Local Golf",
    "count": 1
  },
  {
    "slug": "ponte_vedra",
    "label": "Ponte Vedra",
    "count": 1
  },
  {
    "slug": "florida",
    "label": "Florida",
    "count": 1
  },
  {
    "slug": "golf_entertainment",
    "label": "Golf Entertainment",
    "count": 1
  },
  {
    "slug": "social_sport",
    "label": "Social Sport",
    "count": 1
  },
  {
    "slug": "training_available",
    "label": "Training Available",
    "count": 1
  },
  {
    "slug": "tyler_tx",
    "label": "Tyler Tx",
    "count": 1
  },
  {
    "slug": "sports_entertainment",
    "label": "Sports Entertainment",
    "count": 1
  },
  {
    "slug": "golf_lessons",
    "label": "Golf Lessons",
    "count": 1
  },
  {
    "slug": "putting_lab",
    "label": "Putting Lab",
    "count": 1
  },
  {
    "slug": "golf_repair",
    "label": "Golf Repair",
    "count": 1
  },
  {
    "slug": "custom_installations",
    "label": "Custom Installations",
    "count": 1
  },
  {
    "slug": "luxury_experience",
    "label": "Luxury Experience",
    "count": 1
  },
  {
    "slug": "atlanta_based",
    "label": "Atlanta Based",
    "count": 1
  },
  {
    "slug": "comprehensive_services",
    "label": "Comprehensive Services",
    "count": 1
  },
  {
    "slug": "design_build",
    "label": "Design Build",
    "count": 1
  },
  {
    "slug": "after_hours_access",
    "label": "After Hours Access",
    "count": 1
  },
  {
    "slug": "bar_and_lounge",
    "label": "Bar And Lounge",
    "count": 1
  },
  {
    "slug": "putting_analysis",
    "label": "Putting Analysis",
    "count": 1
  },
  {
    "slug": "Golf Simulators",
    "label": "Golf Simulators",
    "count": 1
  },
  {
    "slug": "Bar",
    "label": "Bar",
    "count": 1
  },
  {
    "slug": "Game Room",
    "label": "Game Room",
    "count": 1
  },
  {
    "slug": "Sports Bar",
    "label": "Sports Bar",
    "count": 1
  },
  {
    "slug": "Entertainment",
    "label": "Entertainment",
    "count": 1
  },
  {
    "slug": "weekend_warriors",
    "label": "Weekend Warriors",
    "count": 1
  },
  {
    "slug": "structured_practice",
    "label": "Structured Practice",
    "count": 1
  },
  {
    "slug": "entertainment_center",
    "label": "Entertainment Center",
    "count": 1
  },
  {
    "slug": "upscale_environment",
    "label": "Upscale Environment",
    "count": 1
  },
  {
    "slug": "golf",
    "label": "Golf",
    "count": 1
  },
  {
    "slug": "training_aid_available",
    "label": "Training Aid Available",
    "count": 1
  },
  {
    "slug": "exclusive_events",
    "label": "Exclusive Events",
    "count": 1
  },
  {
    "slug": "juniors_friendly",
    "label": "Juniors Friendly",
    "count": 1
  },
  {
    "slug": "adult_focused",
    "label": "Adult Focused",
    "count": 1
  },
  {
    "slug": "indoor_entertainment",
    "label": "Indoor Entertainment",
    "count": 1
  },
  {
    "slug": "weather_proof",
    "label": "Weather Proof",
    "count": 1
  },
  {
    "slug": "app_based_booking",
    "label": "App Based Booking",
    "count": 1
  },
  {
    "slug": "family_owned",
    "label": "Family Owned",
    "count": 1
  },
  {
    "slug": "private_parties",
    "label": "Private Parties",
    "count": 1
  },
  {
    "slug": "festivals",
    "label": "Festivals",
    "count": 1
  },
  {
    "slug": "trade_shows",
    "label": "Trade Shows",
    "count": 1
  },
  {
    "slug": "fitness_center",
    "label": "Fitness Center",
    "count": 1
  },
  {
    "slug": "indoor_events",
    "label": "Indoor Events",
    "count": 1
  },
  {
    "slug": "resort_amenities",
    "label": "Resort Amenities",
    "count": 1
  },
  {
    "slug": "all_skill_levels",
    "label": "All Skill Levels",
    "count": 1
  },
  {
    "slug": "driving_range",
    "label": "Driving Range",
    "count": 1
  },
  {
    "slug": "downtown",
    "label": "Downtown",
    "count": 1
  },
  {
    "slug": "scenic_views",
    "label": "Scenic Views",
    "count": 1
  },
  {
    "slug": "custom_clubs",
    "label": "Custom Clubs",
    "count": 1
  },
  {
    "slug": "private_appointment",
    "label": "Private Appointment",
    "count": 1
  },
  {
    "slug": "accessible",
    "label": "Accessible",
    "count": 1
  },
  {
    "slug": "golf_simulators",
    "label": "Golf Simulators",
    "count": 1
  },
  {
    "slug": "baseball_training",
    "label": "Baseball Training",
    "count": 1
  },
  {
    "slug": "batting_cages",
    "label": "Batting Cages",
    "count": 1
  },
  {
    "slug": "lessons_training",
    "label": "Lessons Training",
    "count": 1
  },
  {
    "slug": "hittrax",
    "label": "Hittrax",
    "count": 1
  },
  {
    "slug": "arcade",
    "label": "Arcade",
    "count": 1
  },
  {
    "slug": "executive_course",
    "label": "Executive Course",
    "count": 1
  },
  {
    "slug": "historic_course",
    "label": "Historic Course",
    "count": 1
  },
  {
    "slug": "walking_friendly",
    "label": "Walking Friendly",
    "count": 1
  },
  {
    "slug": "mountain_valley",
    "label": "Mountain Valley",
    "count": 1
  },
  {
    "slug": "day_trip",
    "label": "Day Trip",
    "count": 1
  },
  {
    "slug": "famous_courses",
    "label": "Famous Courses",
    "count": 1
  },
  {
    "slug": "mini_games",
    "label": "Mini Games",
    "count": 1
  },
  {
    "slug": "competitive_play",
    "label": "Competitive Play",
    "count": 1
  },
  {
    "slug": "resort",
    "label": "Resort",
    "count": 1
  },
  {
    "slug": "simulator_golf",
    "label": "Simulator Golf",
    "count": 1
  },
  {
    "slug": "bar_lounge",
    "label": "Bar Lounge",
    "count": 1
  },
  {
    "slug": "fitness_facility",
    "label": "Fitness Facility",
    "count": 1
  },
  {
    "slug": "indoor_outdoor",
    "label": "Indoor Outdoor",
    "count": 1
  },
  {
    "slug": "urban_arena",
    "label": "Urban Arena",
    "count": 1
  },
  {
    "slug": "BYOB",
    "label": "BYOB",
    "count": 1
  },
  {
    "slug": "practice_sessions",
    "label": "Practice Sessions",
    "count": 1
  },
  {
    "slug": "no_weather_issues",
    "label": "No Weather Issues",
    "count": 1
  },
  {
    "slug": "founding_members",
    "label": "Founding Members",
    "count": 1
  },
  {
    "slug": "no_public_play",
    "label": "No Public Play",
    "count": 1
  },
  {
    "slug": "racing_simulators",
    "label": "Racing Simulators",
    "count": 1
  },
  {
    "slug": "outings_tournaments",
    "label": "Outings Tournaments",
    "count": 1
  },
  {
    "slug": "outdoor_facility",
    "label": "Outdoor Facility",
    "count": 1
  },
  {
    "slug": "parking_available",
    "label": "Parking Available",
    "count": 1
  },
  {
    "slug": "partner_facility",
    "label": "Partner Facility",
    "count": 1
  },
  {
    "slug": "portable_rentals",
    "label": "Portable Rentals",
    "count": 1
  },
  {
    "slug": "team_building",
    "label": "Team Building",
    "count": 1
  },
  {
    "slug": "private_members_only",
    "label": "Private Members Only",
    "count": 1
  },
  {
    "slug": "poway",
    "label": "Poway",
    "count": 1
  },
  {
    "slug": "retail_fitting",
    "label": "Retail Fitting",
    "count": 1
  },
  {
    "slug": "ADA_accessible",
    "label": "ADA Accessible",
    "count": 1
  },
  {
    "slug": "pga_professionals",
    "label": "Pga Professionals",
    "count": 1
  },
  {
    "slug": "custom_fit",
    "label": "Custom Fit",
    "count": 1
  },
  {
    "slug": "resort_style",
    "label": "Resort Style",
    "count": 1
  },
  {
    "slug": "private_studio",
    "label": "Private Studio",
    "count": 1
  },
  {
    "slug": "pro_shop_discount",
    "label": "Pro Shop Discount",
    "count": 1
  },
  {
    "slug": "social_friendly",
    "label": "Social Friendly",
    "count": 1
  },
  {
    "slug": "anytime_access",
    "label": "Anytime Access",
    "count": 1
  },
  {
    "slug": "pickleball",
    "label": "Pickleball",
    "count": 1
  },
  {
    "slug": "golf simulator",
    "label": "Golf Simulator",
    "count": 1
  },
  {
    "slug": "lounge",
    "label": "Lounge",
    "count": 1
  },
  {
    "slug": "family-friendly",
    "label": "Family Friendly",
    "count": 1
  },
  {
    "slug": "date night",
    "label": "Date Night",
    "count": 1
  },
  {
    "slug": "bachelor party",
    "label": "Bachelor Party",
    "count": 1
  },
  {
    "slug": "birthday parties",
    "label": "Birthday Parties",
    "count": 1
  },
  {
    "slug": "practice facility",
    "label": "Practice Facility",
    "count": 1
  },
  {
    "slug": "membership_program",
    "label": "Membership Program",
    "count": 1
  },
  {
    "slug": "custom_club_repair",
    "label": "Custom Club Repair",
    "count": 1
  },
  {
    "slug": "arcade_games",
    "label": "Arcade Games",
    "count": 1
  },
  {
    "slug": "food_and_drink",
    "label": "Food And Drink",
    "count": 1
  },
  {
    "slug": "simulator golf",
    "label": "Simulator Golf",
    "count": 1
  },
  {
    "slug": "practice range",
    "label": "Practice Range",
    "count": 1
  },
  {
    "slug": "whiskey_bar",
    "label": "Whiskey Bar",
    "count": 1
  },
  {
    "slug": "family_business",
    "label": "Family Business",
    "count": 1
  },
  {
    "slug": "toledo",
    "label": "Toledo",
    "count": 1
  },
  {
    "slug": "Indoor Golf",
    "label": "Indoor Golf",
    "count": 1
  },
  {
    "slug": "Simulators",
    "label": "Simulators",
    "count": 1
  },
  {
    "slug": "Lessons",
    "label": "Lessons",
    "count": 1
  },
  {
    "slug": "Events",
    "label": "Events",
    "count": 1
  },
  {
    "slug": "Family Owned",
    "label": "Family Owned",
    "count": 1
  },
  {
    "slug": "retail_shop",
    "label": "Retail Shop",
    "count": 1
  },
  {
    "slug": "course_improvements",
    "label": "Course Improvements",
    "count": 1
  },
  {
    "slug": "alcohol",
    "label": "Alcohol",
    "count": 1
  },
  {
    "slug": "urban_location",
    "label": "Urban Location",
    "count": 1
  },
  {
    "slug": "sports_complex",
    "label": "Sports Complex",
    "count": 1
  },
  {
    "slug": "group_classes",
    "label": "Group Classes",
    "count": 1
  },
  {
    "slug": "beer_golf",
    "label": "Beer Golf",
    "count": 1
  },
  {
    "slug": "24/7 access",
    "label": "24/7 Access",
    "count": 1
  },
  {
    "slug": "booking required",
    "label": "Booking Required",
    "count": 1
  },
  {
    "slug": "online_gaming",
    "label": "Online Gaming",
    "count": 1
  },
  {
    "slug": "slot_games",
    "label": "Slot Games",
    "count": 1
  },
  {
    "slug": "betting",
    "label": "Betting",
    "count": 1
  },
  {
    "slug": "casino",
    "label": "Casino",
    "count": 1
  },
  {
    "slug": "gacor_slots",
    "label": "Gacor Slots",
    "count": 1
  },
  {
    "slug": "indonesian_market",
    "label": "Indonesian Market",
    "count": 1
  },
  {
    "slug": "vip_program",
    "label": "Vip Program",
    "count": 1
  },
  {
    "slug": "daily_bonuses",
    "label": "Daily Bonuses",
    "count": 1
  },
  {
    "slug": "secure_platform",
    "label": "Secure Platform",
    "count": 1
  },
  {
    "slug": "24_hour_support",
    "label": "24 Hour Support",
    "count": 1
  },
  {
    "slug": "mobile_events",
    "label": "Mobile Events",
    "count": 1
  },
  {
    "slug": "brand_activations",
    "label": "Brand Activations",
    "count": 1
  },
  {
    "slug": "academics",
    "label": "Academics",
    "count": 1
  },
  {
    "slug": "practice_areas",
    "label": "Practice Areas",
    "count": 1
  },
  {
    "slug": "full_service",
    "label": "Full Service",
    "count": 1
  },
  {
    "slug": "events_rentals",
    "label": "Events Rentals",
    "count": 1
  },
  {
    "slug": "virtual_lessons",
    "label": "Virtual Lessons",
    "count": 1
  },
  {
    "slug": "guaranteed_results",
    "label": "Guaranteed Results",
    "count": 1
  },
  {
    "slug": "focused_practice",
    "label": "Focused Practice",
    "count": 1
  },
  {
    "slug": "custom_solutions",
    "label": "Custom Solutions",
    "count": 1
  },
  {
    "slug": "high_tech",
    "label": "High Tech",
    "count": 1
  },
  {
    "slug": "premium_brands",
    "label": "Premium Brands",
    "count": 1
  },
  {
    "slug": "practice_tune-up",
    "label": "Practice Tune Up",
    "count": 1
  },
  {
    "slug": "home_installation",
    "label": "Home Installation",
    "count": 1
  },
  {
    "slug": "casual_dining",
    "label": "Casual Dining",
    "count": 1
  },
  {
    "slug": "social_spot",
    "label": "Social Spot",
    "count": 1
  },
  {
    "slug": "happy_hour",
    "label": "Happy Hour",
    "count": 1
  },
  {
    "slug": "self_service",
    "label": "Self Service",
    "count": 1
  },
  {
    "slug": "golf simulators",
    "label": "Golf Simulators",
    "count": 1
  },
  {
    "slug": "full bar",
    "label": "Full Bar",
    "count": 1
  },
  {
    "slug": "junior_programs",
    "label": "Junior Programs",
    "count": 1
  },
  {
    "slug": "simulator_available",
    "label": "Simulator Available",
    "count": 1
  },
  {
    "slug": "foresight_sports",
    "label": "Foresight Sports",
    "count": 1
  },
  {
    "slug": "on_course_training",
    "label": "On Course Training",
    "count": 1
  },
  {
    "slug": "golf_academy",
    "label": "Golf Academy",
    "count": 1
  },
  {
    "slug": "indoor_bays",
    "label": "Indoor Bays",
    "count": 1
  },
  {
    "slug": "lake_forest",
    "label": "Lake Forest",
    "count": 1
  },
  {
    "slug": "air_conditioned",
    "label": "Air Conditioned",
    "count": 1
  },
  {
    "slug": "quiet_studio",
    "label": "Quiet Studio",
    "count": 1
  },
  {
    "slug": "social_gathering",
    "label": "Social Gathering",
    "count": 1
  },
  {
    "slug": "social_events",
    "label": "Social Events",
    "count": 1
  },
  {
    "slug": "byob_friendly",
    "label": "Byob Friendly",
    "count": 1
  },
  {
    "slug": "skill_building",
    "label": "Skill Building",
    "count": 1
  },
  {
    "slug": "rain_or_shine",
    "label": "Rain Or Shine",
    "count": 1
  },
  {
    "slug": "structured_lessons",
    "label": "Structured Lessons",
    "count": 1
  },
  {
    "slug": "couples_friendly",
    "label": "Couples Friendly",
    "count": 1
  },
  {
    "slug": "social_leagues",
    "label": "Social Leagues",
    "count": 1
  },
  {
    "slug": "parties_and_events",
    "label": "Parties And Events",
    "count": 1
  },
  {
    "slug": "simulator_bays",
    "label": "Simulator Bays",
    "count": 1
  },
  {
    "slug": "no_membership",
    "label": "No Membership",
    "count": 1
  },
  {
    "slug": "group_rates",
    "label": "Group Rates",
    "count": 1
  },
  {
    "slug": "equipment_retail",
    "label": "Equipment Retail",
    "count": 1
  },
  {
    "slug": "online_shopping",
    "label": "Online Shopping",
    "count": 1
  },
  {
    "slug": "discounted_lessons",
    "label": "Discounted Lessons",
    "count": 1
  },
  {
    "slug": "group_learning",
    "label": "Group Learning",
    "count": 1
  },
  {
    "slug": "equipment_upgrades",
    "label": "Equipment Upgrades",
    "count": 1
  }
];

// Vibes with venues (120 categories)
export const AVAILABLE_VIBES: CategoryItem[] = [
  {
    "slug": "modern",
    "label": "Modern",
    "count": 1974
  },
  {
    "slug": "welcoming",
    "label": "Welcoming",
    "count": 1701
  },
  {
    "slug": "community_club",
    "label": "Community Club",
    "count": 1671
  },
  {
    "slug": "tech_lab",
    "label": "Tech Lab",
    "count": 1445
  },
  {
    "slug": "casual",
    "label": "Casual",
    "count": 1316
  },
  {
    "slug": "sports_bar",
    "label": "Sports Bar",
    "count": 1068
  },
  {
    "slug": "family_fun_center",
    "label": "Family Fun Center",
    "count": 841
  },
  {
    "slug": "industrial_training",
    "label": "Industrial Training",
    "count": 544
  },
  {
    "slug": "private_luxury",
    "label": "Private Luxury",
    "count": 421
  },
  {
    "slug": "upscale_lounge",
    "label": "Upscale Lounge",
    "count": 334
  },
  {
    "slug": "party_atmosphere",
    "label": "Party Atmosphere",
    "count": 233
  },
  {
    "slug": "professional",
    "label": "Professional",
    "count": 84
  },
  {
    "slug": "social",
    "label": "Social",
    "count": 25
  },
  {
    "slug": "focused",
    "label": "Focused",
    "count": 22
  },
  {
    "slug": "retro_gaming",
    "label": "Retro Gaming",
    "count": 15
  },
  {
    "slug": "professional_training",
    "label": "Professional Training",
    "count": 14
  },
  {
    "slug": "family_friendly",
    "label": "Family Friendly",
    "count": 9
  },
  {
    "slug": "speakeasy",
    "label": "Speakeasy",
    "count": 7
  },
  {
    "slug": "entertainment",
    "label": "Entertainment",
    "count": 6
  },
  {
    "slug": "instructional",
    "label": "Instructional",
    "count": 6
  },
  {
    "slug": "traditional",
    "label": "Traditional",
    "count": 4
  },
  {
    "slug": "private",
    "label": "Private",
    "count": 4
  },
  {
    "slug": "exclusive",
    "label": "Exclusive",
    "count": 4
  },
  {
    "slug": "community",
    "label": "Community",
    "count": 4
  },
  {
    "slug": "entertainment_complex",
    "label": "Entertainment Complex",
    "count": 4
  },
  {
    "slug": "tech_focused",
    "label": "Tech Focused",
    "count": 3
  },
  {
    "slug": "technical",
    "label": "Technical",
    "count": 3
  },
  {
    "slug": "scenic",
    "label": "Scenic",
    "count": 3
  },
  {
    "slug": "upscale",
    "label": "Upscale",
    "count": 3
  },
  {
    "slug": "high-tech",
    "label": "High Tech",
    "count": 3
  },
  {
    "slug": "social_lounge",
    "label": "Social Lounge",
    "count": 3
  },
  {
    "slug": "country_club",
    "label": "Country Club",
    "count": 3
  },
  {
    "slug": "practical",
    "label": "Practical",
    "count": 2
  },
  {
    "slug": "quiet",
    "label": "Quiet",
    "count": 2
  },
  {
    "slug": "professional_atmosphere",
    "label": "Professional Atmosphere",
    "count": 2
  },
  {
    "slug": "entertainment_focused",
    "label": "Entertainment Focused",
    "count": 2
  },
  {
    "slug": "community_focused",
    "label": "Community Focused",
    "count": 2
  },
  {
    "slug": "focused_training",
    "label": "Focused Training",
    "count": 2
  },
  {
    "slug": "Casual",
    "label": "Casual",
    "count": 2
  },
  {
    "slug": "Social",
    "label": "Social",
    "count": 2
  },
  {
    "slug": "relaxed",
    "label": "Relaxed",
    "count": 2
  },
  {
    "slug": "energetic",
    "label": "Energetic",
    "count": 2
  },
  {
    "slug": "training_studio",
    "label": "Training Studio",
    "count": 2
  },
  {
    "slug": "retail_space",
    "label": "Retail Space",
    "count": 2
  },
  {
    "slug": "flexible",
    "label": "Flexible",
    "count": 2
  },
  {
    "slug": "fun",
    "label": "Fun",
    "count": 2
  },
  {
    "slug": "training_focused",
    "label": "Training Focused",
    "count": 1
  },
  {
    "slug": "industrial_modern",
    "label": "Industrial Modern",
    "count": 1
  },
  {
    "slug": "performance",
    "label": "Performance",
    "count": 1
  },
  {
    "slug": "athletic",
    "label": "Athletic",
    "count": 1
  },
  {
    "slug": "premium_tech",
    "label": "Premium Tech",
    "count": 1
  },
  {
    "slug": "focused_learning",
    "label": "Focused Learning",
    "count": 1
  },
  {
    "slug": "professional_studio",
    "label": "Professional Studio",
    "count": 1
  },
  {
    "slug": "functional",
    "label": "Functional",
    "count": 1
  },
  {
    "slug": "serious_athletic",
    "label": "Serious Athletic",
    "count": 1
  },
  {
    "slug": "motivating_community",
    "label": "Motivating Community",
    "count": 1
  },
  {
    "slug": "comfortable",
    "label": "Comfortable",
    "count": 1
  },
  {
    "slug": "modern_facility",
    "label": "Modern Facility",
    "count": 1
  },
  {
    "slug": "focus_on_learning",
    "label": "Focus On Learning",
    "count": 1
  },
  {
    "slug": "club_house",
    "label": "Club House",
    "count": 1
  },
  {
    "slug": "focus",
    "label": "Focus",
    "count": 1
  },
  {
    "slug": "intensive",
    "label": "Intensive",
    "count": 1
  },
  {
    "slug": "social_sports_bar",
    "label": "Social Sports Bar",
    "count": 1
  },
  {
    "slug": "indoor_comfort",
    "label": "Indoor Comfort",
    "count": 1
  },
  {
    "slug": "training_oriented",
    "label": "Training Oriented",
    "count": 1
  },
  {
    "slug": "competitive",
    "label": "Competitive",
    "count": 1
  },
  {
    "slug": "focused_practice",
    "label": "Focused Practice",
    "count": 1
  },
  {
    "slug": "community_oriented",
    "label": "Community Oriented",
    "count": 1
  },
  {
    "slug": "focused_fun",
    "label": "Focused Fun",
    "count": 1
  },
  {
    "slug": "urban_clubhouse",
    "label": "Urban Clubhouse",
    "count": 1
  },
  {
    "slug": "elevated",
    "label": "Elevated",
    "count": 1
  },
  {
    "slug": "inclusive",
    "label": "Inclusive",
    "count": 1
  },
  {
    "slug": "data_driven",
    "label": "Data Driven",
    "count": 1
  },
  {
    "slug": "Lively",
    "label": "Lively",
    "count": 1
  },
  {
    "slug": "Family-Friendly",
    "label": "Family Friendly",
    "count": 1
  },
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 1
  },
  {
    "slug": "mobile_luxury",
    "label": "Mobile Luxury",
    "count": 1
  },
  {
    "slug": "customizable",
    "label": "Customizable",
    "count": 1
  },
  {
    "slug": "lounge",
    "label": "Lounge",
    "count": 1
  },
  {
    "slug": "upscale_resort",
    "label": "Upscale Resort",
    "count": 1
  },
  {
    "slug": "relaxed_luxury",
    "label": "Relaxed Luxury",
    "count": 1
  },
  {
    "slug": "destination_golf",
    "label": "Destination Golf",
    "count": 1
  },
  {
    "slug": "technical_modern",
    "label": "Technical Modern",
    "count": 1
  },
  {
    "slug": "community_hub",
    "label": "Community Hub",
    "count": 1
  },
  {
    "slug": "historic",
    "label": "Historic",
    "count": 1
  },
  {
    "slug": "outdoorsy",
    "label": "Outdoorsy",
    "count": 1
  },
  {
    "slug": "sports_focused",
    "label": "Sports Focused",
    "count": 1
  },
  {
    "slug": "family-oriented",
    "label": "Family Oriented",
    "count": 1
  },
  {
    "slug": "high-energy",
    "label": "High Energy",
    "count": 1
  },
  {
    "slug": "tech-forward",
    "label": "Tech Forward",
    "count": 1
  },
  {
    "slug": "indoor_outdoor_combo",
    "label": "Indoor Outdoor Combo",
    "count": 1
  },
  {
    "slug": "analytical",
    "label": "Analytical",
    "count": 1
  },
  {
    "slug": "structured",
    "label": "Structured",
    "count": 1
  },
  {
    "slug": "clean_modern",
    "label": "Clean Modern",
    "count": 1
  },
  {
    "slug": "family_friendly_center",
    "label": "Family Friendly Center",
    "count": 1
  },
  {
    "slug": "lounge_atmosphere",
    "label": "Lounge Atmosphere",
    "count": 1
  },
  {
    "slug": "spacious",
    "label": "Spacious",
    "count": 1
  },
  {
    "slug": "entertainment-focused",
    "label": "Entertainment Focused",
    "count": 1
  },
  {
    "slug": "dog_friendly",
    "label": "Dog Friendly",
    "count": 1
  },
  {
    "slug": "sports bar",
    "label": "Sports Bar",
    "count": 1
  },
  {
    "slug": "winter activity",
    "label": "Winter Activity",
    "count": 1
  },
  {
    "slug": "retro",
    "label": "Retro",
    "count": 1
  },
  {
    "slug": "modern_tech",
    "label": "Modern Tech",
    "count": 1
  },
  {
    "slug": "Modern",
    "label": "Modern",
    "count": 1
  },
  {
    "slug": "technology focused",
    "label": "Technology Focused",
    "count": 1
  },
  {
    "slug": "digital_entertainment",
    "label": "Digital Entertainment",
    "count": 1
  },
  {
    "slug": "gaming_platform",
    "label": "Gaming Platform",
    "count": 1
  },
  {
    "slug": "promotional",
    "label": "Promotional",
    "count": 1
  },
  {
    "slug": "online_service",
    "label": "Online Service",
    "count": 1
  },
  {
    "slug": "resort_atmosphere",
    "label": "Resort Atmosphere",
    "count": 1
  },
  {
    "slug": "social_lively",
    "label": "Social Lively",
    "count": 1
  },
  {
    "slug": "lively",
    "label": "Lively",
    "count": 1
  },
  {
    "slug": "autonomous",
    "label": "Autonomous",
    "count": 1
  },
  {
    "slug": "climate_controlled",
    "label": "Climate Controlled",
    "count": 1
  },
  {
    "slug": "intimate",
    "label": "Intimate",
    "count": 1
  },
  {
    "slug": "social_club",
    "label": "Social Club",
    "count": 1
  },
  {
    "slug": "retail_fitting_center",
    "label": "Retail Fitting Center",
    "count": 1
  },
  {
    "slug": "club_atmosphere",
    "label": "Club Atmosphere",
    "count": 1
  },
  {
    "slug": "professional_service",
    "label": "Professional Service",
    "count": 1
  },
  {
    "slug": "retail_environment",
    "label": "Retail Environment",
    "count": 1
  }
];

// Segments with venues (83 categories)
export const AVAILABLE_SEGMENTS: CategoryItem[] = [
  {
    "slug": "beginners",
    "label": "Beginners",
    "count": 2736
  },
  {
    "slug": "families",
    "label": "Families",
    "count": 2557
  },
  {
    "slug": "serious_golfers",
    "label": "Serious Golfers",
    "count": 2484
  },
  {
    "slug": "corporate_teams",
    "label": "Corporate Teams",
    "count": 2400
  },
  {
    "slug": "solo_practice",
    "label": "Solo Practice",
    "count": 2093
  },
  {
    "slug": "juniors_youth",
    "label": "Juniors Youth",
    "count": 1054
  },
  {
    "slug": "large_groups",
    "label": "Large Groups",
    "count": 898
  },
  {
    "slug": "coaches_instructors",
    "label": "Coaches Instructors",
    "count": 703
  },
  {
    "slug": "tourists_travelers",
    "label": "Tourists Travelers",
    "count": 312
  },
  {
    "slug": "low_handicap",
    "label": "Low Handicap",
    "count": 176
  },
  {
    "slug": "bachelor_parties",
    "label": "Bachelor Parties",
    "count": 59
  },
  {
    "slug": "casual_golfers",
    "label": "Casual Golfers",
    "count": 20
  },
  {
    "slug": "groups",
    "label": "Groups",
    "count": 13
  },
  {
    "slug": "beginner_friendly",
    "label": "Beginner Friendly",
    "count": 10
  },
  {
    "slug": "adults_only",
    "label": "Adults Only",
    "count": 8
  },
  {
    "slug": "date_night",
    "label": "Date Night",
    "count": 6
  },
  {
    "slug": "golf_enthusiasts",
    "label": "Golf Enthusiasts",
    "count": 5
  },
  {
    "slug": "kids",
    "label": "Kids",
    "count": 5
  },
  {
    "slug": "leagues",
    "label": "Leagues",
    "count": 5
  },
  {
    "slug": "social_golfers",
    "label": "Social Golfers",
    "count": 4
  },
  {
    "slug": "local_residents",
    "label": "Local Residents",
    "count": 3
  },
  {
    "slug": "homeowners",
    "label": "Homeowners",
    "count": 3
  },
  {
    "slug": "sports_fans",
    "label": "Sports Fans",
    "count": 3
  },
  {
    "slug": "casual_players",
    "label": "Casual Players",
    "count": 2
  },
  {
    "slug": "event_planners",
    "label": "Event Planners",
    "count": 2
  },
  {
    "slug": "group_friendly",
    "label": "Group Friendly",
    "count": 2
  },
  {
    "slug": "small_groups",
    "label": "Small Groups",
    "count": 2
  },
  {
    "slug": "kids_youth",
    "label": "Kids Youth",
    "count": 2
  },
  {
    "slug": "business_professionals",
    "label": "Business Professionals",
    "count": 2
  },
  {
    "slug": "social_groups",
    "label": "Social Groups",
    "count": 2
  },
  {
    "slug": "Families",
    "label": "Families",
    "count": 2
  },
  {
    "slug": "beginner_golfers",
    "label": "Beginner Golfers",
    "count": 2
  },
  {
    "slug": "golfers",
    "label": "Golfers",
    "count": 2
  },
  {
    "slug": "league players",
    "label": "League Players",
    "count": 2
  },
  {
    "slug": "golf enthusiasts",
    "label": "Golf Enthusiasts",
    "count": 2
  },
  {
    "slug": "casual golfers",
    "label": "Casual Golfers",
    "count": 2
  },
  {
    "slug": "group_bookings",
    "label": "Group Bookings",
    "count": 1
  },
  {
    "slug": "practice_seekers",
    "label": "Practice Seekers",
    "count": 1
  },
  {
    "slug": "teams",
    "label": "Teams",
    "count": 1
  },
  {
    "slug": "groups_of_friends",
    "label": "Groups Of Friends",
    "count": 1
  },
  {
    "slug": "businesses",
    "label": "Businesses",
    "count": 1
  },
  {
    "slug": "adults",
    "label": "Adults",
    "count": 1
  },
  {
    "slug": "corporate_groups",
    "label": "Corporate Groups",
    "count": 1
  },
  {
    "slug": "friends",
    "label": "Friends",
    "count": 1
  },
  {
    "slug": "golf_teams",
    "label": "Golf Teams",
    "count": 1
  },
  {
    "slug": "commercial_clients",
    "label": "Commercial Clients",
    "count": 1
  },
  {
    "slug": "recreational_golfers",
    "label": "Recreational Golfers",
    "count": 1
  },
  {
    "slug": "tech_savvy",
    "label": "Tech Savvy",
    "count": 1
  },
  {
    "slug": "technology_enthusiasts",
    "label": "Technology Enthusiasts",
    "count": 1
  },
  {
    "slug": "busy_professionals",
    "label": "Busy Professionals",
    "count": 1
  },
  {
    "slug": "tech_savvy_players",
    "label": "Tech Savvy Players",
    "count": 1
  },
  {
    "slug": "golfers_looking_to_improve",
    "label": "Golfers Looking To Improve",
    "count": 1
  },
  {
    "slug": "competitive_golfers",
    "label": "Competitive Golfers",
    "count": 1
  },
  {
    "slug": "juniors",
    "label": "Juniors",
    "count": 1
  },
  {
    "slug": "club_fitting_clients",
    "label": "Club Fitting Clients",
    "count": 1
  },
  {
    "slug": "Golfers",
    "label": "Golfers",
    "count": 1
  },
  {
    "slug": "Casual Players",
    "label": "Casual Players",
    "count": 1
  },
  {
    "slug": "Groups",
    "label": "Groups",
    "count": 1
  },
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 1
  },
  {
    "slug": "casual_gamers",
    "label": "Casual Gamers",
    "count": 1
  },
  {
    "slug": "founding_members",
    "label": "Founding Members",
    "count": 1
  },
  {
    "slug": "racing_enthusiasts",
    "label": "Racing Enthusiasts",
    "count": 1
  },
  {
    "slug": "students",
    "label": "Students",
    "count": 1
  },
  {
    "slug": "All skill levels; families; groups; corporate meetings; casual golfers.",
    "label": "All Skill Levels; Families; Groups; Corporate Meetings; Casual Golfers.",
    "count": 1
  },
  {
    "slug": "casual players",
    "label": "Casual Players",
    "count": 1
  },
  {
    "slug": "league_players",
    "label": "League Players",
    "count": 1
  },
  {
    "slug": "Golfers of all skill levels",
    "label": "Golfers Of All Skill Levels",
    "count": 1
  },
  {
    "slug": "Casual golfers",
    "label": "Casual Golfers",
    "count": 1
  },
  {
    "slug": "competitors",
    "label": "Competitors",
    "count": 1
  },
  {
    "slug": "online_gamers",
    "label": "Online Gamers",
    "count": 1
  },
  {
    "slug": "slot_enthusiasts",
    "label": "Slot Enthusiasts",
    "count": 1
  },
  {
    "slug": "indonesian_players",
    "label": "Indonesian Players",
    "count": 1
  },
  {
    "slug": "vip_members",
    "label": "Vip Members",
    "count": 1
  },
  {
    "slug": "casino_fans",
    "label": "Casino Fans",
    "count": 1
  },
  {
    "slug": "kids_friendly",
    "label": "Kids Friendly",
    "count": 1
  },
  {
    "slug": "budget_minded_golfers",
    "label": "Budget Minded Golfers",
    "count": 1
  },
  {
    "slug": "club_shoppers",
    "label": "Club Shoppers",
    "count": 1
  },
  {
    "slug": "home_owners",
    "label": "Home Owners",
    "count": 1
  },
  {
    "slug": "custom_builders",
    "label": "Custom Builders",
    "count": 1
  },
  {
    "slug": "performance_seekers",
    "label": "Performance Seekers",
    "count": 1
  },
  {
    "slug": "casual_diners",
    "label": "Casual Diners",
    "count": 1
  },
  {
    "slug": "locals",
    "label": "Locals",
    "count": 1
  },
  {
    "slug": "social_seekers",
    "label": "Social Seekers",
    "count": 1
  }
];

// Hardware with venues (135 categories)
export const AVAILABLE_HARDWARE: CategoryItem[] = [
  {
    "slug": "trackman",
    "label": "TrackMan",
    "count": 1062
  },
  {
    "slug": "foresight",
    "label": "Foresight",
    "count": 225
  },
  {
    "slug": "uneekor",
    "label": "Uneekor",
    "count": 166
  },
  {
    "slug": "full-swing",
    "label": "Full Swing",
    "count": 158
  },
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 152
  },
  {
    "slug": "skytrak",
    "label": "SkyTrak",
    "count": 103
  },
  {
    "slug": "golfzon",
    "label": "Golfzon",
    "count": 100
  },
  {
    "slug": "x-golf",
    "label": "X Golf",
    "count": 67
  },
  {
    "slug": "aboutgolf",
    "label": "AboutGolf",
    "count": 64
  },
  {
    "slug": "trugolf",
    "label": "Trugolf",
    "count": 53
  },
  {
    "slug": "flightscope",
    "label": "Flightscope",
    "count": 49
  },
  {
    "slug": "hd-golf",
    "label": "Hd Golf",
    "count": 32
  },
  {
    "slug": "toptracer",
    "label": "Toptracer",
    "count": 28
  },
  {
    "slug": "protee",
    "label": "Protee",
    "count": 24
  },
  {
    "slug": "swing-catalyst",
    "label": "Swing Catalyst",
    "count": 14
  },
  {
    "slug": "gc-quad",
    "label": "GC Quad",
    "count": 11
  },
  {
    "slug": "puttview",
    "label": "Puttview",
    "count": 11
  },
  {
    "slug": "gspro",
    "label": "Gspro",
    "count": 11
  },
  {
    "slug": "bushnell",
    "label": "Bushnell",
    "count": 8
  },
  {
    "slug": "sam",
    "label": "Sam",
    "count": 7
  },
  {
    "slug": "gc-hawk",
    "label": "Gc Hawk",
    "count": 7
  },
  {
    "slug": "apogee",
    "label": "Apogee",
    "count": 6
  },
  {
    "slug": "garmin",
    "label": "Garmin",
    "count": 6
  },
  {
    "slug": "sam-puttlab",
    "label": "Sam Puttlab",
    "count": 5
  },
  {
    "slug": "other",
    "label": "Other",
    "count": 5
  },
  {
    "slug": "capto",
    "label": "Capto",
    "count": 4
  },
  {
    "slug": "launch-monitor",
    "label": "Launch Monitor",
    "count": 4
  },
  {
    "slug": "pga-tour",
    "label": "Pga Tour",
    "count": 4
  },
  {
    "slug": "topgolf",
    "label": "Topgolf",
    "count": 4
  },
  {
    "slug": "smart2move",
    "label": "Smart2move",
    "count": 4
  },
  {
    "slug": "boditrak",
    "label": "Boditrak",
    "count": 3
  },
  {
    "slug": "sportsbox",
    "label": "Sportsbox",
    "count": 3
  },
  {
    "slug": "full-swing-golf",
    "label": "Full Swing Golf",
    "count": 3
  },
  {
    "slug": "golftec",
    "label": "Golftec",
    "count": 3
  },
  {
    "slug": "ag",
    "label": "Ag",
    "count": 3
  },
  {
    "slug": "unknown-premium",
    "label": "Unknown Premium",
    "count": 3
  },
  {
    "slug": "xgolf",
    "label": "Xgolf",
    "count": 3
  },
  {
    "slug": "optishot",
    "label": "Optishot",
    "count": 3
  },
  {
    "slug": "gchawk",
    "label": "Gchawk",
    "count": 3
  },
  {
    "slug": "premium",
    "label": "Premium",
    "count": 3
  },
  {
    "slug": "kgolf",
    "label": "Kgolf",
    "count": 3
  },
  {
    "slug": "quintic",
    "label": "Quintic",
    "count": 2
  },
  {
    "slug": "high-end",
    "label": "High End",
    "count": 2
  },
  {
    "slug": "t2",
    "label": "T2",
    "count": 2
  },
  {
    "slug": "golfvx",
    "label": "Golfvx",
    "count": 2
  },
  {
    "slug": "eyexo",
    "label": "Eyexo",
    "count": 2
  },
  {
    "slug": "pga-tour-simulator",
    "label": "Pga Tour Simulator",
    "count": 2
  },
  {
    "slug": "gears",
    "label": "Gears",
    "count": 2
  },
  {
    "slug": "golf-vx",
    "label": "Golf Vx",
    "count": 2
  },
  {
    "slug": "hackmotion",
    "label": "Hackmotion",
    "count": 2
  },
  {
    "slug": "motion2coach",
    "label": "Motion2coach",
    "count": 2
  },
  {
    "slug": "jc-video",
    "label": "Jc Video",
    "count": 2
  },
  {
    "slug": "square",
    "label": "Square",
    "count": 2
  },
  {
    "slug": "rapsodo",
    "label": "Rapsodo",
    "count": 2
  },
  {
    "slug": "benq",
    "label": "Benq",
    "count": 2
  },
  {
    "slug": "simulator",
    "label": "Simulator",
    "count": 2
  },
  {
    "slug": "high-definition-golf",
    "label": "High Definition Golf",
    "count": 2
  },
  {
    "slug": "indoor-links",
    "label": "Indoor Links",
    "count": 1
  },
  {
    "slug": "gimme",
    "label": "Gimme",
    "count": 1
  },
  {
    "slug": "visual-sports",
    "label": "Visual Sports",
    "count": 1
  },
  {
    "slug": "sams",
    "label": "Sams",
    "count": 1
  },
  {
    "slug": "h-kan-dahlby",
    "label": "H Kan Dahlby",
    "count": 1
  },
  {
    "slug": "flighscope",
    "label": "Flighscope",
    "count": 1
  },
  {
    "slug": "pro-tee",
    "label": "Pro Tee",
    "count": 1
  },
  {
    "slug": "full-swing-simulator",
    "label": "Full Swing Simulator",
    "count": 1
  },
  {
    "slug": "proteevx",
    "label": "Proteevx",
    "count": 1
  },
  {
    "slug": "swingcatalyst",
    "label": "Swingcatalyst",
    "count": 1
  },
  {
    "slug": "courses71",
    "label": "Courses71",
    "count": 1
  },
  {
    "slug": "udr",
    "label": "Udr",
    "count": 1
  },
  {
    "slug": "divot-action",
    "label": "Divot Action",
    "count": 1
  },
  {
    "slug": "red-stakes-golf",
    "label": "Red Stakes Golf",
    "count": 1
  },
  {
    "slug": "whing-golf",
    "label": "Whing Golf",
    "count": 1
  },
  {
    "slug": "gears-golf",
    "label": "Gears Golf",
    "count": 1
  },
  {
    "slug": "eye-xo2",
    "label": "Eye Xo2",
    "count": 1
  },
  {
    "slug": "bogolf",
    "label": "Bogolf",
    "count": 1
  },
  {
    "slug": "sms-screen-golf",
    "label": "Sms Screen Golf",
    "count": 1
  },
  {
    "slug": "gc",
    "label": "Gc",
    "count": 1
  },
  {
    "slug": "custom",
    "label": "Custom",
    "count": 1
  },
  {
    "slug": "full-swing-simulators",
    "label": "Full Swing Simulators",
    "count": 1
  },
  {
    "slug": "innovative-motion",
    "label": "Innovative Motion",
    "count": 1
  },
  {
    "slug": "carl-s-place",
    "label": "Carl S Place",
    "count": 1
  },
  {
    "slug": "golfjoy",
    "label": "Golfjoy",
    "count": 1
  },
  {
    "slug": "idra",
    "label": "Idra",
    "count": 1
  },
  {
    "slug": "gdr",
    "label": "Gdr",
    "count": 1
  },
  {
    "slug": "two-vision",
    "label": "Two Vision",
    "count": 1
  },
  {
    "slug": "hdgolf",
    "label": "Hdgolf",
    "count": 1
  },
  {
    "slug": "eyexyo",
    "label": "Eyexyo",
    "count": 1
  },
  {
    "slug": "eagle-club-systems",
    "label": "Eagle Club Systems",
    "count": 1
  },
  {
    "slug": "air-break",
    "label": "Air Break",
    "count": 1
  },
  {
    "slug": "putt-aim",
    "label": "Putt Aim",
    "count": 1
  },
  {
    "slug": "hybridz",
    "label": "Hybridz",
    "count": 1
  },
  {
    "slug": "x-golf-simulator",
    "label": "X Golf Simulator",
    "count": 1
  },
  {
    "slug": "e6-golf",
    "label": "E6 Golf",
    "count": 1
  },
  {
    "slug": "truegolf",
    "label": "Truegolf",
    "count": 1
  },
  {
    "slug": "e6",
    "label": "E6",
    "count": 1
  },
  {
    "slug": "chronic-golf",
    "label": "Chronic Golf",
    "count": 1
  },
  {
    "slug": "deadsolid",
    "label": "Deadsolid",
    "count": 1
  },
  {
    "slug": "gsppro",
    "label": "Gsppro",
    "count": 1
  },
  {
    "slug": "planeswing",
    "label": "Planeswing",
    "count": 1
  },
  {
    "slug": "eye-xo",
    "label": "Eye Xo",
    "count": 1
  },
  {
    "slug": "e6-connect",
    "label": "E6 Connect",
    "count": 1
  },
  {
    "slug": "3-trak",
    "label": "3 Trak",
    "count": 1
  },
  {
    "slug": "ag-golf-links",
    "label": "Ag Golf Links",
    "count": 1
  },
  {
    "slug": "ion3",
    "label": "Ion3",
    "count": 1
  },
  {
    "slug": "pga-tour-simulators",
    "label": "Pga Tour Simulators",
    "count": 1
  },
  {
    "slug": "optimotion",
    "label": "Optimotion",
    "count": 1
  },
  {
    "slug": "zen",
    "label": "Zen",
    "count": 1
  },
  {
    "slug": "sg-golf",
    "label": "Sg Golf",
    "count": 1
  },
  {
    "slug": "heradiya",
    "label": "Heradiya",
    "count": 1
  },
  {
    "slug": "k-golf",
    "label": "K Golf",
    "count": 1
  },
  {
    "slug": "rangex",
    "label": "Rangex",
    "count": 1
  },
  {
    "slug": "3trak",
    "label": "3trak",
    "count": 1
  },
  {
    "slug": "forsyth-sports",
    "label": "Forsyth Sports",
    "count": 1
  },
  {
    "slug": "premium-golf-simulator",
    "label": "Premium Golf Simulator",
    "count": 1
  },
  {
    "slug": "hack-motion",
    "label": "Hack Motion",
    "count": 1
  },
  {
    "slug": "k-vest",
    "label": "K Vest",
    "count": 1
  },
  {
    "slug": "inrange",
    "label": "Inrange",
    "count": 1
  },
  {
    "slug": "brookfields",
    "label": "Brookfields",
    "count": 1
  },
  {
    "slug": "golfforever",
    "label": "Golfforever",
    "count": 1
  },
  {
    "slug": "kit",
    "label": "Kit",
    "count": 1
  },
  {
    "slug": "trueturnpro",
    "label": "Trueturnpro",
    "count": 1
  },
  {
    "slug": "v1",
    "label": "V1",
    "count": 1
  },
  {
    "slug": "visio-putting",
    "label": "Visio Putting",
    "count": 1
  },
  {
    "slug": "pxg",
    "label": "Pxg",
    "count": 1
  },
  {
    "slug": "laser-shot",
    "label": "Laser Shot",
    "count": 1
  },
  {
    "slug": "bravo",
    "label": "Bravo",
    "count": 1
  },
  {
    "slug": "proveex",
    "label": "Proveex",
    "count": 1
  },
  {
    "slug": "chad-johansen",
    "label": "Chad Johansen",
    "count": 1
  },
  {
    "slug": "premium-launch-monitor",
    "label": "Premium Launch Monitor",
    "count": 1
  },
  {
    "slug": "par-t-golf",
    "label": "Par T Golf",
    "count": 1
  },
  {
    "slug": "gtr",
    "label": "Gtr",
    "count": 1
  },
  {
    "slug": "voice-caddie",
    "label": "Voice Caddie",
    "count": 1
  },
  {
    "slug": "impactvision",
    "label": "Impactvision",
    "count": 1
  },
  {
    "slug": "robo-golf-pro",
    "label": "Robo Golf Pro",
    "count": 1
  },
  {
    "slug": "v1-sports",
    "label": "V1 Sports",
    "count": 1
  }
];

// Amenities with venues (3 categories)
export const AVAILABLE_AMENITIES: CategoryItem[] = [
  {
    "slug": "parking",
    "label": "Parking",
    "count": 3153
  },
  {
    "slug": "coaching_available",
    "label": "Coaching",
    "count": 2342
  },
  {
    "slug": "private_rooms",
    "label": "Private Rooms",
    "count": 1188
  }
];

// Software with venues (6 categories)
export const AVAILABLE_SOFTWARE: CategoryItem[] = [
  {
    "slug": "gspro",
    "label": "GSPro",
    "count": 407
  },
  {
    "slug": "e6",
    "label": "E6 Connect",
    "count": 188
  },
  {
    "slug": "fsx",
    "label": "Fsx",
    "count": 26
  },
  {
    "slug": "trackman-virtual",
    "label": "TrackMan Virtual",
    "count": 16
  },
  {
    "slug": "tgc",
    "label": "TGC 2019",
    "count": 12
  },
  {
    "slug": "wgt",
    "label": "WGT",
    "count": 1
  }
];

// Launch monitors with venues (4 categories)
export const AVAILABLE_LAUNCH_MONITORS: CategoryItem[] = [
  {
    "slug": "unknown",
    "label": "Unknown",
    "count": 1376
  },
  {
    "slug": "radar",
    "label": "Radar",
    "count": 1216
  },
  {
    "slug": "hybrid",
    "label": "Hybrid",
    "count": 334
  },
  {
    "slug": "photometric_camera",
    "label": "Camera",
    "count": 227
  }
];

// Helper to get related links for a category (static, no DB query)
export function getStaticRelatedLinks(
  currentCategory: string,
  currentSlug: string,
  limit = 6
): Array<{ href: string; label: string; count: number }> {
  const links: Array<{ href: string; label: string; count: number }> = [];

  // Add vibes (if not current category)
  if (currentCategory !== "vibe") {
    for (const vibe of AVAILABLE_VIBES.slice(0, 2)) {
      links.push({ href: `/best/vibe/${vibe.slug}`, label: `Best ${vibe.label}`, count: vibe.count });
    }
  } else {
    // Add other vibes excluding current
    for (const vibe of AVAILABLE_VIBES.filter(v => v.slug !== currentSlug).slice(0, 2)) {
      links.push({ href: `/best/vibe/${vibe.slug}`, label: `Best ${vibe.label}`, count: vibe.count });
    }
  }

  // Add segments
  if (currentCategory !== "who-its-for") {
    for (const seg of AVAILABLE_SEGMENTS.slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/who-its-for/${seg.slug}`, label: `Best for ${seg.label}`, count: seg.count });
      }
    }
  } else {
    for (const seg of AVAILABLE_SEGMENTS.filter(s => s.slug !== currentSlug).slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/who-its-for/${seg.slug}`, label: `Best for ${seg.label}`, count: seg.count });
      }
    }
  }

  // Add hardware
  if (currentCategory !== "hardware") {
    for (const hw of AVAILABLE_HARDWARE.slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/hardware/${hw.slug}`, label: `Best ${hw.label}`, count: hw.count });
      }
    }
  } else {
    for (const hw of AVAILABLE_HARDWARE.filter(h => h.slug !== currentSlug).slice(0, 2)) {
      if (links.length < limit) {
        links.push({ href: `/best/hardware/${hw.slug}`, label: `Best ${hw.label}`, count: hw.count });
      }
    }
  }

  return links.slice(0, limit);
}

// Check if a category slug has venues
export function hasVenues(category: string, slug: string): boolean {
  switch (category) {
    case "tags": return AVAILABLE_TAGS.some(t => t.slug === slug);
    case "vibe": return AVAILABLE_VIBES.some(v => v.slug === slug);
    case "who-its-for": return AVAILABLE_SEGMENTS.some(s => s.slug === slug);
    case "hardware": return AVAILABLE_HARDWARE.some(h => h.slug === slug);
    case "amenities": return AVAILABLE_AMENITIES.some(a => a.slug === slug);
    case "software": return AVAILABLE_SOFTWARE.some(s => s.slug === slug);
    case "launch-monitor": return AVAILABLE_LAUNCH_MONITORS.some(l => l.slug === slug);
    default: return false;
  }
}
