import { db } from "../lib/db";

const sampleVenues = [
  {
    name: "Five Iron Golf - Downtown Chicago",
    slug: "five-iron-golf-downtown-chicago",
    venueType: "sim_bar",
    address: "320 N Clark St",
    city: "Chicago",
    state: "Illinois",
    zipCode: "60654",
    country: "US",
    latitude: 41.8875,
    longitude: -87.6308,
    phone: "3125550100",
    website: "https://fiveirongolf.com/locations/chicago",
    bookingUrl: "https://fiveirongolf.com/book",
    shortDescription: "Premium indoor golf simulator bar in downtown Chicago with Trackman technology. Perfect for groups, date nights, and serious practice.",
    about: "Five Iron Golf Chicago offers state-of-the-art Trackman simulators in a vibrant downtown location. With 8 simulator bays, a full bar, and food menu, it's the perfect spot for everything from serious practice to group outings.\n\nThe facility features Trackman 4 launch monitors, premium hitting mats, and a comfortable lounge atmosphere. Private rooms are available for larger groups and corporate events.",
    tags: ["date_night", "corporate_events", "serious_practice", "full_bar", "food_and_drinks"],
    vibeTags: ["premium", "social", "competitive"],
    simulatorSystems: [{ brand: "Trackman", model: "4", notes: "Professional-grade launch monitors" }],
    launchMonitorType: "radar",
    leftyFriendly: true,
    bayCount: 8,
    hasPrivateRooms: true,
    privateRoomsCount: 2,
    maxGroupSizePerBay: 6,
    pricingModel: "per_bay_hour",
    priceRangeMin: 55,
    priceRangeMax: 85,
    foodAndDrink: { food: true, alcohol: true, notes: "Full bar and kitchen menu" },
    parking: "garage",
    wifi: true,
    kidFriendly: true,
    coachingAvailable: true,
    hours: "mon:11:00-23:00|tue:11:00-23:00|wed:11:00-23:00|thu:11:00-00:00|fri:11:00-00:00|sat:09:00-00:00|sun:09:00-22:00",
    ratingTechQuality: 4.8,
    ratingFacilityComfort: 4.5,
    ratingValueForMoney: 4.0,
    ratingOverall: 4.4,
    whyGolfersLikeIt: ["Accurate Trackman data", "Great downtown location", "Excellent bar and food menu", "Friendly staff", "Clean, modern facility"],
    featured: true,
    verificationLevel: "verified",
  },
  {
    name: "GolfTec - Schaumburg",
    slug: "golftec-schaumburg",
    venueType: "training_studio",
    address: "1650 E Golf Rd",
    city: "Schaumburg",
    state: "Illinois",
    zipCode: "60173",
    country: "US",
    latitude: 42.0483,
    longitude: -88.0374,
    phone: "8475550200",
    website: "https://www.golftec.com/locations/schaumburg",
    shortDescription: "Professional golf instruction and practice facility with video analysis and launch monitors. Focus on game improvement.",
    about: "GolfTec Schaumburg offers professional golf lessons using advanced video analysis and launch monitor technology. Their certified coaches provide personalized instruction to help golfers of all levels improve their game.\n\nThe facility features indoor hitting bays with GCQuad launch monitors, video swing analysis, and custom club fitting services.",
    tags: ["serious_practice", "coaching_available", "club_fitting", "beginner_friendly"],
    vibeTags: ["training_focused", "professional"],
    simulatorSystems: [{ brand: "GCQuad", model: "GCQuad", notes: "Foresight Sports launch monitor" }],
    launchMonitorType: "photometric_camera",
    leftyFriendly: true,
    bayCount: 6,
    hasPrivateRooms: false,
    coachingAvailable: true,
    pricingModel: "per_person_hour",
    priceRangeMin: 45,
    priceRangeMax: 75,
    foodAndDrink: { food: false, alcohol: false, notes: "Water and snacks available" },
    parking: "free_lot",
    wifi: true,
    kidFriendly: true,
    hours: "mon:09:00-21:00|tue:09:00-21:00|wed:09:00-21:00|thu:09:00-21:00|fri:09:00-20:00|sat:08:00-18:00|sun:09:00-17:00",
    ratingTechQuality: 4.9,
    ratingFacilityComfort: 4.2,
    ratingValueForMoney: 4.5,
    ratingOverall: 4.5,
    whyGolfersLikeIt: ["Excellent coaching", "Detailed swing analysis", "GCQuad accuracy", "Flexible lesson packages"],
    claimed: true,
    verificationLevel: "verified",
  },
  {
    name: "Topgolf - Chicago",
    slug: "topgolf-chicago",
    venueType: "sim_bar",
    address: "699 W Thorndale Ave",
    city: "Chicago",
    state: "Illinois",
    zipCode: "60660",
    country: "US",
    latitude: 41.9933,
    longitude: -87.6467,
    phone: "3125550300",
    website: "https://topgolf.com/us/illinois/chicago",
    bookingUrl: "https://topgolf.com/us/illinois/chicago/book",
    shortDescription: "The ultimate entertainment destination with climate-controlled hitting bays, food, drinks, and golf games for all skill levels.",
    about: "Topgolf Chicago combines golf, entertainment, and dining in a high-energy environment. Using microchipped golf balls and targets, players can compete in various games while enjoying food and drinks delivered to their bay.\n\nPerfect for groups, parties, date nights, and casual golfers. No golf experience required to have a great time.",
    tags: ["date_night", "groups", "food_and_drinks", "entertainment", "kid_friendly"],
    vibeTags: ["casual", "rowdy", "social"],
    simulatorSystems: [{ brand: "Toptracer", model: "Range", notes: "Ball tracking and games" }],
    launchMonitorType: "radar",
    bayCount: 100,
    hasPrivateRooms: true,
    maxGroupSizePerBay: 6,
    pricingModel: "per_bay_hour",
    priceRangeMin: 35,
    priceRangeMax: 65,
    foodAndDrink: { food: true, alcohol: true, notes: "Full restaurant and bar service" },
    parking: "free_lot",
    wifi: true,
    kidFriendly: true,
    hours: "mon:10:00-23:00|tue:10:00-23:00|wed:10:00-23:00|thu:10:00-00:00|fri:10:00-00:00|sat:09:00-00:00|sun:09:00-23:00",
    ratingTechQuality: 4.0,
    ratingFacilityComfort: 4.8,
    ratingValueForMoney: 4.2,
    ratingOverall: 4.3,
    whyGolfersLikeIt: ["Great atmosphere", "Fun games", "Good food", "Perfect for groups", "No pressure environment"],
    featured: true,
    verificationLevel: "verified",
  },
  {
    name: "X-Golf - Naperville",
    slug: "x-golf-naperville",
    venueType: "sim_bar",
    address: "2860 Showplace Dr",
    city: "Naperville",
    state: "Illinois",
    zipCode: "60564",
    country: "US",
    latitude: 41.7489,
    longitude: -88.1665,
    phone: "6305550400",
    website: "https://playxgolf.com/locations/naperville",
    bookingUrl: "https://playxgolf.com/book",
    shortDescription: "Indoor golf simulator lounge with bar, food, and leagues. Great for practice or casual rounds with friends.",
    about: "X-Golf Naperville offers a relaxed atmosphere for golf enthusiasts and casual players alike. Featuring professional-grade simulators, a full bar, and regular leagues and tournaments.\n\nThe venue hosts weekly leagues, corporate events, and private parties. Individual simulator bays can be rented by the hour.",
    tags: ["leagues", "food_and_drinks", "corporate_events", "serious_practice"],
    vibeTags: ["casual", "competitive"],
    simulatorSystems: [{ brand: "X-Golf", model: "Simulator", notes: "X-Golf proprietary system" }],
    launchMonitorType: "hybrid",
    leftyFriendly: true,
    bayCount: 6,
    hasPrivateRooms: false,
    maxGroupSizePerBay: 8,
    pricingModel: "per_bay_hour",
    priceRangeMin: 40,
    priceRangeMax: 60,
    foodAndDrink: { food: true, alcohol: true, notes: "Bar menu and snacks" },
    parking: "free_lot",
    wifi: true,
    kidFriendly: true,
    coachingAvailable: false,
    hours: "mon:11:00-22:00|tue:11:00-22:00|wed:11:00-22:00|thu:11:00-23:00|fri:11:00-00:00|sat:10:00-00:00|sun:10:00-22:00",
    ratingTechQuality: 4.2,
    ratingFacilityComfort: 4.0,
    ratingValueForMoney: 4.3,
    ratingOverall: 4.2,
    whyGolfersLikeIt: ["Fun leagues", "Good bar atmosphere", "Reasonable rates", "Friendly competition"],
    verificationLevel: "partially_verified",
  },
  {
    name: "Indoor Golf Zone - Evanston",
    slug: "indoor-golf-zone-evanston",
    venueType: "training_studio",
    address: "1903 Dempster St",
    city: "Evanston",
    state: "Illinois",
    zipCode: "60202",
    country: "US",
    latitude: 42.0411,
    longitude: -87.6906,
    phone: "8475550500",
    website: "https://indoorgolfzone.com",
    shortDescription: "Family-owned indoor golf facility with Uneekor simulators. Focus on practice, lessons, and club fitting.",
    about: "Indoor Golf Zone is a family-owned facility providing serious golfers with quality practice time on accurate simulators. With Uneekor EYE XO launch monitors, golfers get detailed feedback on every shot.\n\nThe facility offers lessons with PGA professionals, club fitting services, and membership options for regular practice.",
    tags: ["serious_practice", "coaching_available", "club_fitting", "membership"],
    vibeTags: ["training_focused", "family"],
    simulatorSystems: [{ brand: "Uneekor", model: "EYE XO", notes: "Ceiling-mounted camera system" }],
    launchMonitorType: "photometric_camera",
    leftyFriendly: true,
    bayCount: 4,
    hasPrivateRooms: false,
    coachingAvailable: true,
    pricingModel: "per_bay_hour",
    priceRangeMin: 35,
    priceRangeMax: 50,
    parking: "street",
    wifi: true,
    kidFriendly: true,
    hours: "mon:10:00-20:00|tue:10:00-20:00|wed:10:00-20:00|thu:10:00-20:00|fri:10:00-21:00|sat:09:00-21:00|sun:10:00-18:00",
    ratingTechQuality: 4.6,
    ratingFacilityComfort: 4.0,
    ratingValueForMoney: 4.7,
    ratingOverall: 4.4,
    whyGolfersLikeIt: ["Uneekor accuracy", "Knowledgeable staff", "Great for practice", "Affordable rates"],
    verificationLevel: "partially_verified",
  },
];

async function main() {
  console.log("Seeding database...");

  // Clear existing data
  await db.favorite.deleteMany();
  await db.correctionReport.deleteMany();
  await db.submission.deleteMany();
  await db.venue.deleteMany();

  console.log("Creating venues...");

  for (const venue of sampleVenues) {
    await db.venue.create({
      data: venue as any,
    });
    console.log(`Created: ${venue.name}`);
  }

  console.log("\nSeed completed successfully!");
  console.log(`Created ${sampleVenues.length} sample venues`);
}

main()
  .catch((e) => {
    console.error("Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
